// Code generated by "stringer -type CharacterClass -trimprefix CharacterClass -linecomment -output class_string.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CharacterClassAmazon-0]
	_ = x[CharacterClassSorceress-1]
	_ = x[CharacterClassNecromancer-2]
	_ = x[CharacterClassPaladin-3]
	_ = x[CharacterClassBarbarian-4]
	_ = x[CharacterClassDruid-5]
	_ = x[CharacterClassAssassin-6]
}

const _CharacterClass_name = "AmazonSorceressNecromancerPaladinBarbarianDruidAssassin"

var _CharacterClass_index = [...]uint8{0, 6, 15, 26, 33, 42, 47, 55}

func (i CharacterClass) String() string {
	if i >= CharacterClass(len(_CharacterClass_index)-1) {
		return "CharacterClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CharacterClass_name[_CharacterClass_index[i]:_CharacterClass_index[i+1]]
}
