// Code generated by "stringer -linecomment -type LowQualityItemType -output low_quality_string.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LowQualityItemCrude-0]
	_ = x[LowQualityItemCracked-1]
	_ = x[LowQualityItemDamaged-2]
	_ = x[LowQualityItemLowQuality-3]
}

const _LowQualityItemType_name = "crudecrackeddamagedlow quality"

var _LowQualityItemType_index = [...]uint8{0, 5, 12, 19, 30}

func (i LowQualityItemType) String() string {
	if i >= LowQualityItemType(len(_LowQualityItemType_index)-1) {
		return "LowQualityItemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LowQualityItemType_name[_LowQualityItemType_index[i]:_LowQualityItemType_index[i+1]]
}
