// Code generated by "stringer -linecomment -type StoragePlace -output storage_place_string.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StorageNone-0]
	_ = x[StorageInventory-1]
	_ = x[StorageCube-4]
	_ = x[StorageStash-5]
}

const (
	_StoragePlace_name_0 = "inventory"
	_StoragePlace_name_1 = "Horadric Cubestash"
)

var (
	_StoragePlace_index_0 = [...]uint8{0, 0, 9}
	_StoragePlace_index_1 = [...]uint8{0, 13, 18}
)

func (i StoragePlace) String() string {
	switch {
	case i <= 1:
		return _StoragePlace_name_0[_StoragePlace_index_0[i]:_StoragePlace_index_0[i+1]]
	case 4 <= i && i <= 5:
		i -= 4
		return _StoragePlace_name_1[_StoragePlace_index_1[i]:_StoragePlace_index_1[i+1]]
	default:
		return "StoragePlace(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
