// Package itemdata contains data copied from https://github.com/nokka/d2s , Thanx!
// nolint:gochecknoglobals,golint,stylecheck,revive //data file
package itemdata

// HasQuantity returns true if the item has quantity bits
func (c ItemCode) HasQuantity() bool {
	// All item types that contain the quantity bits will exist in here,
	// we'll use this when reading items to make sure we only read quantity bits
	// when they exist, or we'll ruin the rest of the bit offsets for the item.
	quantityMap := map[ItemCode]bool{
		// Misc
		TownPortalBook:      true,
		IdentifyBook:        true,
		SkeletonKey:         true,
		RancidGasPotion:     true,
		OilPotion:           true,
		ChokingGasPotion:    true,
		ExplodingPotion:     true,
		StranglingGasPotion: true,
		FulmatingPotion:     true,
		Arrows:              true,
		Bolts:               true,

		// Throwables
		ThrowingKnife: true,
		ThrowingAxe:   true,
		BalancedKnife: true,
		BalancedAxe:   true,
		BattleDart:    true,
		Francisca:     true,
		WarDart:       true,
		Hurlbat:       true,
		FlyingKnife:   true,
		FlyingAxe:     true,
		WingedKnife:   true,
		WingedAxe:     true,

		// Javelins
		Javelin:            true,
		Pilum:              true,
		ShortSpear:         true,
		Glaive:             true,
		ThrowingSpear:      true,
		WarJavelin:         true,
		GreatPilum:         true,
		Simbilan:           true,
		Spiculum:           true,
		Harpoon:            true,
		HyperionJavelin:    true,
		StygianPilum:       true,
		BalrogSpear:        true,
		GhostGlaive:        true,
		WingedHarpoon:      true,
		MaidenJavelin:      true,
		CeremonialJavelin:  true,
		MatriarchalJavelin: true,
	}

	_, ok := quantityMap[c]

	return ok
}

// IsTome returns true if the item is a tome
func (c ItemCode) IsTome() bool {
	// Items that are tomes contain 5 extra bits, so we need to keep track of what
	// items are tomes, and read the bits accordingly.
	tomeMap := map[ItemCode]bool{
		TownPortalBook: true,
		IdentifyBook:   true,
	}

	_, ok := tomeMap[c]

	return ok
}

// ShieldCodes shield item codes mapped to their in game, human-friendly, readable name.
// nolint:gochecknoglobals // data variable
var ShieldCodes = map[ItemCode]string{
	Aegis:            "Aegis",
	AerinShield:      "Aerin Shield",
	AkaranRondache:   "Akaran Rondache",
	AkaranTarge:      "Akaran Targe",
	KurastShield:     "Kurast Shield",
	AncientShield:    "Ancient Shield",
	BarbedShield:     "Barbed Shield",
	BladeBarrier:     "Blade Barrier",
	BloodlordSkull:   "Bloodlord Skull",
	BoneShield:       "Bone Shield",
	Buckler:          "Buckler",
	CantorTrophy:     "Cantor Trophy",
	CrownShield:      "Crown Shield",
	Defender:         "Defender",
	DemonHead:        "Demon Head",
	DragonShield:     "Dragon Shield",
	FetishTrophy:     "Fetish Trophy",
	GargoyleHead:     "Gargoyle Head",
	GothicShield:     "Gothic Shield",
	GrimShield:       "Grim Shield",
	GildedShield:     "Gilded Shield",
	HeirophantTrophy: "Heirophant Trophy",
	Heater:           "Heater",
	HellspawnSkull:   "Hellspawn Skull",
	HeraldicShield:   "Heraldic Shield",
	KiteShield:       "Kite Shield",
	LargeShield:      "Large Shield",
	Luna:             "Luna",
	MinionSkull:      "Minion Skull",
	Monarch:          "Monarch",
	MummifiedTrophy:  "Mummified Trophy",
	OverseerSkull:    "Overseer Skull",
	Pavise:           "Pavise",
	PreservedHead:    "Preserved Head",
	ProtectorShield:  "Protector Shield",
	Rondache:         "Rondache",
	RoundShield:      "Round Shield",
	RoyalShield:      "Royal Shield",
	SacredRondache:   "Sacred Rondache",
	SacredTarge:      "Sacred Targe",
	Scutum:           "Scutum",
	SextonTrophy:     "Sexton Trophy",
	SmallShield:      "Small Shield",
	SpikedShield:     "Spiked Shield",
	SuccubusSkull:    "Succubus Skull",
	Targe:            "Targe",
	TowerShield:      "Tower Shield",
	TrollNest:        "Troll Nest",
	UnravellerHead:   "Unraveller Head",
	VortexShield:     "Vortex Shield",
	Ward:             "Ward",
	ZakarumShield:    "Zakarum Shield",
	ZombieHead:       "Zombie Head",
}

// ArmorCodes - Armor item codes mapped to their in game, human-friendly, readable name.
// nolint:gochecknoglobals // data variable
var ArmorCodes = map[ItemCode]string{
	AlphaHelm:         "Alpha Helm",
	AncientArmor:      "Ancient Armor",
	Antlers:           "Antlers",
	ArchonPlate:       "Archon Plate",
	Armet:             "Armet",
	AssaultHelmet:     "Assault Helmet",
	AvengerGuard:      "Avenger Guard",
	BalrogSkin:        "Balrog Skin",
	Basinet:           "Basinet",
	BattleBelt:        "Battle Belt",
	BattleBoots:       "Battle Boots",
	BattleGauntlets:   "Battle Gauntlets",
	Belt:              "Belt",
	BloodSpirit:       "Blood Spirit",
	BoneHelm:          "Bone Helm",
	BoneVisage:        "Bone Visage",
	Boneweave:         "Boneweave",
	BoneweaveBoots:    "Boneweave Boots",
	Bracers:           "Bracers",
	BrambleMitts:      "Bramble Mitts",
	BreastPlate:       "Breast Plate",
	Cap:               "Cap",
	CarnageHelm:       "Carnage Helm",
	Casque:            "Casque",
	ChainBoots:        "Chain Boots",
	ChainMail:         "Chain Mail",
	ChaosArmor:        "Chaos Armor",
	Circlet:           "Circlet",
	ColossusGirdle:    "Colossus Girdle",
	ConquerorCrown:    "Conqueror Crown",
	Corona:            "Corona",
	Coronet:           "Coronet",
	Crown:             "Crown",
	CrusaderGauntlets: "Crusader Gauntlets",
	Cuirass:           "Cuirass",
	DeathMask:         "Death Mask",
	Demonhead:         "Demonhead",
	DemonhideArmor:    "Demonhide Armor",
	DemonhideBoots:    "Demonhide Boots",
	DemonhideGloves:   "Demonhide Gloves",
	DemonhideSash:     "Demonhide Sash",
	DestroyerHelm:     "Destroyer Helm",
	Diadem:            "Diadem",
	DiamondMail:       "Diamond Mail",
	DreamSpirit:       "Dream Spirit",
	DuskShroud:        "Dusk Shroud",
	EarthSpirit:       "Earth Spirit",
	EmbossedPlate:     "Embossed Plate",
	FalconMask:        "Falcon Mask",
	FangedHelm:        "Fanged Helm",
	FieldPlate:        "Field Plate",
	FullHelm:          "Full Helm",
	PlateMail:         "Plate Mail",
	FullPlateMail:     "Full Plate Mail",
	FuryVisor:         "Fury Visor",
	Gauntlets:         "Gauntlets",
	GhostArmor:        "Ghost Armor",
	GiantConch:        "Giant Conch",
	Girdle:            "Girdle",
	Gloves:            "Gloves",
	GothicPlate:       "Gothic Plate",
	GrandCrown:        "Grand Crown",
	GreatHauberk:      "Great Hauberk",
	GreatHelm:         "Great Helm",
	GriffonHeadress:   "Griffon Headress",
	GrimHelm:          "Grim Helm",
	GuardianCrown:     "Guardian Crown",
	HardLeatherArmor:  "Hard Leather Armor",
	HawkHelm:          "Hawk Helm",
	HeavyBelt:         "Heavy Belt",
	HeavyBoots:        "Heavy Boots",
	HeavyBracers:      "Heavy Bracers",
	HeavyGloves:       "Heavy Gloves",
	HellforgedPlate:   "Hellforged Plate",
	Helm:              "Helm",
	HornedHelm:        "Horned Helm",
	HuntersGuise:      "Hunter's Guise",
	Hydraskull:        "Hydraskull",
	Hyperion:          "Hyperion",
	JawboneCap:        "Jawbone Cap",
	JawboneVisor:      "Jawbone Visor",
	KrakenShell:       "Kraken Shell",
	LacqueredPlate:    "Lacquered Plate",
	LeatherArmor:      "Leather Armor",
	LeatherBoots:      "Leather Boots",
	LightBelt:         "Light Belt",
	LightGauntlets:    "Light Gauntlets",
	LightPlate:        "Light Plate",
	LightPlatedBoots:  "Light Plated Boots",
	LinkedMail:        "Linked Mail",
	LionHelm:          "Lion Helm",
	LoricatedMail:     "Loricated Mail",
	MagePlate:         "Mage Plate",
	Mask:              "Mask",
	MeshArmor:         "Mesh Armor",
	MeshBelt:          "Mesh Belt",
	MeshBoots:         "Mesh Boots",
	MirroredBoots:     "Mirrored Boots",
	MithrilCoil:       "Mithril Coil",
	MyrmidonGreaves:   "Myrmidon Greaves",
	OgreGauntlets:     "Ogre Gauntlets",
	OrnatePlate:       "Ornate Plate",
	PlateBoots:        "Plate Boots",
	QuiltedArmor:      "Quilted Armor",
	RageMask:          "Rage Mask",
	RingMail:          "Ring Mail",
	RussetArmor:       "Russet Armor",
	SacredArmor:       "Sacred Armor",
	SacredFeathers:    "Sacred Feathers",
	Sallet:            "Sallet",
	Sash:              "Sash",
	SavageHelmet:      "Savage Helmet",
	ScaleMail:         "Scale Mail",
	ScarabHusk:        "Scarab Husk",
	ScarabshellBoots:  "Scarabshell Boots",
	SerpentskinArmor:  "Serpentskin Armor",
	ShadowPlate:       "Shadow Plate",
	Shako:             "Shako",
	SharkskinBelt:     "Sharkskin Belt",
	SharkskinBoots:    "Sharkskin Boots",
	SharkskinGloves:   "Sharkskin Gloves",
	SharktoothArmor:   "Sharktooth Armor",
	SkullCap:          "Skull Cap",
	SkySpirit:         "Sky Spirit",
	SlayerGuard:       "Slayer Guard",
	SpiderwebSash:     "Spiderweb Sash",
	SpiredHelm:        "Spired Helm",
	SpiritMask:        "Spirit Mask",
	SplintMail:        "Splint Mail",
	StuddedLeather:    "Studded Leather",
	SunSpirit:         "Sun Spirit",
	TemplarCoat:       "Templar Coat",
	Tiara:             "Tiara",
	TigulatedMail:     "Tigulated Mail",
	TotemicMask:       "Totemic Mask",
	TrellisedArmor:    "Trellised Armor",
	TrollBelt:         "Troll Belt",
	Vambraces:         "Vambraces",
	VampireboneGloves: "Vampirebone Gloves",
	VampirefangBelt:   "Vampirefang Belt",
	WarBelt:           "War Belt",
	WarBoots:          "War Boots",
	WarGauntlets:      "War Gauntlets",
	WarHat:            "War Hat",
	WingedHelm:        "Winged Helm",
	WireFleece:        "Wire Fleece",
	WolfHead:          "Wolf Head",
	Wyrmhide:          "Wyrmhide",
	WyrmhideBoots:     "Wyrmhide Boots",
}

// WeaponCodes: Weapon item codes mapped to their in game, human-friendly, readable name.
// nolint:gochecknoglobals // data variable
var WeaponCodes = map[ItemCode]string{
	AncientAxe:          "Ancient Axe",
	AncientSword:        "Ancient Sword",
	Arbalest:            "Arbalest",
	ArchonStaff:         "Archon Staff",
	AshwoodBow:          "Ashwood Bow",
	Ataghan:             "Ataghan",
	Axe:                 "Axe",
	BalancedAxe:         "Balanced Axe",
	BalancedKnife:       "Balanced Knife",
	Balista:             "Balista",
	BalrogBlade:         "Balrog Blade",
	BalrogSpear:         "Balrog Spear",
	BarbedClub:          "Barbed Club",
	Bardiche:            "Bardiche",
	BastardSword:        "Bastard Sword",
	BattleAxe:           "Battle Axe",
	BattleCestus:        "Battle Cestus",
	BattleDart:          "Battle Dart",
	BattleHammer:        "Battle Hammer",
	BattleScythe:        "Battle Scythe",
	BattleStaff:         "Battle Staff",
	BattleSword:         "Battle Sword",
	BeardedAxe:          "Bearded Axe",
	BecDeCorbin:         "Bec De Corbin",
	BerserkerAxe:        "Berserker Axe",
	Bill:                "Bill",
	Blade:               "Blade",
	BladeBow:            "Blade Bow",
	BladeTalons:         "Blade Talons",
	BoneKnife:           "Bone Knife",
	BoneWand:            "Bone Wand",
	Brandistock:         "Brandistock",
	BroadAxe:            "Broad Axe",
	BroadSword:          "Broad Sword",
	BurntWand:           "Burnt Wand",
	Caduceus:            "Caduceus",
	CedarBow:            "Cedar Bow",
	CedarStaff:          "Cedar Staff",
	CeremonialBow:       "Ceremonial Bow",
	CeremonialJavelin:   "Ceremonial Javelin",
	CeremonialPike:      "Ceremonial Pike",
	CeremonialSpear:     "Ceremonial Spear",
	Cestus:              "Cestus",
	ChampionAxe:         "Champion Axe",
	ChampionSword:       "Champion Sword",
	ChokingGasPotion:    "Choking Gas Potion",
	ChuKoNu:             "Chu-Ko-Nu",
	Cinquedeas:          "Cinquedeas",
	ClaspedOrb:          "Clasped Orb",
	Claws:               "Claws",
	Claymore:            "Claymore",
	Cleaver:             "Cleaver",
	CloudySphere:        "Cloudy Sphere",
	Club:                "Club",
	ColossalSword:       "Colossal Sword",
	ColossalBlade:       "Colossal Blade",
	ColossusCrossbow:    "Colossus Crossbow",
	ColossusVoulge:      "Colossus Voulge",
	CompositeBow:        "Composite Bow",
	ConquestSword:       "Conquest Sword",
	Crossbow:            "Crossbow",
	Crowbill:            "Crowbill",
	CrusaderBow:         "Crusader Bow",
	CrypticAxe:          "Cryptic Axe",
	CrypticSword:        "Cryptic Sword",
	CrystalSword:        "Crystal Sword",
	CrystallineGlobe:    "Crystalline Globe",
	Cudgel:              "Cudgel",
	Cutlass:             "Cutlass",
	DacianFalx:          "Dacian Falx",
	Dagger:              "Dagger",
	Decapitator:         "Decapitator",
	DecoyDagger:         "Decoy Dagger",
	DemonCrossbow:       "Demon Crossbow",
	DemonHeart:          "Demon Heart",
	DevilStar:           "Devil Star",
	DiamondBow:          "Diamond Bow",
	DimensionalBlade:    "Dimensional Blade",
	DimensionalShard:    "Dimensional Shard",
	Dirk:                "Dirk",
	DivineScepter:       "Divine Scepter",
	DoubleAxe:           "Double Axe",
	DoubleBow:           "Double Bow",
	DragonStone:         "Dragon Stone",
	EableOrb:            "Eable Orb",
	EdgeBow:             "Edge Bow",
	ElderStaff:          "Elder Staff",
	EldritchOrb:         "Eldritch Orb",
	ElegantBlade:        "Elegant Blade",
	Espadon:             "Espadon",
	EttinAxe:            "Ettin Axe",
	ExecutionerSword:    "Executioner Sword",
	ExplodingPotion:     "Exploding Potion",
	Falcata:             "Falcata",
	Falchion:            "Falchion",
	FangedKnife:         "Fanged Knife",
	Fascia:              "Fascia",
	FeralAxe:            "Feral Axe",
	FeralClaws:          "Feral Claws",
	Flail:               "Flail",
	Flamberge:           "Flamberge",
	FlangedMace:         "Flanged Mace",
	FlyingAxe:           "Flying Axe",
	FlyingKnife:         "Flying Knife",
	Francisca:           "Francisca",
	FulmatingPotion:     "Fulmating Potion",
	Fuscina:             "Fuscina",
	GhostGlaive:         "Ghost Glaive",
	GhostSpear:          "Ghost Spear",
	GhostWand:           "Ghost Wand",
	GiantAxe:            "Giant Axe",
	GiantSword:          "Giant Sword",
	GiantThresher:       "Giant Thresher",
	Gidbinn:             "Gidbinn",
	Gladius:             "Gladius",
	Glaive:              "Glaive",
	GloriousAxe:         "Glorious Axe",
	GlowingOrb:          "Glowing Orb",
	GnarledStaff:        "Gnarled Staff",
	GorgonCrossbow:      "Gorgon Crossbow",
	GothicAxe:           "Gothic Axe",
	GothicBow:           "Gothic Bow",
	GothicStaff:         "Gothic Staff",
	GothicSword:         "Gothic Sword",
	GrandMatronBow:      "Grand Matron Bow",
	GrandScepter:        "Grand Scepter",
	GraveWand:           "Grave Wand",
	GreatAxe:            "Great Axe",
	GreatBow:            "Great Bow",
	GreatMaul:           "Great Maul",
	GreatPilum:          "Great Pilum",
	GreatPoleaxe:        "Great Poleaxe",
	GreatSword:          "Great Sword",
	GreaterClaws:        "Greater Claws",
	GreaterTalons:       "Greater Talons",
	GrimScythe:          "Grim Scythe",
	GrimWand:            "Grim Wand",
	Halberd:             "Halberd",
	HandAxe:             "Hand Axe",
	HandScythe:          "Hand Scythe",
	Harpoon:             "Harpoon",
	Hatchet:             "Hatchet",
	HatchetHands:        "HatchetHands",
	HeavenlyStone:       "Heavenly Stone",
	HeavyCrossbow:       "Heavy Crossbow",
	HellforgeHammer:     "Hellforge Hammer",
	HighlandBlade:       "Highland Blade",
	HolyWaterSprinkler:  "Holy Water Sprinkler",
	HoradricMalus:       "Horadric Malus",
	HoradricStaff:       "Horadric Staff",
	HuntersBow:          "Hunters Bow",
	Hurlbat:             "Hurlbat",
	HydraBow:            "Hydra Bow",
	HydraEdge:           "Hydra Edge",
	HyperionJavelin:     "Hyperion Javelin",
	HyperionSpear:       "Hyperion Spear",
	JaggedStar:          "Jagged Star",
	Javelin:             "Javelin",
	JoStaff:             "Jo Staff",
	Katar:               "Katar",
	KhalimFlail:         "Khalim Flail",
	Knout:               "Knout",
	Kriss:               "Kriss",
	Lance:               "Lance",
	LargeAxe:            "Large Axe",
	LegendSpike:         "Legend Spike",
	LegendSword:         "Legend Sword",
	LegendaryMallet:     "Legendary Mallet",
	LichWand:            "Lich Wand",
	LightCrossbow:       "Light Crossbow",
	LochaberAxe:         "Lochaber Axe",
	LongBattleBow:       "Long Battle Bow",
	LongBow:             "Long Bow",
	LongSiegeBow:        "Long Siege Bow",
	LongStaff:           "Long Staff",
	LongSword:           "Long Sword",
	LongWarBow:          "Long War Bow",
	Mace:                "Mace",
	MaidenJavelin:       "Maiden Javelin",
	MaidenPike:          "Maiden Pike",
	MaidenSpear:         "Maiden Spear",
	Mancatcher:          "Mancatcher",
	MarteldeFer:         "Martel de Fer",
	MatriarchalBow:      "Matriarchal Bow",
	MatriarchalPike:     "Matriarchal Pike",
	MatriarchalSpear:    "Matriarchal Spear",
	MatriarchalJavelin:  "Matriarchal Javelin",
	Maul:                "Maul",
	MightyScepter:       "Mighty Scepter",
	MilitaryAxe:         "Military Axe",
	MilitaryPick:        "Military Pick",
	MithralPoint:        "Mithral Point",
	MorningStar:         "Morning Star",
	MythicalSword:       "Mythical Sword",
	Naga:                "Naga",
	OgreAxe:             "Ogre Axe",
	OgreMaul:            "Ogre Maul",
	OilPotion:           "Oil Potion",
	Partizan:            "Partizan",
	PelletBow:           "Pellet Bow",
	PetrifiedWand:       "Petrified Wand",
	PhaseBlade:          "Phase Blade",
	Pike:                "Pike",
	Pilum:               "Pilum",
	Poignard:            "Poignard",
	Poleaxe:             "Poleaxe",
	PolishedWand:        "Polished Wand",
	QuarterStaff:        "Quarter Staff",
	Quhab:               "Quhab",
	RancidGasPotion:     "Rancid Gas Potion",
	RazorBow:            "Razor Bow",
	ReflexBow:           "Reflex Bow",
	ReinforcedMace:      "Reinforced Mace",
	RepeatingCrossbow:   "Repeating Crossbow",
	Rondel:              "Rondel",
	RuneBow:             "Rune Bow",
	RuneScepter:         "Rune Scepter",
	RuneStaff:           "Rune Staff",
	RuneSword:           "Rune Sword",
	RunicTalons:         "Runic Talons",
	Sabre:               "Sabre",
	SacredGlobe:         "Sacred Globe",
	Scepter:             "Scepter",
	Scimitar:            "Scimitar",
	ScissorsKatar:       "Scissors Katar",
	ScissorsQuhab:       "Scissors Quhab",
	ScissorsSuwayyah:    "Scissors Suwayyah",
	Scourge:             "Scourge",
	Scythe:              "Scythe",
	SeraphRod:           "Seraph Rod",
	ShadowBow:           "Shadow Bow",
	Shamshir:            "Shamshir",
	Shillelah:           "Shillelah",
	ShortBattleBow:      "Short Battle Bow",
	ShortBow:            "Short Bow",
	ShortSiegeBow:       "Short Siege Bow",
	ShortSpear:          "Short Spear",
	ShortStaff:          "Short Staff",
	ShortSword:          "Short Sword",
	ShortWarBow:         "Short War Bow",
	SiegeCrossbow:       "Siege Crossbow",
	SilverEdgedAxe:      "Silver Edged Axe",
	Simbilan:            "Simbilan",
	SmallCrescent:       "Small Crescent",
	SmokedSphere:        "Smoked Sphere",
	SparklingBall:       "Sparkling Ball",
	Spear:               "Spear",
	Spetum:              "Spetum",
	Spiculum:            "Spiculum",
	SpiderBow:           "Spider Bow",
	SpikedClub:          "Spiked Club",
	StaffOfTheKings:     "Staff Of The Kings",
	StagBow:             "Stag Bow",
	Stalagmite:          "Stalagmite",
	Stilleto:            "Stilleto",
	StranglingGasPotion: "Strangling Gas Potion",
	StygianPike:         "Stygian Pike",
	StygianPilum:        "Stygian Pilum",
	SuperKhalimFlail:    "Super Khalim Flail",
	Suwayyah:            "Suwayyah",
	SwirlingCrystal:     "Swirling Crystal",
	Tabar:               "Tabar",
	Thresher:            "Thresher",
	ThrowingAxe:         "Throwing Axe",
	ThrowingKnife:       "Throwing Knife",
	ThrowingSpear:       "Throwing Spear",
	ThunderMaul:         "Thunder Maul",
	Tomahawk:            "Tomahawk",
	TombWand:            "Tomb Wand",
	Trident:             "Trident",
	Truncheon:           "Truncheon",
	Tulwar:              "Tulwar",
	TuskSword:           "Tusk Sword",
	TwinAxe:             "Twin Axe",
	TwoHandedSword:      "Two Handed Sword",
	TyrantClub:          "Tyrant Club",
	UnearthedWand:       "Unearthed Wand",
	VortexOrb:           "Vortex Orb",
	Voulge:              "Voulge",
	WalkingStick:        "Walking Stick",
	Wand:                "Wand",
	WarAxe:              "War Axe",
	WarClub:             "War Club",
	WarDart:             "War Dart",
	WarFist:             "War Fist",
	WarFork:             "War Fork",
	WarHammer:           "War Hammer",
	WarJavelin:          "War Javelin",
	WarPike:             "War Pike",
	WarScepter:          "War Scepter",
	WarScythe:           "War Scythe",
	WarSpear:            "War Spear",
	WarSpike:            "War Spike",
	WarStaff:            "War Staff",
	WarSword:            "War Sword",
	WardBow:             "Ward Bow",
	WingedAxe:           "Winged Axe",
	WingedHarpoon:       "Winged Harpoon",
	WingedKnife:         "Winged Knife",
	WirtsLeg:            "Wirts Leg",
	WristBlade:          "Wrist Blade",
	WristSpike:          "Wrist Spike",
	WristSword:          "Wrist Sword",
	Yari:                "Yari",
	YewWand:             "Yew Wand",
	Zweihander:          "Zweihander",
}

// MiscCodes - Misc items codes, like jewelry, gems, potions and runes, mapped to their in
// game, human-friendly, readable name.
// nolint:gochecknoglobals // data var
var MiscCodes = map[ItemCode]string{
	Amethyst:                      "Amethyst",
	AmnRune:                       "Amn Rune",
	Amulet:                        "Amulet",
	AntidotePotion:                "Antidote Potion",
	Arrows:                        "Arrows",
	BaalsEye:                      "Baal's Eye",
	BarkScroll:                    "Bark Scroll",
	BerRune:                       "Ber Rune",
	Bolts:                         "Bolts",
	BookofSkill:                   "Book of Skill",
	BurningEssenceofTerror:        "Burning Essence of Terror",
	ChamRune:                      "Cham Rune",
	ChargedEssenceofHatred:        "Charged Essence of Hatred",
	GrandCharm:                    "Grand Charm",
	LargeCharm:                    "Large Charm",
	SmallCharm:                    "Small Charm",
	ChippedAmethyst:               "Chipped Amethyst",
	ChippedDiamond:                "Chipped Diamond",
	ChippedEmerald:                "Chipped Emerald",
	ChippedRuby:                   "Chipped Ruby",
	ChippedSapphire:               "Chipped Sapphire",
	ChippedSkull:                  "Chipped Skull",
	ChippedTopaz:                  "Chipped Topaz",
	DecipheredBarkScroll:          "Deciphered Bark Scroll",
	DiablosHorn:                   "Diablo's Horn",
	Diamond:                       "Diamond",
	DolRune:                       "Dol Rune",
	ElRune:                        "El Rune",
	EldRune:                       "Eld Rune",
	Elixir:                        "Elixir",
	Emerald:                       "Emerald",
	EthRune:                       "Eth Rune",
	FalRune:                       "Fal Rune",
	FesteringEssenceofDestruction: "Festering Essence of Destruction",
	FlawedAmethyst:                "Flawed Amethyst",
	FlawedDiamond:                 "Flawed Diamond",
	FlawedEmerald:                 "Flawed Emerald",
	FlawedRuby:                    "Flawed Ruby",
	FlawedSapphire:                "Flawed Sapphire",
	FlawedSkull:                   "Flawed Skull",
	FlawedTopaz:                   "Flawed Topaz",
	FlawlessAmethyst:              "Flawless Amethyst",
	FlawlessDiamond:               "Flawless Diamond",
	FlawlessEmerald:               "Flawless Emerald",
	FlawlessRuby:                  "Flawless Ruby",
	FlawlessSapphire:              "Flawless Sapphire",
	FlawlessSkull:                 "Flawless Skull",
	FlawlessTopaz:                 "Flawless Topaz",
	FullHealingPotion:             "Full Healing Potion",
	FullManaPotion:                "Full Mana Potion",
	FullRejuvenationPotion:        "Full Rejuvenation Potion",
	Gold:                          "Gold",
	GoldBird:                      "Gold Bird",
	GreaterHealingPotion:          "Greater Healing Potion",
	GreaterManaPotion:             "Greater Mana Potion",
	GulRune:                       "Gul Rune",
	HealingPotion:                 "Healing Potion",
	HealingPotionMid:              "Healing Potion",
	HelRune:                       "Hel Rune",
	Herb:                          "Herb",
	HoradricCube:                  "Horadric Cube",
	IdentifyBook:                  "Identify Book",
	IdentifyScroll:                "Identify Scroll",
	IoRune:                        "Io Rune",
	IstRune:                       "Ist Rune",
	IthRune:                       "Ith Rune",
	JadeFigurine:                  "Jade Figurine",
	JahRune:                       "Jah Rune",
	Jewel:                         "Jewel",
	KeyofDestruction:              "Key of Destruction",
	KeyofHate:                     "Key of Hate",
	KeyofTerror:                   "Key of Terror",
	KhalimsBrain:                  "Khalim's Brain",
	KhalimsEye:                    "Khalim's Eye",
	KhalimsHeart:                  "Khalim's Heart",
	KoRune:                        "Ko Rune",
	LamEsensTome:                  "Lam Esens Tome",
	LargeBluePotion:               "Large Blue Potion",
	LargeRedPotion:                "Large Red Potion",
	LemRune:                       "Lem Rune",
	LesserHealingPotion:           "Lesser Healing Potion",
	LesserManaPotion:              "Lesser Mana Potion",
	LightHealingPotion:            "Light Healing Potion",
	LightManaPotion:               "Light Mana Potion",
	LoRune:                        "Lo Rune",
	LumRune:                       "Lum Rune",
	Maguffin:                      "Maguffin",
	MalRune:                       "Mal Rune",
	ManaPotion:                    "Mana Potion",
	ManaPotionMid:                 "Mana Potion",
	MephistosBrain:                "Mephisto's Brain",
	MephistoKey:                   "Mephisto Key",
	MephistoSoulStone:             "Mephisto Soul Stone",
	NefRune:                       "Nef Rune",
	OhmRune:                       "Ohm Rune",
	OrtRune:                       "Ort Rune",
	PerfectAmethyst:               "Perfect Amethyst",
	PerfectDiamond:                "Perfect Diamond",
	PerfectEmerald:                "Perfect Emerald",
	PerfectRuby:                   "Perfect Ruby",
	PerfectSapphire:               "Perfect Sapphire",
	PerfectSkull:                  "Perfect Skull",
	PerfectTopaz:                  "Perfect Topaz",
	PlayerEar:                     "Player Ear",
	PulRune:                       "Pul Rune",
	RalRune:                       "Ral Rune",
	RejuvenationPotion:            "Rejuvenation Potion",
	Ring:                          "Ring",
	Ruby:                          "Ruby",
	Sapphire:                      "Sapphire",
	Scroll:                        "Scroll",
	ScrollofHoradric:              "Scroll of Horadric",
	ScrollofMalah:                 "Scroll of Malah",
	PotionofLife:                  "Potion of Life",
	ShaelRune:                     "Shael Rune",
	SkeletonKey:                   "Skeleton Key",
	Skull:                         "Skull",
	SmallBluePotion:               "Small Blue Potion",
	SmallRedPotion:                "Small Red Potion",
	SolRune:                       "Sol Rune",
	StaminaPotion:                 "Stamina Potion",
	StandardofHeroes:              "Standard of Heroes",
	StrongHealingPotion:           "Strong Healing Potion",
	StrongManaPotion:              "Strong Mana Potion",
	SurRune:                       "Sur Rune",
	TalRune:                       "Tal Rune",
	ThawingPotion:                 "Thawing Potion",
	ThulRune:                      "Thul Rune",
	TirRune:                       "Tir Rune",
	TokenofAbsolution:             "Token of Absolution",
	Topaz:                         "Topaz",
	Torch:                         "Torch",
	TownPortalBook:                "Town Portal Book",
	TownPortalScroll:              "Town Portal Scroll",
	TwistedEssenceofSuffering:     "Twisted Essence of Suffering",
	UmRune:                        "Um Rune",
	VexRune:                       "Vex Rune",
	ViperAmulet:                   "Viper Amulet",
	ZodRune:                       "Zod Rune",
}

var UniqueNames = map[uint16]string{
	0:   "The Gnasher",
	1:   "Deathspade",
	2:   "Bladebone",
	3:   "Skull splitter",
	4:   "Rakescar",
	5:   "Axe of Fechmar",
	6:   "Goreshovel",
	7:   "The Chiefthan",
	8:   "Brainhew",
	9:   "Humongous",
	10:  "Torch of Iros",
	11:  "Maelstorm",
	12:  "Gravenspine",
	13:  "Umes Lament",
	14:  "Felloak",
	15:  "Knell Striker",
	16:  "Rusthandle",
	17:  "Stormeye",
	18:  "Stoutnail",
	19:  "Crushflange",
	20:  "Bloodrise",
	21:  "The Generals Tan Do Li Ga",
	22:  "Ironstone",
	23:  "Bonesnap",
	24:  "Steeldriver",
	25:  "Rixot's Keen",
	26:  "Blood Crescent",
	27:  "Skewer of Krintiz",
	28:  "Gleamscythe",
	29:  "Azurewrath",
	30:  "Griswold's Edge",
	31:  "Hellplague",
	32:  "Culwens Point",
	33:  "Shadowfang",
	34:  "Soulflay",
	35:  "Kinemils Awl",
	36:  "Blacktongue",
	37:  "Ripsaw",
	38:  "The Patriarch",
	39:  "Gull",
	40:  "The Diggler",
	41:  "The Jade Tan Do",
	42:  "Spectral Shard",
	43:  "The Dragon Chang",
	44:  "Razortine",
	45:  "Bloodthief",
	46:  "Lance of Yaggai",
	47:  "The Tannr Gorerod",
	48:  "Dimoaks Hew",
	49:  "Steelgoad",
	50:  "Soul Harvest",
	51:  "The Battlebranch",
	52:  "Woestave",
	53:  "The Grim Reaper",
	54:  "Bane Ash",
	55:  "Serpent Lord",
	56:  "Spire of Lazarus",
	57:  "The Salamander",
	58:  "The Iron Jang Bong",
	59:  "Pluckeye",
	60:  "Witherstring",
	61:  "Raven Claw",
	62:  "Rogue's Bow",
	63:  "Stormstrike",
	64:  "Wizendraw",
	65:  "Hellclap",
	66:  "Blastbark",
	67:  "Leadcrow",
	68:  "Ichorsting",
	69:  "Hellcast",
	70:  "Doomslinger",
	71:  "Biggin's Bonnet",
	72:  "Tarnhelm",
	73:  "Coif of Glory",
	74:  "Duskdeep",
	75:  "Wormskull",
	76:  "Howltusk",
	77:  "Undead Crown",
	78:  "The Face of Horror",
	79:  "Greyform",
	80:  "Blinkbat's Form",
	81:  "The Centurion",
	82:  "Twitchthroe",
	83:  "Darkglow",
	84:  "Hawkmail",
	85:  "Sparking Mail",
	86:  "Venom Ward",
	87:  "Iceblink",
	88:  "Boneflesh",
	89:  "Rockfleece",
	90:  "Rattlecage",
	91:  "Goldskin",
	92:  "Victors Silk",
	93:  "Heavenly Garb",
	94:  "Pelta Lunata",
	95:  "Umbral Disk",
	96:  "Stormguild",
	97:  "Wall of the Eyeless",
	98:  "Swordback Hold",
	99:  "Steelclash",
	100: "Bverrit Keep",
	101: "The Ward",
	102: "The Hand of Broc",
	103: "Bloodfist",
	104: "Chance Guards",
	105: "Magefist",
	106: "Frostburn",
	107: "Hotspur",
	108: "Gorefoot",
	109: "Treads of Cthon",
	110: "Goblin Toe",
	111: "Tearhaunch",
	112: "Lenymo",
	113: "Snakecord",
	114: "Nightsmoke",
	115: "Goldwrap",
	116: "Bladebuckle",
	117: "Nokozan Relic",
	118: "The Eye of Etlich",
	119: "The Mahim-Oak Curio",
	120: "Nagelring",
	121: "Manald Heal",
	122: "The Stone of Jordan",
	123: "Amulet of the Viper",
	124: "Staff of Kings",
	125: "Horadric Staff",
	126: "Hell Forge Hammer",
	127: "Khalim's Flail",
	128: "Super Khalim's Flail",
	129: "Coldkill",
	130: "Butcher's Pupil",
	131: "Islestrike",
	132: "Pompe's Wrath",
	133: "Guardian Naga",
	134: "Warlord's Trust",
	135: "Spellsteel",
	136: "Stormrider",
	137: "Boneslayer Blade",
	138: "The Minataur",
	139: "Suicide Branch",
	140: "Carin Shard",
	141: "Arm of King Leoric",
	142: "Blackhand Key",
	143: "Dark Clan Crusher",
	144: "Zakarum's Hand",
	145: "The Fetid Sprinkler",
	146: "Hand of Blessed Light",
	147: "Fleshrender",
	148: "Sureshrill Frost",
	149: "Moonfall",
	150: "Baezil's Vortex",
	151: "Earthshaker",
	152: "Bloodtree Stump",
	153: "The Gavel of Pain",
	154: "Bloodletter",
	155: "Coldsteel Eye",
	156: "Hexfire",
	157: "Blade of Ali Baba",
	158: "Ginther's Rift",
	159: "Headstriker",
	160: "Plague Bearer",
	161: "The Atlantian",
	162: "Crainte Vomir",
	163: "Bing Sz Wang",
	164: "The Vile Husk",
	165: "Cloudcrack",
	166: "Todesfaelle Flamme",
	167: "Swordguard",
	168: "Spineripper",
	169: "Heart Carver",
	170: "Blackbog's Sharp",
	171: "Stormspike",
	172: "The Impaler",
	173: "Kelpie Snare",
	174: "Soulfeast Tine",
	175: "Hone Sundan",
	176: "Spire of Honor",
	177: "The Meat Scraper",
	178: "Blackleach Blade",
	179: "Athena's Wrath",
	180: "Pierre Tombale Couant",
	181: "Husoldal Evo",
	182: "Grim's Burning Dead",
	183: "Razorswitch",
	184: "Ribcracker",
	185: "Chromatic Ire",
	186: "Warpspear",
	187: "Skullcollector",
	188: "Skystrike",
	189: "Riphook",
	190: "Kuko Shakaku",
	191: "Endlesshail",
	192: "Whichwild String",
	193: "Cliffkiller",
	194: "Magewrath",
	195: "Godstrike Arch",
	196: "Langer Briser",
	197: "Pus Spiter",
	198: "Buriza-Do Kyanon",
	199: "Demon Machine",
	200: "Armor (Unknown)",
	201: "Peasent Crown",
	202: "Rockstopper",
	203: "Stealskull",
	204: "Darksight Helm",
	205: "Valkyrie Wing",
	206: "Crown of Thieves",
	207: "Blckhorn's Face",
	208: "Vampire Gaze",
	209: "The Spirit Shroud",
	210: "Skin of the Vipermagi",
	211: "Skin of the Flayed One",
	212: "Ironpelt",
	213: "Spiritforge",
	214: "Crow Caw",
	215: "Shaftstop",
	216: "Duriel's Shell",
	217: "Skullder's Ire",
	218: "Guardian Angel",
	219: "Toothrow",
	220: "Atma's Wail",
	221: "Black Hades",
	222: "Corpsemourn",
	223: "Que-Hegan's Wisdom",
	224: "Visceratuant",
	225: "Mosers Blessed Circle",
	226: "Stormchaser",
	227: "Tiamat's Rebuke",
	228: "Gerke's Sanctuary",
	229: "Radimant's Sphere",
	230: "Lidless Wall",
	231: "Lance Guard",
	232: "Venom Grip",
	233: "Gravepalm",
	234: "Ghoulhide",
	235: "Lavagout",
	236: "Hellmouth",
	237: "Infernostride",
	238: "Waterwalk",
	239: "Silkweave",
	240: "Wartraveler",
	241: "Gorerider",
	242: "String of Ears",
	243: "Razortail",
	244: "Gloomstrap",
	245: "Snowclash",
	246: "Thundergod's Vigor",
	247: "Elite unique",
	248: "Harlequin Crest",
	249: "Veil of Steel",
	250: "The Gladiator's Bane",
	251: "Arkaine's Valor",
	252: "Blackoak Shield",
	253: "Stormshield",
	254: "Hellslayer",
	255: "Messerschmidt's Reaver",
	256: "Baranar's Star",
	257: "Schaefer's Hammer",
	258: "The Cranium Basher",
	259: "Lightsabre",
	260: "Doombringer",
	261: "The Grandfather",
	262: "Wizardspike",
	263: "Constricting Ring",
	264: "Stormspire",
	265: "Eaglehorn",
	266: "Windforce",
	267: "Ring",
	268: "Bul Katho's Wedding Band",
	269: "The Cat's Eye",
	270: "The Rising Sun",
	271: "Crescent Moon",
	272: "Mara's Kaleidoscope",
	273: "Atma's Scarab",
	274: "Dwarf Star",
	275: "Raven Frost",
	276: "Highlord's Wrath",
	277: "Saracen's Chance",
	278: "Class specific",
	279: "Arreat's Face",
	280: "Homunculus",
	281: "Titan's Revenge",
	282: "Lycander's Aim",
	283: "Lycander's Flank",
	284: "The Oculus",
	285: "Herald of Zakarum",
	286: "Bartuc's Cut-Throat",
	287: "Jalal's Mane",
	288: "The Scalper",
	289: "Bloodmoon",
	290: "Djinnslayer",
	291: "Deathbit",
	292: "Warshrike",
	293: "Gutsiphon",
	294: "Razoredge",
	295: "Gore Ripper",
	296: "Demon Limb",
	297: "Steel Shade",
	298: "Tomb Reaver",
	299: "Death's Web",
	300: "Nature's Peace",
	301: "Azurewrath",
	302: "Seraph's Hymn",
	303: "Zakarum's Salvation",
	304: "Fleshripper",
	305: "Odium",
	306: "Horizon's Tornado",
	307: "Stone Crusher",
	308: "Jade Talon",
	309: "Shadow Dancer",
	310: "Cerebus' Bite",
	311: "Tyrael's Might",
	312: "Soul Drainer",
	313: "Rune Master",
	314: "Death Cleaver",
	315: "Executioner's Justice",
	316: "Stoneraven",
	317: "Leviathan",
	318: "Larzuk's Champion",
	319: "Wisp Projector",
	320: "Gargoyle's Bite",
	321: "Lacerator",
	322: "Mang Song's Lesson",
	323: "Viperfork",
	324: "Ethereal Edge",
	325: "Demonhorn's Edge",
	326: "The Reaper's Toll",
	327: "Spiritkeeper",
	328: "Hellrack",
	329: "Alma Negra",
	330: "Darkforge Spawn",
	331: "Widowmaker",
	332: "Bloodraven's Charge",
	333: "Ghostflame",
	334: "Shadowkiller",
	335: "Gimmershred",
	336: "Griffon's Eye",
	337: "Windhammer",
	338: "Thunderstroke",
	339: "Giant Maimer",
	340: "Demon's Arch",
	341: "Boneflame",
	342: "Steelpillar",
	343: "Nightwing's Veil",
	344: "Crown of Ages",
	345: "Andariel's Visage",
	346: "Darkfear",
	347: "Dragonscale",
	348: "Steel Carapice",
	349: "Medusa's Gaze",
	350: "Ravenlore",
	351: "Boneshade",
	352: "Nethercrow",
	353: "Flamebellow",
	354: "Fathom",
	355: "Wolfhowl",
	356: "Spirit Ward",
	357: "Kira's Guardian",
	358: "Ormus Robes",
	359: "Gheed's Fortune",
	360: "Stormlash",
	361: "Halaberd's Reign",
	362: "Warriv's Warder",
	363: "Spike Thorn",
	364: "Dracul's Grasp",
	365: "Frostwind",
	366: "Templar's Might",
	367: "Eschuta's Temper",
	368: "Firelizard's Talons",
	369: "Sandstorm Trek",
	370: "Marrowwalk",
	371: "Heaven's Light",
	372: "Merman's Speed",
	373: "Arachnid Mesh",
	374: "Nosferatu's Coil",
	375: "Metalgrid",
	376: "Verdugo's Hearty Cord",
	377: "Sigurd's Staunch",
	378: "Carrion Wind",
	379: "Giantskull",
	380: "Ironward",
	381: "Annihilus",
	382: "Arioc's Needle",
	383: "Cranebeak",
	384: "Nord's Tenderizer",
	385: "Earthshifter",
	386: "Wraithflight",
	387: "Bonehew",
	388: "Ondal's Wisdom",
	389: "The Reedeemer",
	390: "Headhunter's Glory",
	391: "Steelrend",
	392: "Rainbow Facet",
	393: "Rainbow Facet",
	394: "Rainbow Facet",
	395: "Rainbow Facet",
	396: "Rainbow Facet",
	397: "Rainbow Facet",
	398: "Rainbow Facet",
	399: "Rainbow Facet",
	400: "Hellfire Torch",
}

var MagicalPrefixes = map[uint16]string{
	2:   "Sturdy",
	3:   "Strong",
	4:   "Glorious",
	5:   "Blessed",
	6:   "Saintly",
	7:   "Holy",
	8:   "Devious",
	9:   "Fortified",
	13:  "Jagged",
	14:  "Deadly",
	15:  "Vicious",
	16:  "Brutal",
	17:  "Massive",
	18:  "Savage",
	19:  "Merciless",
	20:  "Vulpine",
	25:  "Tireless",
	26:  "Rugged",
	27:  "Bronze",
	28:  "Iron",
	29:  "Steel",
	30:  "Silver",
	32:  "Gold",
	33:  "Platinum",
	34:  "Meteoric",
	35:  "Sharp",
	36:  "Fine",
	37:  "Warrior's",
	38:  "Soldier's",
	39:  "Knight's",
	40:  "Lord's",
	41:  "King's",
	42:  "Howling",
	43:  "Fortuitous",
	49:  "Glimmering",
	50:  "Glowing",
	53:  "Lizard's",
	55:  "Snake's",
	56:  "Serpent's",
	57:  "Serpent's",
	58:  "Drake's",
	59:  "Dragon's",
	60:  "Dragon's",
	61:  "Wyrm's",
	64:  "Prismatic",
	65:  "Prismatic",
	66:  "Azure",
	67:  "Lapis",
	68:  "Lapis",
	69:  "Cobalt",
	70:  "Cobalt",
	72:  "Sapphire",
	75:  "Crimson",
	76:  "Burgundy",
	77:  "Burgundy",
	78:  "Garnet",
	79:  "Garnet",
	81:  "Ruby",
	84:  "Ocher",
	85:  "Tangerine",
	86:  "Tangerine",
	87:  "Coral",
	88:  "Coral",
	90:  "Amber",
	93:  "Beryl",
	94:  "Jade",
	95:  "Jade",
	96:  "Viridian",
	97:  "Viridian",
	99:  "Emerald",
	101: "Fletcher's",
	102: "Archer's",
	103: "Archer's",
	104: "Monk's",
	105: "Priest's",
	106: "Priest's",
	107: "Summoner's",
	108: "Necromancer's",
	109: "Necromancer's",
	110: "Angel's",
	111: "Arch-Angel's",
	112: "Arch-Angel's",
	113: "Slayer's",
	114: "Berserker's",
	115: "Berserker's",
	118: "Triumphant",
	119: "Stout",
	120: "Stout",
	121: "Stout",
	122: "Burly",
	123: "Burly",
	124: "Burly",
	125: "Stalwart",
	126: "Stalwart",
	127: "Stalwart",
	128: "Stout",
	129: "Stout",
	130: "Stout",
	131: "Burly",
	132: "Burly",
	133: "Stalwart",
	134: "Stalwart",
	135: "Stout",
	136: "Stout",
	137: "Burly",
	138: "Stalwart",
	139: "Blanched",
	140: "Eburin",
	141: "Bone",
	142: "Ivory",
	143: "Sturdy",
	144: "Sturdy",
	145: "Strong",
	146: "Glorious",
	147: "Blessed",
	148: "Saintly",
	149: "Holy",
	150: "Godly",
	151: "Devious",
	152: "Blank",
	153: "Null",
	154: "Antimagic",
	155: "Red",
	156: "Red",
	157: "Sanguinary",
	158: "Sanguinary",
	159: "Bloody",
	160: "Red",
	161: "Sanguinary",
	162: "Bloody",
	163: "Red",
	164: "Sanguinary",
	165: "Bloody",
	166: "Scarlet",
	167: "Crimson",
	168: "Jagged",
	169: "Jagged",
	170: "Jagged",
	171: "Forked",
	172: "Forked",
	173: "Serrated",
	174: "Serrated",
	175: "Jagged",
	176: "Jagged",
	177: "Forked",
	178: "Forked",
	179: "Serrated",
	180: "Jagged",
	181: "Forked",
	182: "Serrated",
	183: "Carbuncle",
	184: "Carmine",
	185: "Vermillion",
	186: "Jagged",
	187: "Deadly",
	188: "Vicious",
	189: "Brutal",
	190: "Massive",
	191: "Savage",
	192: "Merciless",
	193: "Ferocious",
	194: "Cruel",
	195: "Cinnabar",
	196: "Rusty",
	197: "Realgar",
	198: "Ruby",
	199: "Vulpine",
	200: "Dun",
	201: "Tireless",
	202: "Tireless",
	203: "Brown",
	204: "Rugged",
	205: "Rugged",
	206: "Rugged",
	207: "Rugged",
	208: "Rugged",
	209: "Rugged",
	210: "Rugged",
	211: "Rugged",
	212: "Rugged",
	213: "Rugged",
	214: "Rugged",
	215: "Vigorous",
	216: "Chestnut",
	217: "Maroon",
	218: "Bronze",
	219: "Bronze",
	220: "Bronze",
	221: "Iron",
	222: "Iron",
	223: "Iron",
	224: "Steel",
	225: "Steel",
	226: "Steel",
	227: "Bronze",
	228: "Bronze",
	229: "Bronze",
	230: "Iron",
	231: "Iron",
	232: "Steel",
	233: "Steel",
	234: "Bronze",
	235: "Bronze",
	236: "Iron",
	237: "Steel",
	238: "Bronze",
	239: "Iron",
	240: "Steel",
	241: "Silver",
	242: "Gold",
	243: "Platinum",
	244: "Meteoric",
	245: "Strange",
	246: "Weird",
	247: "Nickel",
	248: "Tin",
	249: "Silver",
	250: "Argent",
	251: "Fine",
	252: "Fine",
	253: "Sharp",
	254: "Fine",
	255: "Sharp",
	256: "Fine",
	257: "Sharp",
	258: "Fine",
	259: "Warrior's",
	260: "Soldier's",
	261: "Knight's",
	262: "Lord's",
	263: "King's",
	264: "Master's",
	265: "Grandmaster's",
	266: "Glimmering",
	267: "Glowing",
	268: "Bright",
	269: "Screaming",
	270: "Howling",
	271: "Wailing",
	272: "Screaming",
	273: "Howling",
	274: "Wailing",
	275: "Lucky",
	276: "Lucky",
	277: "Lucky",
	278: "Lucky",
	279: "Lucky",
	280: "Lucky",
	281: "Felicitous",
	282: "Fortuitous",
	283: "Emerald",
	284: "Lizard's",
	285: "Lizard's",
	286: "Lizard's",
	287: "Snake's",
	288: "Snake's",
	289: "Snake's",
	290: "Serpent's",
	291: "Serpent's",
	292: "Serpent's",
	293: "Lizard's",
	294: "Lizard's",
	295: "Lizard's",
	296: "Snake's",
	297: "Snake's",
	298: "Serpent's",
	299: "Serpent's",
	300: "Lizard's",
	301: "Lizard's",
	302: "Snake's",
	303: "Serpent's",
	304: "Lizard's",
	305: "Snake's",
	306: "Serpent's",
	307: "Serpent's",
	308: "Drake's",
	309: "Dragon's",
	310: "Dragon's",
	311: "Wyrm's",
	312: "Great Wyrm's",
	313: "Bahamut's",
	314: "Zircon",
	315: "Jacinth",
	316: "Turquoise",
	317: "Shimmering",
	318: "Shimmering",
	319: "Shimmering",
	320: "Shimmering",
	321: "Shimmering",
	322: "Shimmering",
	323: "Shimmering",
	324: "Rainbow",
	325: "Scintillating",
	326: "Prismatic",
	327: "Chromatic",
	328: "Shimmering",
	329: "Rainbow",
	330: "Scintillating",
	331: "Prismatic",
	332: "Chromatic",
	333: "Shimmering",
	334: "Rainbow",
	335: "Scintillating",
	336: "Shimmering",
	337: "Scintillating",
	338: "Azure",
	339: "Lapis",
	340: "Cobalt",
	341: "Sapphire",
	342: "Azure",
	343: "Lapis",
	344: "Cobalt",
	345: "Sapphire",
	346: "Azure",
	347: "Lapis",
	348: "Cobalt",
	349: "Sapphire",
	350: "Azure",
	351: "Lapis",
	352: "Lapis",
	353: "Cobalt",
	354: "Cobalt",
	355: "Sapphire",
	356: "Lapis Lazuli",
	357: "Sapphire",
	358: "Crimson",
	359: "Russet",
	360: "Garnet",
	361: "Ruby",
	362: "Crimson",
	363: "Russet",
	364: "Garnet",
	365: "Ruby",
	366: "Crimson",
	367: "Russet",
	368: "Garnet",
	369: "Ruby",
	370: "Russet",
	371: "Russet",
	372: "Garnet",
	373: "Garnet",
	374: "Ruby",
	375: "Garnet",
	376: "Ruby",
	377: "Tangerine",
	378: "Ocher",
	379: "Coral",
	380: "Amber",
	381: "Tangerine",
	382: "Ocher",
	383: "Coral",
	384: "Amber",
	385: "Tangerine",
	386: "Ocher",
	387: "Coral",
	388: "Amber",
	389: "Tangerine",
	390: "Ocher",
	391: "Ocher",
	392: "Coral",
	393: "Coral",
	394: "Amber",
	395: "Camphor",
	396: " Ambergris",
	397: "Beryl",
	398: "Viridian",
	399: "Jade",
	400: "Emerald",
	401: "Beryl",
	402: "Viridian",
	403: "Jade",
	404: "Emerald",
	405: "Beryl",
	406: "Viridian",
	407: "Jade",
	408: "Emerald",
	409: "Beryl",
	410: "Viridian",
	411: "Viridian",
	412: "Jade",
	413: "Jade",
	414: "Emerald",
	415: "Beryl",
	416: "Jade",
	417: "Triumphant",
	418: "Victorious",
	419: "Aureolin",
	420: "Mechanist's",
	421: "Artificer's",
	422: "Jeweler's",
	423: "Assamic",
	424: "Arcadian",
	425: "Unearthly",
	426: "Astral",
	427: "Elysian",
	428: "Celestial",
	429: "Diamond",
	430: "Fletcher's",
	431: "Acrobat's",
	432: "Harpoonist's",
	433: "Fletcher's",
	434: "Bowyer's",
	435: "Archer's",
	436: "Acrobat's",
	437: "Gymnast's",
	438: "Athlete's",
	439: "Harpoonist's",
	440: "Spearmaiden's",
	441: "Lancer's",
	442: "Burning",
	443: "Sparking",
	444: "Chilling",
	445: "Burning",
	446: "Blazing",
	447: "Volcanic",
	448: "Sparking",
	449: "Charged",
	450: "Powered",
	451: "Chilling",
	452: "Freezing",
	453: "Glacial",
	454: "Hexing",
	455: "Fungal",
	456: "Graverobber's",
	457: "Hexing",
	458: "Blighting",
	459: "Accursed",
	460: "Fungal",
	461: "Noxious",
	462: "Venomous",
	463: "Graverobber's",
	464: "Vodoun",
	465: "Golemlord's",
	466: "Lion Branded",
	467: "Captain's",
	468: "Preserver's",
	469: "Lion Branded",
	470: "Hawk Branded",
	471: "Rose Branded",
	472: "Captain's",
	473: "Commander's",
	474: "Marshal's",
	475: "Preserver's",
	476: "Warder's",
	477: "Guardian's",
	478: "Expert's",
	479: "Fanatic",
	480: "Sounding",
	481: "Expert's",
	482: "Veteran's",
	483: "Master's",
	484: "Fanatic",
	485: "Raging",
	486: "Furious",
	487: "Sounding",
	488: "Resonant",
	489: "Echoing",
	490: "Trainer's",
	491: "Spiritual",
	492: "Nature's",
	493: "Trainer's",
	494: "Caretaker's",
	495: "Keeper's",
	496: "Spiritual",
	497: "Feral",
	498: "Communal",
	499: "Nature's",
	500: "Terra's",
	501: "Gaea's",
	502: "Entrapping",
	503: "Mentalist's",
	504: "Shogukusha's",
	505: "Entrapping",
	506: "Trickster's",
	507: "Cunning",
	508: "Mentalist's",
	509: "Psychic",
	510: "Shadow",
	511: "Shogukusha's",
	512: "Sensei's",
	513: "Kenshi's",
	514: "Miocene",
	515: "Miocene",
	516: "Oligocene",
	517: "Oligocene",
	518: "Eocene",
	519: "Eocene",
	520: "Paleocene",
	521: "Paleocene",
	522: "Knave's",
	523: "Jack's",
	524: "Jester's",
	525: "Joker's",
	526: "Trump",
	527: "Loud",
	528: "Calling",
	529: "Yelling",
	530: "Shouting",
	531: "Screaming",
	532: "Paradox",
	533: "Paradox",
	534: "Robineye",
	535: "Sparroweye",
	536: "Falconeye",
	537: "Hawkeye",
	538: "Eagleeye",
	539: "Visionary",
	540: "Mnemonic",
	541: "Snowflake",
	542: "Shivering",
	543: "Boreal",
	544: "Hibernal",
	545: "Ember",
	546: "Smoldering",
	547: "Smoking",
	548: "Flaming",
	549: "Scorching",
	550: "Static",
	551: "Glowing",
	552: "Buzzing",
	553: "Arcing",
	554: "Shocking",
	555: "Septic",
	556: "Envenomed",
	557: "Corosive",
	558: "Toxic",
	559: "Pestilent",
	560: "Maiden's",
	561: "Valkyrie's",
	562: "Maiden's",
	563: "Valkyrie's",
	564: "Monk's",
	565: "Priest's",
	566: "Monk's",
	567: "Priest's",
	568: "Monk's",
	569: "Priest's",
	570: "Summoner's",
	571: "Necromancer's",
	572: "Summoner's",
	573: "Necromancer's",
	574: "Angel's",
	575: "Arch-Angel's",
	576: "Angel's",
	577: "Arch-Angel's",
	578: "Slayer's",
	579: "Berserker's",
	580: "Slayer's",
	581: "Berserker's",
	582: "Slayer's",
	583: "Berserker's",
	584: "Shaman's",
	585: "Hierophant's",
	586: "Shaman's",
	587: "Hierophant's",
	588: "Magekiller's",
	589: "Witch-hunter's",
	590: "Magekiller's",
	591: "Witch-hunter's",
	592: "Compact",
	593: "Thin",
	594: "Dense",
	595: "Consecrated",
	596: "Pure",
	597: "Sacred",
	598: "Hallowed",
	599: "Divine",
	600: "Pearl",
	601: "Crimson",
	602: "Red",
	603: "Sanguinary",
	604: "Bloody",
	605: "Red",
	606: "Sanguinary",
	607: "Red",
	608: "Jagged",
	609: "Forked",
	610: "Serrated",
	611: "Jagged",
	612: "Forked",
	613: "Jagged",
	614: "Snowflake",
	615: "Shivering",
	616: "Boreal",
	617: "Hibernal",
	618: "Snowflake",
	619: "Shivering",
	620: "Boreal",
	621: "Hibernal",
	622: "Snowflake",
	623: "Shivering",
	624: "Boreal",
	625: "Hibernal",
	626: "Ember",
	627: "Smoldering",
	628: "Smoking",
	629: "Flaming",
	630: "Ember",
	631: "Smoldering",
	632: "Smoking",
	633: "Flaming",
	634: "Ember",
	635: "Smoldering",
	636: "Smoking",
	637: "Flaming",
	638: "Static",
	639: "Glowing",
	640: "Arcing",
	641: "Shocking",
	642: "Static",
	643: "Glowing",
	644: "Arcing",
	645: "Shocking",
	646: "Static",
	647: "Glowing",
	648: "Arcing",
	649: "Shocking",
	650: "Septic",
	651: "Envenomed",
	652: "Toxic",
	653: "Pestilent",
	654: "Septic",
	655: "Envenomed",
	656: "Toxic",
	657: "Pestilent",
	658: "Septic",
	659: "Envenomed",
	660: "Toxic",
	661: "Pestilent",
	662: "Tireless",
	663: "Lizard's",
	664: "Azure",
	665: "Crimson",
	666: "Tangerine",
	667: "Beryl",
	668: "Godly",
	669: "Cruel",
}

var MagicalSuffixes = map[uint16]string{
	1:   "Health",
	2:   "Protection",
	3:   "Absorption",
	4:   "Life",
	5:   "(nothing?)",
	6:   "Warding",
	7:   "the Sentinel",
	8:   "Guarding",
	9:   "Negation",
	10:  "(nothing?)",
	11:  "Piercing",
	12:  "Bashing",
	13:  "Puncturing",
	14:  "Thorns",
	15:  "Spikes",
	16:  "Fleadiness",
	17:  "Alacrity",
	18:  "Swiitness ",
	19:  "Quickness",
	20:  "Blocking",
	21:  "Deilecting",
	22:  "the Apprentice",
	23:  "the Magus",
	24:  "Frost",
	25:  "the Glacier",
	26:  "Frost",
	27:  "Warmth",
	28:  "Flame",
	29:  "Fire",
	30:  "Burning",
	31:  "Flame",
	32:  "Shook",
	33:  "Lightning",
	34:  "Thunder",
	35:  "Shock",
	36:  "Craftsmanship",
	37:  "Quality",
	38:  "Maiming",
	39:  "Slaying",
	40:  "Gore",
	41:  "Carnage",
	42:  "Slaughter",
	43:  "Maiming",
	44:  "Worth",
	45:  "Measure",
	46:  "Excellence",
	47:  "Petlctmance",
	48:  "Measure",
	49:  "Blight",
	50:  "Venom",
	51:  "Pestilence",
	52:  "Blight",
	53:  "Dextetity",
	54:  "Dextetity",
	55:  "Skill",
	56:  "Skill",
	57:  "Accuracy",
	58:  "Precision",
	59:  "Precision",
	60:  "Petlection",
	61:  "Balance",
	62:  "Stability",
	63:  "(nothing?)",
	64:  "Regenetation",
	65:  "Regenetation",
	66:  "Regenetation",
	67:  "Regrowth",
	68:  "Regrowth",
	69:  "Vileness",
	70:  "(nothing?)",
	71:  "Greed",
	72:  "Wealth",
	73:  "Chance",
	74:  "Fortune",
	75:  "Energy",
	76:  "Energy",
	77:  "the Mind",
	78:  "Brilliance",
	79:  "Sorcery",
	80:  "Wizardry",
	81:  "the Beat",
	82:  "Light",
	83:  "Radiance",
	84:  "the Sun",
	85:  "Life",
	86:  "the Jackal",
	87:  "the Fox",
	88:  "the Wolf",
	89:  "the Wolf",
	90:  "the Tiget",
	91:  "the Mammoth",
	92:  "the Mammoth",
	93:  "the Colosuss",
	94:  "the Leech",
	95:  "the Locust",
	96:  "the Bat",
	97:  "the Vampire",
	98:  "Defiance",
	99:  "Amelioration",
	100: "Remedy",
	101: "(nothing?)",
	102: "Simplicity",
	103: "Ease",
	104: "(nothing?)",
	105: "Strength",
	106: "Might",
	107: "the Ox",
	108: "the Ox",
	109: "the Giant",
	110: "the Giant",
	111: "the Titan",
	112: "Pacing",
	113: "Haste",
	114: "Speed",
	115: "Health",
	116: "Protection",
	117: "Absorption",
	118: "Life",
	119: "Life Everlasting",
	120: "Protection",
	121: "Absorption",
	122: "Life",
	123: "Anima",
	124: "Warding",
	125: "the Sentinel",
	126: "Guarding",
	127: "Negation",
	128: "the Sentinel",
	129: "Guarding",
	130: "Negation",
	131: "Coolness",
	132: "Incombustibility",
	133: "Amianthus",
	134: "Fire Quenching",
	135: "Coolness",
	136: "Incombustibility",
	137: "Amianthus",
	138: "Fire Quenching",
	139: "Faith",
	140: "Resistance",
	141: "Insulation",
	142: "Grounding",
	143: "the Dynamo",
	144: "Resistance",
	145: "Insulation",
	146: "Grounding",
	147: "the Dynamo",
	148: "Stoicism",
	149: "Warming",
	150: "Thawing",
	151: "the Dunes",
	152: "the Sirocco",
	153: "Warming",
	154: "Thawing",
	155: "the Dunes",
	156: "the Sirocco",
	157: "Desire",
	158: "Piercing",
	159: "Bashing",
	160: "Puncturing",
	161: "Thorns",
	162: "Spikes",
	163: "Razors",
	164: "Swords",
	165: "Malice",
	166: "Readiness",
	167: "Alacrity",
	168: "Swiftness",
	169: "Quickness",
	170: "Alacrity",
	171: "Fewer",
	172: "Blocking",
	173: "Deflecting",
	174: "the Apprentice",
	175: "the Magus",
	176: "Frost",
	177: "the Icicle",
	178: "the Glacier",
	179: "Winter",
	180: "Frost",
	181: "Frigidity",
	182: "Warmth",
	183: "Flame",
	184: "Fire",
	185: "Burning",
	186: "Incineration",
	187: "Flame",
	188: "Passion",
	189: "Shock",
	190: "Lightning",
	191: "Thunder",
	192: "Storms",
	193: "Shock",
	194: "Ennui",
	195: "Craftsmanship",
	196: "Quality",
	197: "Maiming",
	198: "Slaying",
	199: "Gore",
	200: "Damage",
	201: "Slaughter",
	202: "Butchery",
	203: "Evisceration",
	204: "Maiming",
	205: "Craftsmanship",
	206: "Craftsmanship",
	207: "Craftsmanship",
	208: "Quality",
	209: "Quality",
	210: "Maiming",
	211: "Maiming",
	212: "Craftsmanship",
	213: "Craftsmanship",
	214: "Quality",
	215: "Quality",
	216: "Maiming",
	217: "Craftsmanship",
	218: "Quality",
	219: "Maiming",
	220: "Ire",
	221: "Wrath",
	222: "Damage",
	223: "Worth",
	224: "Measure",
	225: "Excellence",
	226: "Performance",
	227: "Transcendence",
	228: "Worth",
	229: "Measure",
	230: "Excellence",
	231: "Performance",
	232: "Joyfulness",
	233: "Bliss",
	234: "Blight",
	235: "Venom",
	236: "Pestilence",
	237: "Anthrax",
	238: "Blight",
	239: "Envy",
	240: "Dexterity",
	241: "Skill",
	242: "Accuracy",
	243: "Precision",
	244: "Perfection",
	245: "Nirvana",
	246: "Dexterity",
	247: "Skill",
	248: "Accuracy",
	249: "Precision",
	250: "Perfection",
	251: "Dexterity",
	252: "Skill",
	253: "Accuracy",
	254: "Precision",
	255: "Dexterity",
	256: "Dexterity",
	257: "Dexterity",
	258: "Dexterity",
	259: "Dexterity",
	260: "Dexterity",
	261: "Daring",
	262: "Balance",
	263: "Equilibrium",
	264: "Stability",
	265: "Balance",
	266: "Balance",
	267: "Balance",
	268: "Truth",
	269: "Regeneration",
	270: "Regeneration",
	271: "Regeneration",
	272: "Regrowth",
	273: "Regrowth",
	274: "Revivification",
	275: "Honor",
	276: "Vileness",
	277: "Greed",
	278: "Wealth",
	279: "Greed",
	280: "Greed",
	281: "Greed",
	282: "Greed",
	283: "Greed",
	284: "Greed",
	285: "Avarice",
	286: "Chance",
	287: "Fortune",
	288: "Fortune",
	289: "Luck",
	290: "Fortune",
	291: "Good Luck",
	292: "Prosperity",
	293: "Energy",
	294: "the Mind",
	295: "Brilliance",
	296: "Sorcery",
	297: "Wizardry",
	298: "Enlightenment",
	299: "Energy",
	300: "the Mind",
	301: "Brilliance",
	302: "Sorcery",
	303: "Wizardry",
	304: "Energy",
	305: "the Mind",
	306: "Brilliance",
	307: "Sorcery",
	308: "Knowledge",
	309: "the Bear",
	310: "Light",
	311: "Radiance",
	312: "the Sun",
	313: "the Jackal",
	314: "the Fox",
	315: "the Wolf",
	316: "the Tiger",
	317: "the Mammoth",
	318: "the Colosuss",
	319: "the Squid",
	320: "the Whale",
	321: "the Jackal",
	322: "the Fox",
	323: "the Wolf",
	324: "the Tiger",
	325: "the Mammoth",
	326: "the Colosuss",
	327: "the Jackal",
	328: "the Fox",
	329: "the Wolf",
	330: "the Tiger",
	331: "the Mammoth",
	332: "Life",
	333: "Life",
	334: "Life",
	335: "Substinence",
	336: "Substinence",
	337: "Substinence",
	338: "Vita",
	339: "Vita",
	340: "Vita",
	341: "Life",
	342: "Life",
	343: "Substinence",
	344: "Substinence",
	345: "Vita",
	346: "Vita",
	347: "Life",
	348: "Substinence",
	349: "Vita",
	350: "Spirit",
	351: "Hope",
	352: "the Leech",
	353: "the Locust",
	354: "the Lamprey",
	355: "the Leech",
	356: "the Locust",
	357: "the Lamprey",
	358: "the Leech",
	359: "the Bat",
	360: "the Wraith",
	361: "the Vampire",
	362: "the Bat",
	363: "the Wraith",
	364: "the Vampire",
	365: "the Bat",
	366: "Defiance",
	367: "Amelioration",
	368: "Remedy",
	369: "Simplicity",
	370: "Ease",
	371: "Freedom",
	372: "Strength",
	373: "Might",
	374: "the Ox",
	375: "the Giant",
	376: "the Titan",
	377: "Atlus",
	378: "Strength",
	379: "Might",
	380: "the Us",
	381: "the Giant",
	382: "the Titan",
	383: "Strength",
	384: "Might",
	385: "the Us",
	386: "the Giant",
	387: "Strength",
	388: "Strength",
	389: "Strength",
	390: "Strength",
	391: "Strength",
	392: "Strength",
	393: "Virility",
	394: "Pacing",
	395: "Haste",
	396: "Speed",
	397: "Traveling",
	398: "Acceleration",
	399: "Inertia",
	400: "Inertia",
	401: "Inertia",
	402: "Self-Repair",
	403: "Fast Repair",
	404: "Ages",
	405: "Heplenishing",
	406: "Propagation",
	407: "the Kraken",
	408: "Memory",
	409: "the Elephant",
	410: "Power",
	411: "Grace",
	412: "Grace and Power",
	413: "the Yeti",
	414: "the Phoenix",
	415: "the Efreeti",
	416: "the Cobra",
	417: "the Elements",
	418: "Firebolts",
	419: "Firebolts",
	420: "Firebolts",
	421: "Charged Shield",
	422: "Charged Shield",
	423: "Charged Shield",
	424: "Icebolt",
	425: "Frozen Armor",
	426: "Static Field",
	427: "Telekinesis",
	428: "Frost Shield",
	429: "Ice Blast",
	430: "Blaze",
	431: "Fire Ball",
	432: "Nova",
	433: "Nova",
	434: "Nova Shield",
	435: "Nova Shield",
	436: "Nova Shield",
	437: "Lightning",
	438: "Lightning",
	439: "Shiver Armor",
	440: "Fire Wall",
	441: "Enchant",
	442: "Chain Lightning",
	443: "Chain Lightning",
	444: "Chain Lightning",
	445: "Teleport Shield",
	446: "Teleport Shield",
	447: "Teleport Shield",
	448: "Glacial Spike",
	449: "Meteor",
	450: "Thunder Storm",
	451: "Energy Shield",
	452: "Blizzard",
	453: "Chilling Armor",
	454: "Hydra Shield",
	455: "Frozen ler",
	456: "Dawn",
	457: "Sunlight",
	458: "Magic Arrows",
	459: "Magic Arrows",
	460: "Fire Arrows",
	461: "Fire Arrows",
	462: "lnner Sight",
	463: "Inner Sight",
	464: "Jabbing",
	465: "Jabbing",
	466: "Cold Arrows",
	467: "Cold Arrows",
	468: "Multiple Shot",
	469: "Multiple Shot",
	470: "Power Strike",
	471: "Power Strike",
	472: "Poison Jab",
	473: "Poison Jab",
	474: "Exploding Arrows",
	475: "Exploding Arrows",
	476: "Slow Missiles",
	477: "Slow Missiles",
	478: "lmpaling Strike",
	479: "lmpaling Strike",
	480: "Lightning Javelin",
	481: "Lightning Javelin",
	482: "Ice Arrows",
	483: "Ice Arrows",
	484: "Guided Arrows",
	485: "Guided Arrows",
	486: "Charged Strike",
	487: "Charged Strike",
	488: "Plague Jab",
	489: "Plague Jab",
	490: "lmmolating Arrows",
	491: "lmmolating Arrows",
	492: "Fending",
	493: "Fending",
	494: "Freezing Arrows",
	495: "Freezing Arrows",
	496: "Lightning Strike",
	497: "Lightning Strike",
	498: "Lightning Fury",
	499: "Lightning Fury",
	500: "Fire Bolts",
	501: "Fire Bolts",
	502: "Charged Bolts",
	503: "Charged Bolts",
	504: "Ice Bolts",
	505: "Ice Bolts",
	506: "Frozen Armor",
	507: "Frozen Armor",
	508: "Static Field",
	509: "Static Field",
	510: "Telekinesis",
	511: "Telekinesis",
	512: "Frost Novas",
	513: "Frost Novas",
	514: "Ice Blasts",
	515: "Ice Blasts",
	516: "Blazing",
	517: "Blazing",
	518: "Fire Balls",
	519: "Fire Balls",
	520: "Novas",
	521: "Novas",
	522: "Lightning",
	523: "Lightning",
	524: "Shiver Armor",
	525: "Shiver Armor",
	526: "Fire Walls",
	527: "Fire Walls",
	528: "Enchantment",
	529: "Enchantment",
	530: "Chain Lightning",
	531: "Chain Lightning",
	532: "Teleportation",
	533: "Teleportation",
	534: "Glacial Spikes",
	535: "Glacial Spikes",
	536: "Meteors",
	537: "Meteors",
	538: "Thunder Storm",
	539: "Thunder Storm",
	540: "Energy Shield",
	541: "Energy Shield",
	542: "Blizzards",
	543: "Blizzards",
	544: "Chilling Armor",
	545: "Chilling Armor",
	546: "Hydras",
	547: "Hydras",
	548: "Frozen Orbs",
	549: "Frozen Orbs",
	550: "Amplify Damage",
	551: "Amplify Damage",
	552: "Teeth",
	553: "Teeth",
	554: "Bone Armor",
	555: "Bone Armor",
	556: "Raise Skeletons",
	557: "Raise Skeletons",
	558: "Dim Vision",
	559: "Dim Vision",
	560: "Weaken",
	561: "Weaken",
	562: "Poison Dagger",
	563: "Poison Dagger",
	564: "Corpse Explosions",
	565: "Corpse Explosions",
	566: "Clay Golem Summoning",
	567: "Clay Golem Summoning",
	568: "Iron Maiden",
	569: "Iron Maiden",
	570: "Terror",
	571: "Terror",
	572: "Bone Walls",
	573: "Bone Walls",
	574: "Raise Skeletal Mages",
	575: "Raise Skeletal Mages",
	576: "Confusion",
	577: "Confusion",
	578: "Life Tap",
	579: "Life Tap",
	580: "Poison Explosion",
	581: "Poison Explosion",
	582: "Bone Spears",
	583: "Bone Spears",
	584: "Blood Golem Summoning",
	585: "Blood Golem Summoning",
	586: "Attraction",
	587: "Attraction",
	588: "Decrepification",
	589: "Decrepification",
	590: "Bone Imprisonment",
	591: "Bone Imprisonment",
	592: "Iron Golem Creation",
	593: "Iron Golem Creation",
	594: "Lower Resistance",
	595: "Lower Flesistance",
	596: "Poison Novas",
	597: "Poison Novas",
	598: "Bone Spirits",
	599: "Bone Spirits",
	600: "Fire Golem Summoning",
	601: "Fire Golem Summoning",
	602: "Revivification",
	603: "Revivification",
	604: "Sacrifice",
	605: "Sacrifice",
	606: "Holy Bolts",
	607: "Holy Bolts",
	608: "Zeal",
	609: "Zeal",
	610: "Vengeance",
	611: "Vengeance",
	612: "Blessed Hammers",
	613: "Blessed Hammers",
	614: "Conversion",
	615: "Conversion",
	616: "Fist of the Heavens",
	617: "Fist of the Heavens",
	618: "Bashing",
	619: "Bashing",
	620: "Howling",
	621: "Howling",
	622: "Potion Finding",
	623: "Potion Finding",
	624: "Taunting",
	625: "Taunting",
	626: "Shouting",
	627: "Shouting",
	628: "Stunning",
	629: "Stunning",
	630: "Item Finding",
	631: "Item Finding",
	632: "Concentration",
	633: "Concentration",
	634: "Battle Cry",
	635: "Battle Cry",
	636: "Battle Orders",
	637: "Battle Orders",
	638: "Grim Ward",
	639: "Grim Ward",
	640: "War Cry",
	641: "War Cry",
	642: "Battle Command",
	643: "Battle Command",
	644: "Firestorms",
	645: "Firestorms",
	646: "Molten Boulders",
	647: "Molten Boulders",
	648: "Eruption",
	649: "Eruption",
	650: "Cyclone Armor",
	651: "Cyclone Armor",
	652: "Twister",
	653: "Twister",
	654: "Volcano",
	655: "Volcano",
	656: "Tornado",
	657: "Tornado",
	658: "Armageddon",
	659: "Armageddon",
	660: "Hurricane",
	661: "Hurricane",
	662: "Damage Amplification",
	663: "the Icicle",
	664: "the Glacier",
	665: "Fire",
	666: "Burning",
	667: "Lightning",
	668: "Thunder",
	669: "Daring",
	670: "Daring",
	671: "Knowledge",
	672: "Knowledge",
	673: "Virility",
	674: "Virility",
	675: "Readiness",
	676: "Craftsmanship",
	677: "Quality",
	678: "Maiming",
	679: "Craftsmanship",
	680: "Quality",
	681: "Craftsmanship",
	682: "Blight",
	683: "Venom",
	684: "Pestilence",
	685: "Anthrax",
	686: "Blight",
	687: "Venom",
	688: "Pestilence",
	689: "Anthrax",
	690: "Blight",
	691: "Venom",
	692: "Pestilence",
	693: "Anthrax",
	694: "Frost",
	695: "the Icicle",
	696: "the Glacier",
	697: "Winter",
	698: "Frost",
	699: "the Icicle",
	700: "the Glacier",
	701: "Winter",
	702: "Frost",
	703: "the Icicle",
	704: "the Glacier",
	705: "Winter",
	706: "Flame",
	707: "Fire",
	708: "Burning",
	709: "Incineration",
	710: "Flame",
	711: "Fire",
	712: "Burning",
	713: "Incineration",
	714: "Flame",
	715: "Fire",
	716: "Burning",
	717: "Incineration",
	718: "Shock",
	719: "Lightning",
	720: "Thunder",
	721: "Storms",
	722: "Shock",
	723: "Lightning",
	724: "Thunder",
	725: "Storms",
	726: "Shock",
	727: "Lightning",
	728: "Thunder",
	729: "Storms",
	730: "Dexterity",
	731: "Dexterity",
	732: "Strength",
	733: "Strength",
	734: "Thorns",
	735: "Frost",
	736: "Flame",
	737: "Blight",
	738: "Shock",
	739: "Regeneration",
	740: "Energy",
	741: "Light",
	742: "the Leech",
	743: "the Locust",
	744: "the Lamprey",
	745: "the Bat",
	746: "the Wraith",
	747: "the Vampire",
}
