// Package itemdata contains data copied from https://github.com/nokka/d2s , Thanx!
package itemdata

// HasQuantity returns true if the item has quantity bits
func (c ItemCode) HasQuantity() bool {
	// All item types that contain the quantity bits will exist in here,
	// we'll use this when reading items to make sure we only read quantity bits
	// when they exist, or we'll ruin the rest of the bit offsets for the item.
	quantityMap := map[ItemCode]bool{
		// Misc
		TownPortalBook:      true,
		IdentifyBook:        true,
		SkeletonKey:         true,
		RancidGasPotion:     true,
		OilPotion:           true,
		ChokingGasPotion:    true,
		ExplodingPotion:     true,
		StranglingGasPotion: true,
		FulmatingPotion:     true,
		Arrows:              true,
		Bolts:               true,

		// Throwables
		ThrowingKnife: true,
		ThrowingAxe:   true,
		BalancedKnife: true,
		BalancedAxe:   true,
		BattleDart:    true,
		Francisca:     true,
		WarDart:       true,
		Hurlbat:       true,
		FlyingKnife:   true,
		FlyingAxe:     true,
		WingedKnife:   true,
		WingedAxe:     true,

		// Javelins
		Javelin:            true,
		Pilum:              true,
		ShortSpear:         true,
		Glaive:             true,
		ThrowingSpear:      true,
		WarJavelin:         true,
		GreatPilum:         true,
		Simbilan:           true,
		Spiculum:           true,
		Harpoon:            true,
		HyperionJavelin:    true,
		StygianPilum:       true,
		BalrogSpear:        true,
		GhostGlaive:        true,
		WingedHarpoon:      true,
		MaidenJavelin:      true,
		CeremonialJavelin:  true,
		MatriarchalJavelin: true,
	}

	_, ok := quantityMap[c]

	return ok
}

// IsTome returns true if the item is a tome
func (c ItemCode) IsTome() bool {
	// Items that are tomes contain 5 extra bits, so we need to keep track of what
	// items are tomes, and read the bits accordingly.
	tomeMap := map[ItemCode]bool{
		TownPortalBook: true,
		IdentifyBook:   true,
	}

	_, ok := tomeMap[c]

	return ok
}

// ShieldCodes shield item codes mapped to their in game, human-friendly, readable name.
// nolint:gochecknoglobals // data variable
var ShieldCodes = map[ItemCode]string{
	Aegis:            "Aegis",
	AerinShield:      "Aerin Shield",
	AkaranRondache:   "Akaran Rondache",
	AkaranTarge:      "Akaran Targe",
	KurastShield:     "Kurast Shield",
	AncientShield:    "Ancient Shield",
	BarbedShield:     "Barbed Shield",
	BladeBarrier:     "Blade Barrier",
	BloodlordSkull:   "Bloodlord Skull",
	BoneShield:       "Bone Shield",
	Buckler:          "Buckler",
	CantorTrophy:     "Cantor Trophy",
	CrownShield:      "Crown Shield",
	Defender:         "Defender",
	DemonHead:        "Demon Head",
	DragonShield:     "Dragon Shield",
	FetishTrophy:     "Fetish Trophy",
	GargoyleHead:     "Gargoyle Head",
	GothicShield:     "Gothic Shield",
	GrimShield:       "Grim Shield",
	GildedShield:     "Gilded Shield",
	HeirophantTrophy: "Heirophant Trophy",
	Heater:           "Heater",
	HellspawnSkull:   "Hellspawn Skull",
	HeraldicShield:   "Heraldic Shield",
	KiteShield:       "Kite Shield",
	LargeShield:      "Large Shield",
	Luna:             "Luna",
	MinionSkull:      "Minion Skull",
	Monarch:          "Monarch",
	MummifiedTrophy:  "Mummified Trophy",
	OverseerSkull:    "Overseer Skull",
	Pavise:           "Pavise",
	PreservedHead:    "Preserved Head",
	ProtectorShield:  "Protector Shield",
	Rondache:         "Rondache",
	RoundShield:      "Round Shield",
	RoyalShield:      "Royal Shield",
	SacredRondache:   "Sacred Rondache",
	SacredTarge:      "Sacred Targe",
	Scutum:           "Scutum",
	SextonTrophy:     "Sexton Trophy",
	SmallShield:      "Small Shield",
	SpikedShield:     "Spiked Shield",
	SuccubusSkull:    "Succubus Skull",
	Targe:            "Targe",
	TowerShield:      "Tower Shield",
	TrollNest:        "Troll Nest",
	UnravellerHead:   "Unraveller Head",
	VortexShield:     "Vortex Shield",
	Ward:             "Ward",
	ZakarumShield:    "Zakarum Shield",
	ZombieHead:       "Zombie Head",
}

// ArmorCodes - Armor item codes mapped to their in game, human-friendly, readable name.
// nolint:gochecknoglobals // data variable
var ArmorCodes = map[ItemCode]string{
	AlphaHelm:         "Alpha Helm",
	AncientArmor:      "Ancient Armor",
	Antlers:           "Antlers",
	ArchonPlate:       "Archon Plate",
	Armet:             "Armet",
	AssaultHelmet:     "Assault Helmet",
	AvengerGuard:      "Avenger Guard",
	BalrogSkin:        "Balrog Skin",
	Basinet:           "Basinet",
	BattleBelt:        "Battle Belt",
	BattleBoots:       "Battle Boots",
	BattleGauntlets:   "Battle Gauntlets",
	Belt:              "Belt",
	BloodSpirit:       "Blood Spirit",
	BoneHelm:          "Bone Helm",
	BoneVisage:        "Bone Visage",
	Boneweave:         "Boneweave",
	BoneweaveBoots:    "Boneweave Boots",
	Bracers:           "Bracers",
	BrambleMitts:      "Bramble Mitts",
	BreastPlate:       "Breast Plate",
	Cap:               "Cap",
	CarnageHelm:       "Carnage Helm",
	Casque:            "Casque",
	ChainBoots:        "Chain Boots",
	ChainMail:         "Chain Mail",
	ChaosArmor:        "Chaos Armor",
	Circlet:           "Circlet",
	ColossusGirdle:    "Colossus Girdle",
	ConquerorCrown:    "Conqueror Crown",
	Corona:            "Corona",
	Coronet:           "Coronet",
	Crown:             "Crown",
	CrusaderGauntlets: "Crusader Gauntlets",
	Cuirass:           "Cuirass",
	DeathMask:         "Death Mask",
	Demonhead:         "Demonhead",
	DemonhideArmor:    "Demonhide Armor",
	DemonhideBoots:    "Demonhide Boots",
	DemonhideGloves:   "Demonhide Gloves",
	DemonhideSash:     "Demonhide Sash",
	DestroyerHelm:     "Destroyer Helm",
	Diadem:            "Diadem",
	DiamondMail:       "Diamond Mail",
	DreamSpirit:       "Dream Spirit",
	DuskShroud:        "Dusk Shroud",
	EarthSpirit:       "Earth Spirit",
	EmbossedPlate:     "Embossed Plate",
	FalconMask:        "Falcon Mask",
	FangedHelm:        "Fanged Helm",
	FieldPlate:        "Field Plate",
	FullHelm:          "Full Helm",
	PlateMail:         "Plate Mail",
	FullPlateMail:     "Full Plate Mail",
	FuryVisor:         "Fury Visor",
	Gauntlets:         "Gauntlets",
	GhostArmor:        "Ghost Armor",
	GiantConch:        "Giant Conch",
	Girdle:            "Girdle",
	Gloves:            "Gloves",
	GothicPlate:       "Gothic Plate",
	GrandCrown:        "Grand Crown",
	GreatHauberk:      "Great Hauberk",
	GreatHelm:         "Great Helm",
	GriffonHeadress:   "Griffon Headress",
	GrimHelm:          "Grim Helm",
	GuardianCrown:     "Guardian Crown",
	HardLeatherArmor:  "Hard Leather Armor",
	HawkHelm:          "Hawk Helm",
	HeavyBelt:         "Heavy Belt",
	HeavyBoots:        "Heavy Boots",
	HeavyBracers:      "Heavy Bracers",
	HeavyGloves:       "Heavy Gloves",
	HellforgedPlate:   "Hellforged Plate",
	Helm:              "Helm",
	HornedHelm:        "Horned Helm",
	HuntersGuise:      "Hunter's Guise",
	Hydraskull:        "Hydraskull",
	Hyperion:          "Hyperion",
	JawboneCap:        "Jawbone Cap",
	JawboneVisor:      "Jawbone Visor",
	KrakenShell:       "Kraken Shell",
	LacqueredPlate:    "Lacquered Plate",
	LeatherArmor:      "Leather Armor",
	LeatherBoots:      "Leather Boots",
	LightBelt:         "Light Belt",
	LightGauntlets:    "Light Gauntlets",
	LightPlate:        "Light Plate",
	LightPlatedBoots:  "Light Plated Boots",
	LinkedMail:        "Linked Mail",
	LionHelm:          "Lion Helm",
	LoricatedMail:     "Loricated Mail",
	MagePlate:         "Mage Plate",
	Mask:              "Mask",
	MeshArmor:         "Mesh Armor",
	MeshBelt:          "Mesh Belt",
	MeshBoots:         "Mesh Boots",
	MirroredBoots:     "Mirrored Boots",
	MithrilCoil:       "Mithril Coil",
	MyrmidonGreaves:   "Myrmidon Greaves",
	OgreGauntlets:     "Ogre Gauntlets",
	OrnatePlate:       "Ornate Plate",
	PlateBoots:        "Plate Boots",
	QuiltedArmor:      "Quilted Armor",
	RageMask:          "Rage Mask",
	RingMail:          "Ring Mail",
	RussetArmor:       "Russet Armor",
	SacredArmor:       "Sacred Armor",
	SacredFeathers:    "Sacred Feathers",
	Sallet:            "Sallet",
	Sash:              "Sash",
	SavageHelmet:      "Savage Helmet",
	ScaleMail:         "Scale Mail",
	ScarabHusk:        "Scarab Husk",
	ScarabshellBoots:  "Scarabshell Boots",
	SerpentskinArmor:  "Serpentskin Armor",
	ShadowPlate:       "Shadow Plate",
	Shako:             "Shako",
	SharkskinBelt:     "Sharkskin Belt",
	SharkskinBoots:    "Sharkskin Boots",
	SharkskinGloves:   "Sharkskin Gloves",
	SharktoothArmor:   "Sharktooth Armor",
	SkullCap:          "Skull Cap",
	SkySpirit:         "Sky Spirit",
	SlayerGuard:       "Slayer Guard",
	SpiderwebSash:     "Spiderweb Sash",
	SpiredHelm:        "Spired Helm",
	SpiritMask:        "Spirit Mask",
	SplintMail:        "Splint Mail",
	StuddedLeather:    "Studded Leather",
	SunSpirit:         "Sun Spirit",
	TemplarCoat:       "Templar Coat",
	Tiara:             "Tiara",
	TigulatedMail:     "Tigulated Mail",
	TotemicMask:       "Totemic Mask",
	TrellisedArmor:    "Trellised Armor",
	TrollBelt:         "Troll Belt",
	Vambraces:         "Vambraces",
	VampireboneGloves: "Vampirebone Gloves",
	VampirefangBelt:   "Vampirefang Belt",
	WarBelt:           "War Belt",
	WarBoots:          "War Boots",
	WarGauntlets:      "War Gauntlets",
	WarHat:            "War Hat",
	WingedHelm:        "Winged Helm",
	WireFleece:        "Wire Fleece",
	WolfHead:          "Wolf Head",
	Wyrmhide:          "Wyrmhide",
	WyrmhideBoots:     "Wyrmhide Boots",
}

// WeaponCodes : Weapon item codes mapped to their in game, human-friendly, readable name.
// nolint:gochecknoglobals // data variable
var WeaponCodes = map[ItemCode]string{
	AncientAxe:          "Ancient Axe",
	AncientSword:        "Ancient Sword",
	Arbalest:            "Arbalest",
	ArchonStaff:         "Archon Staff",
	AshwoodBow:          "Ashwood Bow",
	Ataghan:             "Ataghan",
	Axe:                 "Axe",
	BalancedAxe:         "Balanced Axe",
	BalancedKnife:       "Balanced Knife",
	Balista:             "Balista",
	BalrogBlade:         "Balrog Blade",
	BalrogSpear:         "Balrog Spear",
	BarbedClub:          "Barbed Club",
	Bardiche:            "Bardiche",
	BastardSword:        "Bastard Sword",
	BattleAxe:           "Battle Axe",
	BattleCestus:        "Battle Cestus",
	BattleDart:          "Battle Dart",
	BattleHammer:        "Battle Hammer",
	BattleScythe:        "Battle Scythe",
	BattleStaff:         "Battle Staff",
	BattleSword:         "Battle Sword",
	BeardedAxe:          "Bearded Axe",
	BecDeCorbin:         "Bec De Corbin",
	BerserkerAxe:        "Berserker Axe",
	Bill:                "Bill",
	Blade:               "Blade",
	BladeBow:            "Blade Bow",
	BladeTalons:         "Blade Talons",
	BoneKnife:           "Bone Knife",
	BoneWand:            "Bone Wand",
	Brandistock:         "Brandistock",
	BroadAxe:            "Broad Axe",
	BroadSword:          "Broad Sword",
	BurntWand:           "Burnt Wand",
	Caduceus:            "Caduceus",
	CedarBow:            "Cedar Bow",
	CedarStaff:          "Cedar Staff",
	CeremonialBow:       "Ceremonial Bow",
	CeremonialJavelin:   "Ceremonial Javelin",
	CeremonialPike:      "Ceremonial Pike",
	CeremonialSpear:     "Ceremonial Spear",
	Cestus:              "Cestus",
	ChampionAxe:         "Champion Axe",
	ChampionSword:       "Champion Sword",
	ChokingGasPotion:    "Choking Gas Potion",
	ChuKoNu:             "Chu-Ko-Nu",
	Cinquedeas:          "Cinquedeas",
	ClaspedOrb:          "Clasped Orb",
	Claws:               "Claws",
	Claymore:            "Claymore",
	Cleaver:             "Cleaver",
	CloudySphere:        "Cloudy Sphere",
	Club:                "Club",
	ColossalSword:       "Colossal Sword",
	ColossalBlade:       "Colossal Blade",
	ColossusCrossbow:    "Colossus Crossbow",
	ColossusVoulge:      "Colossus Voulge",
	CompositeBow:        "Composite Bow",
	ConquestSword:       "Conquest Sword",
	Crossbow:            "Crossbow",
	Crowbill:            "Crowbill",
	CrusaderBow:         "Crusader Bow",
	CrypticAxe:          "Cryptic Axe",
	CrypticSword:        "Cryptic Sword",
	CrystalSword:        "Crystal Sword",
	CrystallineGlobe:    "Crystalline Globe",
	Cudgel:              "Cudgel",
	Cutlass:             "Cutlass",
	DacianFalx:          "Dacian Falx",
	Dagger:              "Dagger",
	Decapitator:         "Decapitator",
	DecoyDagger:         "Decoy Dagger",
	DemonCrossbow:       "Demon Crossbow",
	DemonHeart:          "Demon Heart",
	DevilStar:           "Devil Star",
	DiamondBow:          "Diamond Bow",
	DimensionalBlade:    "Dimensional Blade",
	DimensionalShard:    "Dimensional Shard",
	Dirk:                "Dirk",
	DivineScepter:       "Divine Scepter",
	DoubleAxe:           "Double Axe",
	DoubleBow:           "Double Bow",
	DragonStone:         "Dragon Stone",
	EableOrb:            "Eable Orb",
	EdgeBow:             "Edge Bow",
	ElderStaff:          "Elder Staff",
	EldritchOrb:         "Eldritch Orb",
	ElegantBlade:        "Elegant Blade",
	Espadon:             "Espadon",
	EttinAxe:            "Ettin Axe",
	ExecutionerSword:    "Executioner Sword",
	ExplodingPotion:     "Exploding Potion",
	Falcata:             "Falcata",
	Falchion:            "Falchion",
	FangedKnife:         "Fanged Knife",
	Fascia:              "Fascia",
	FeralAxe:            "Feral Axe",
	FeralClaws:          "Feral Claws",
	Flail:               "Flail",
	Flamberge:           "Flamberge",
	FlangedMace:         "Flanged Mace",
	FlyingAxe:           "Flying Axe",
	FlyingKnife:         "Flying Knife",
	Francisca:           "Francisca",
	FulmatingPotion:     "Fulmating Potion",
	Fuscina:             "Fuscina",
	GhostGlaive:         "Ghost Glaive",
	GhostSpear:          "Ghost Spear",
	GhostWand:           "Ghost Wand",
	GiantAxe:            "Giant Axe",
	GiantSword:          "Giant Sword",
	GiantThresher:       "Giant Thresher",
	Gidbinn:             "Gidbinn",
	Gladius:             "Gladius",
	Glaive:              "Glaive",
	GloriousAxe:         "Glorious Axe",
	GlowingOrb:          "Glowing Orb",
	GnarledStaff:        "Gnarled Staff",
	GorgonCrossbow:      "Gorgon Crossbow",
	GothicAxe:           "Gothic Axe",
	GothicBow:           "Gothic Bow",
	GothicStaff:         "Gothic Staff",
	GothicSword:         "Gothic Sword",
	GrandMatronBow:      "Grand Matron Bow",
	GrandScepter:        "Grand Scepter",
	GraveWand:           "Grave Wand",
	GreatAxe:            "Great Axe",
	GreatBow:            "Great Bow",
	GreatMaul:           "Great Maul",
	GreatPilum:          "Great Pilum",
	GreatPoleaxe:        "Great Poleaxe",
	GreatSword:          "Great Sword",
	GreaterClaws:        "Greater Claws",
	GreaterTalons:       "Greater Talons",
	GrimScythe:          "Grim Scythe",
	GrimWand:            "Grim Wand",
	Halberd:             "Halberd",
	HandAxe:             "Hand Axe",
	HandScythe:          "Hand Scythe",
	Harpoon:             "Harpoon",
	Hatchet:             "Hatchet",
	HatchetHands:        "HatchetHands",
	HeavenlyStone:       "Heavenly Stone",
	HeavyCrossbow:       "Heavy Crossbow",
	HellforgeHammer:     "Hellforge Hammer",
	HighlandBlade:       "Highland Blade",
	HolyWaterSprinkler:  "Holy Water Sprinkler",
	HoradricMalus:       "Horadric Malus",
	HoradricStaff:       "Horadric Staff",
	HuntersBow:          "Hunters Bow",
	Hurlbat:             "Hurlbat",
	HydraBow:            "Hydra Bow",
	HydraEdge:           "Hydra Edge",
	HyperionJavelin:     "Hyperion Javelin",
	HyperionSpear:       "Hyperion Spear",
	JaggedStar:          "Jagged Star",
	Javelin:             "Javelin",
	JoStaff:             "Jo Staff",
	Katar:               "Katar",
	KhalimFlail:         "Khalim Flail",
	Knout:               "Knout",
	Kriss:               "Kriss",
	Lance:               "Lance",
	LargeAxe:            "Large Axe",
	LegendSpike:         "Legend Spike",
	LegendSword:         "Legend Sword",
	LegendaryMallet:     "Legendary Mallet",
	LichWand:            "Lich Wand",
	LightCrossbow:       "Light Crossbow",
	LochaberAxe:         "Lochaber Axe",
	LongBattleBow:       "Long Battle Bow",
	LongBow:             "Long Bow",
	LongSiegeBow:        "Long Siege Bow",
	LongStaff:           "Long Staff",
	LongSword:           "Long Sword",
	LongWarBow:          "Long War Bow",
	Mace:                "Mace",
	MaidenJavelin:       "Maiden Javelin",
	MaidenPike:          "Maiden Pike",
	MaidenSpear:         "Maiden Spear",
	Mancatcher:          "Mancatcher",
	MarteldeFer:         "Martel de Fer",
	MatriarchalBow:      "Matriarchal Bow",
	MatriarchalPike:     "Matriarchal Pike",
	MatriarchalSpear:    "Matriarchal Spear",
	MatriarchalJavelin:  "Matriarchal Javelin",
	Maul:                "Maul",
	MightyScepter:       "Mighty Scepter",
	MilitaryAxe:         "Military Axe",
	MilitaryPick:        "Military Pick",
	MithralPoint:        "Mithral Point",
	MorningStar:         "Morning Star",
	MythicalSword:       "Mythical Sword",
	Naga:                "Naga",
	OgreAxe:             "Ogre Axe",
	OgreMaul:            "Ogre Maul",
	OilPotion:           "Oil Potion",
	Partizan:            "Partizan",
	PelletBow:           "Pellet Bow",
	PetrifiedWand:       "Petrified Wand",
	PhaseBlade:          "Phase Blade",
	Pike:                "Pike",
	Pilum:               "Pilum",
	Poignard:            "Poignard",
	Poleaxe:             "Poleaxe",
	PolishedWand:        "Polished Wand",
	QuarterStaff:        "Quarter Staff",
	Quhab:               "Quhab",
	RancidGasPotion:     "Rancid Gas Potion",
	RazorBow:            "Razor Bow",
	ReflexBow:           "Reflex Bow",
	ReinforcedMace:      "Reinforced Mace",
	RepeatingCrossbow:   "Repeating Crossbow",
	Rondel:              "Rondel",
	RuneBow:             "Rune Bow",
	RuneScepter:         "Rune Scepter",
	RuneStaff:           "Rune Staff",
	RuneSword:           "Rune Sword",
	RunicTalons:         "Runic Talons",
	Sabre:               "Sabre",
	SacredGlobe:         "Sacred Globe",
	Scepter:             "Scepter",
	Scimitar:            "Scimitar",
	ScissorsKatar:       "Scissors Katar",
	ScissorsQuhab:       "Scissors Quhab",
	ScissorsSuwayyah:    "Scissors Suwayyah",
	Scourge:             "Scourge",
	Scythe:              "Scythe",
	SeraphRod:           "Seraph Rod",
	ShadowBow:           "Shadow Bow",
	Shamshir:            "Shamshir",
	Shillelah:           "Shillelah",
	ShortBattleBow:      "Short Battle Bow",
	ShortBow:            "Short Bow",
	ShortSiegeBow:       "Short Siege Bow",
	ShortSpear:          "Short Spear",
	ShortStaff:          "Short Staff",
	ShortSword:          "Short Sword",
	ShortWarBow:         "Short War Bow",
	SiegeCrossbow:       "Siege Crossbow",
	SilverEdgedAxe:      "Silver Edged Axe",
	Simbilan:            "Simbilan",
	SmallCrescent:       "Small Crescent",
	SmokedSphere:        "Smoked Sphere",
	SparklingBall:       "Sparkling Ball",
	Spear:               "Spear",
	Spetum:              "Spetum",
	Spiculum:            "Spiculum",
	SpiderBow:           "Spider Bow",
	SpikedClub:          "Spiked Club",
	StaffOfTheKings:     "Staff Of The Kings",
	StagBow:             "Stag Bow",
	Stalagmite:          "Stalagmite",
	Stilleto:            "Stilleto",
	StranglingGasPotion: "Strangling Gas Potion",
	StygianPike:         "Stygian Pike",
	StygianPilum:        "Stygian Pilum",
	SuperKhalimFlail:    "Super Khalim Flail",
	Suwayyah:            "Suwayyah",
	SwirlingCrystal:     "Swirling Crystal",
	Tabar:               "Tabar",
	Thresher:            "Thresher",
	ThrowingAxe:         "Throwing Axe",
	ThrowingKnife:       "Throwing Knife",
	ThrowingSpear:       "Throwing Spear",
	ThunderMaul:         "Thunder Maul",
	Tomahawk:            "Tomahawk",
	TombWand:            "Tomb Wand",
	Trident:             "Trident",
	Truncheon:           "Truncheon",
	Tulwar:              "Tulwar",
	TuskSword:           "Tusk Sword",
	TwinAxe:             "Twin Axe",
	TwoHandedSword:      "Two Handed Sword",
	TyrantClub:          "Tyrant Club",
	UnearthedWand:       "Unearthed Wand",
	VortexOrb:           "Vortex Orb",
	Voulge:              "Voulge",
	WalkingStick:        "Walking Stick",
	Wand:                "Wand",
	WarAxe:              "War Axe",
	WarClub:             "War Club",
	WarDart:             "War Dart",
	WarFist:             "War Fist",
	WarFork:             "War Fork",
	WarHammer:           "War Hammer",
	WarJavelin:          "War Javelin",
	WarPike:             "War Pike",
	WarScepter:          "War Scepter",
	WarScythe:           "War Scythe",
	WarSpear:            "War Spear",
	WarSpike:            "War Spike",
	WarStaff:            "War Staff",
	WarSword:            "War Sword",
	WardBow:             "Ward Bow",
	WingedAxe:           "Winged Axe",
	WingedHarpoon:       "Winged Harpoon",
	WingedKnife:         "Winged Knife",
	WirtsLeg:            "Wirts Leg",
	WristBlade:          "Wrist Blade",
	WristSpike:          "Wrist Spike",
	WristSword:          "Wrist Sword",
	Yari:                "Yari",
	YewWand:             "Yew Wand",
	Zweihander:          "Zweihander",
}

// MiscCodes - Misc items codes, like jewelry, gems, potions and runes, mapped to their in
// game, human-friendly, readable name.
// nolint:gochecknoglobals // data var
var MiscCodes = map[ItemCode]string{
	Amethyst:                      "Amethyst",
	AmnRune:                       "Amn Rune",
	Amulet:                        "Amulet",
	AntidotePotion:                "Antidote Potion",
	Arrows:                        "Arrows",
	BaalsEye:                      "Baal's Eye",
	BarkScroll:                    "Bark Scroll",
	BerRune:                       "Ber Rune",
	Bolts:                         "Bolts",
	BookofSkill:                   "Book of Skill",
	BurningEssenceofTerror:        "Burning Essence of Terror",
	ChamRune:                      "Cham Rune",
	ChargedEssenceofHatred:        "Charged Essence of Hatred",
	GrandCharm:                    "Grand Charm",
	LargeCharm:                    "Large Charm",
	SmallCharm:                    "Small Charm",
	ChippedAmethyst:               "Chipped Amethyst",
	ChippedDiamond:                "Chipped Diamond",
	ChippedEmerald:                "Chipped Emerald",
	ChippedRuby:                   "Chipped Ruby",
	ChippedSapphire:               "Chipped Sapphire",
	ChippedSkull:                  "Chipped Skull",
	ChippedTopaz:                  "Chipped Topaz",
	DecipheredBarkScroll:          "Deciphered Bark Scroll",
	DiablosHorn:                   "Diablo's Horn",
	Diamond:                       "Diamond",
	DolRune:                       "Dol Rune",
	ElRune:                        "El Rune",
	EldRune:                       "Eld Rune",
	Elixir:                        "Elixir",
	Emerald:                       "Emerald",
	EthRune:                       "Eth Rune",
	FalRune:                       "Fal Rune",
	FesteringEssenceofDestruction: "Festering Essence of Destruction",
	FlawedAmethyst:                "Flawed Amethyst",
	FlawedDiamond:                 "Flawed Diamond",
	FlawedEmerald:                 "Flawed Emerald",
	FlawedRuby:                    "Flawed Ruby",
	FlawedSapphire:                "Flawed Sapphire",
	FlawedSkull:                   "Flawed Skull",
	FlawedTopaz:                   "Flawed Topaz",
	FlawlessAmethyst:              "Flawless Amethyst",
	FlawlessDiamond:               "Flawless Diamond",
	FlawlessEmerald:               "Flawless Emerald",
	FlawlessRuby:                  "Flawless Ruby",
	FlawlessSapphire:              "Flawless Sapphire",
	FlawlessSkull:                 "Flawless Skull",
	FlawlessTopaz:                 "Flawless Topaz",
	FullHealingPotion:             "Full Healing Potion",
	FullManaPotion:                "Full Mana Potion",
	FullRejuvenationPotion:        "Full Rejuvenation Potion",
	Gold:                          "Gold",
	GoldBird:                      "Gold Bird",
	GreaterHealingPotion:          "Greater Healing Potion",
	GreaterManaPotion:             "Greater Mana Potion",
	GulRune:                       "Gul Rune",
	HealingPotion:                 "Healing Potion",
	HealingPotionMid:              "Healing Potion",
	HelRune:                       "Hel Rune",
	Herb:                          "Herb",
	HoradricCube:                  "Horadric Cube",
	IdentifyBook:                  "Identify Book",
	IdentifyScroll:                "Identify Scroll",
	IoRune:                        "Io Rune",
	IstRune:                       "Ist Rune",
	IthRune:                       "Ith Rune",
	JadeFigurine:                  "Jade Figurine",
	JahRune:                       "Jah Rune",
	Jewel:                         "Jewel",
	KeyofDestruction:              "Key of Destruction",
	KeyofHate:                     "Key of Hate",
	KeyofTerror:                   "Key of Terror",
	KhalimsBrain:                  "Khalim's Brain",
	KhalimsEye:                    "Khalim's Eye",
	KhalimsHeart:                  "Khalim's Heart",
	KoRune:                        "Ko Rune",
	LamEsensTome:                  "Lam Esens Tome",
	LargeBluePotion:               "Large Blue Potion",
	LargeRedPotion:                "Large Red Potion",
	LemRune:                       "Lem Rune",
	LesserHealingPotion:           "Lesser Healing Potion",
	LesserManaPotion:              "Lesser Mana Potion",
	LightHealingPotion:            "Light Healing Potion",
	LightManaPotion:               "Light Mana Potion",
	LoRune:                        "Lo Rune",
	LumRune:                       "Lum Rune",
	Maguffin:                      "Maguffin",
	MalRune:                       "Mal Rune",
	ManaPotion:                    "Mana Potion",
	ManaPotionMid:                 "Mana Potion",
	MephistosBrain:                "Mephisto's Brain",
	MephistoKey:                   "Mephisto Key",
	MephistoSoulStone:             "Mephisto Soul Stone",
	NefRune:                       "Nef Rune",
	OhmRune:                       "Ohm Rune",
	OrtRune:                       "Ort Rune",
	PerfectAmethyst:               "Perfect Amethyst",
	PerfectDiamond:                "Perfect Diamond",
	PerfectEmerald:                "Perfect Emerald",
	PerfectRuby:                   "Perfect Ruby",
	PerfectSapphire:               "Perfect Sapphire",
	PerfectSkull:                  "Perfect Skull",
	PerfectTopaz:                  "Perfect Topaz",
	PlayerEar:                     "Player Ear",
	PulRune:                       "Pul Rune",
	RalRune:                       "Ral Rune",
	RejuvenationPotion:            "Rejuvenation Potion",
	Ring:                          "Ring",
	Ruby:                          "Ruby",
	Sapphire:                      "Sapphire",
	Scroll:                        "Scroll",
	ScrollofHoradric:              "Scroll of Horadric",
	ScrollofMalah:                 "Scroll of Malah",
	PotionofLife:                  "Potion of Life",
	ShaelRune:                     "Shael Rune",
	SkeletonKey:                   "Skeleton Key",
	Skull:                         "Skull",
	SmallBluePotion:               "Small Blue Potion",
	SmallRedPotion:                "Small Red Potion",
	SolRune:                       "Sol Rune",
	StaminaPotion:                 "Stamina Potion",
	StandardofHeroes:              "Standard of Heroes",
	StrongHealingPotion:           "Strong Healing Potion",
	StrongManaPotion:              "Strong Mana Potion",
	SurRune:                       "Sur Rune",
	TalRune:                       "Tal Rune",
	ThawingPotion:                 "Thawing Potion",
	ThulRune:                      "Thul Rune",
	TirRune:                       "Tir Rune",
	TokenofAbsolution:             "Token of Absolution",
	Topaz:                         "Topaz",
	Torch:                         "Torch",
	TownPortalBook:                "Town Portal Book",
	TownPortalScroll:              "Town Portal Scroll",
	TwistedEssenceofSuffering:     "Twisted Essence of Suffering",
	UmRune:                        "Um Rune",
	VexRune:                       "Vex Rune",
	ViperAmulet:                   "Viper Amulet",
	ZodRune:                       "Zod Rune",
}
