package itemdata

//go:generate stringer -linecomment -type RareName -output rare_string.go

// RareName represents a rare name
type RareName uint16

// rare names
const (
	RareNameBite RareName = iota + 1 // Bite
	RareName2                        // Scratch
	RareName3                        // Scalpel
	RareName4                        // Fang
	RareName5                        // Gutter
	RareName6                        // Thirst
	RareName7                        // Razor
	RareName8                        // Scythe
	RareName9                        // Edge
	RareName10                       // Saw
	RareName11                       // Splitter
	RareName12                       // Cleaver
	RareName13                       // Sever
	RareName14                       // Sunder
	RareName15                       // Rend
	RareName16                       // Mangler
	RareName17                       // Slayer
	RareName18                       // Reaver
	RareName19                       // Spawn
	RareName20                       // Gnash
	RareName21                       // Star
	RareName22                       // Blow
	RareName23                       // Smasher
	RareName24                       // Bane
	RareName25                       // Crusher
	RareName26                       // Breaker
	RareName27                       // Grinder
	RareName28                       // Crack
	RareName29                       // Mallet
	RareName30                       // Knell
	RareName31                       // Lance
	RareName32                       // Spike
	RareName33                       // Impaler
	RareName34                       // Skewer
	RareName35                       // Prod
	RareName36                       // Scourge
	RareName37                       // Wand
	RareName38                       // Wrack
	RareName39                       // Barb
	RareName40                       // Needle
	RareName41                       // Dart
	RareName42                       // Bolt
	RareName43                       // Quarrel
	RareName44                       // Fletch
	RareName45                       // Flight
	RareName46                       // Nock
	RareName47                       // Horn
	RareName48                       // Stinger
	RareName49                       // Quill
	RareName50                       // Goad
	RareName51                       // Branch
	RareName52                       // Spire
	RareName53                       // Song
	RareName54                       // Call
	RareName55                       // Cry
	RareName56                       // Spell
	RareName57                       // Chant
	RareName58                       // Weaver
	RareName59                       // Gnarl
	RareName60                       // Visage
	RareName61                       // Crest
	RareName62                       // Circlet
	RareName63                       // Veil
	RareName64                       // Hood
	RareName65                       // Mask
	RareName66                       // Brow
	RareName67                       // Casque
	RareName68                       // Visor
	RareName69                       // Cowl
	RareName70                       // Hide
	RareName71                       // Pelt
	RareName72                       // Carapace
	RareName73                       // Coat
	RareName74                       // Wrap
	RareName75                       // Suit
	RareName76                       // Cloak
	RareName77                       // Shroud
	RareName78                       // Jack
	RareName79                       // Mantle
	RareName80                       // Guard
	RareName81                       // Badge
	RareName82                       // Rock
	RareName83                       // Aegis
	RareName84                       // Ward
	RareName85                       // Tower
	RareName86                       // Shield
	RareName87                       // Wing
	RareName88                       // Mark
	RareName89                       // Emblem
	RareName90                       // Hand
	RareName91                       // Fist
	RareName92                       // Claw
	RareName93                       // Clutches
	RareName94                       // Grip
	RareName95                       // Grasp
	RareName96                       // Hold
	RareName97                       // Torch
	RareName98                       // Finger
	RareName99                       // Knuckle
	RareName100                      // Shank
	RareName101                      // Spur
	RareName102                      // Tread
	RareName103                      // Stalker
	RareName104                      // Greave
	RareName105                      // Blazer
	RareName106                      // Nails
	RareName107                      // Trample
	RareName108                      // Brogues
	RareName109                      // Track
	RareName110                      // Slippers
	RareName111                      // Clasp
	RareName112                      // Buckle
	RareName113                      // Harness
	RareName114                      // Lock
	RareName115                      // Fringe
	RareName116                      // Winding
	RareName117                      // Chain
	RareName118                      // Strap
	RareName119                      // Lash
	RareName120                      // Cord
	RareName121                      // Knot
	RareName122                      // Circle
	RareName123                      // Loop
	RareName124                      // Eye
	RareName125                      // Turn
	RareName126                      // Spiral
	RareName127                      // Coil
	RareName128                      // Gyre
	RareName129                      // Band
	RareName130                      // Whorl
	RareName131                      // Talisman
	RareName132                      // Heart
	RareName133                      // Noose
	RareName134                      // Necklace
	RareName135                      // Collar
	RareName136                      // Beads
	RareName137                      // Torc
	RareName138                      // Gorget
	RareName139                      // Scarab
	RareName140                      // Wood
	RareName141                      // Brand
	RareName142                      // Bludgeon
	RareName143                      // Cudgel
	RareName144                      // Loom
	RareName145                      // Harp
	RareName146                      // Master
	RareName147                      // Barl
	RareName148                      // Hew
	RareName149                      // Crook
	RareName150                      // Mar
	RareName151                      // Shell
	RareName152                      // Stake
	RareName153                      // Picket
	RareName154                      // Pale
	RareName155                      // Flange
	RareName156                      // Beast
	RareName157                      // Eagle
	RareName158                      // Raven
	RareName159                      // Viper
	RareName160                      // Ghoul
	RareName161                      // Skull
	RareName162                      // Blood
	RareName163                      // Dread
	RareName164                      // Doom
	RareName165                      // Grim
	RareName166                      // Bone
	RareName167                      // Death
	RareName168                      // Shadow
	RareName169                      // Storm
	RareName170                      // Rune
	RareName171                      // Plague
	RareName172                      // Stone
	RareName173                      // Wraith
	RareName174                      // Spirit
	RareName175                      // Storm
	RareName176                      // Demon
	RareName177                      // Cruel
	RareName178                      // Empyrion
	RareName179                      // Bramble
	RareName180                      // Pain
	RareName181                      // Loath
	RareName182                      // Glyph
	RareName183                      // Imp
	RareName184                      // Fiendra
	RareName185                      // Hailstone
	RareName186                      // Gale
	RareName187                      // Dire
	RareName188                      // Soul
	RareName189                      // Brimstone
	RareName190                      // Corpse
	RareName191                      // Carrion
	RareName192                      // Armageddon
	RareName193                      // Havoc
	RareName194                      // Bitter
	RareName195                      // Entropy
	RareName196                      // Chaos
	RareName197                      // Order
	RareName198                      // Rule
	RareName199                      // Warp
	RareName200                      // Rift
	RareName201                      // Corruption
)
