package itemdata

//go:generate stringer -linecomment -type RareName -output rare_string.go

// RareName represents a rare name
type RareName uint16

// rare names
const (
	RareName1   RareName = iota + 1 // Biteg
	RareName2                       // Scratchg
	RareName3                       // Scalpelg
	RareName4                       // Fangg
	RareName5                       // Gutterg
	RareName6                       // Thirstg
	RareName7                       // Razorg
	RareName8                       // Scytheg
	RareName9                       // Edgeg
	RareName10                      // Sawg
	RareName11                      // Splitterg
	RareName12                      // Cleaverg
	RareName13                      // Severg
	RareName14                      // Sunderg
	RareName15                      // Rendg
	RareName16                      // Manglerg
	RareName17                      // Slayerg
	RareName18                      // Reaverg
	RareName19                      // Spawng
	RareName20                      // Gnashg
	RareName21                      // Starg
	RareName22                      // Blowg
	RareName23                      // Smasherg
	RareName24                      // Baneg
	RareName25                      // Crusherg
	RareName26                      // Breakerg
	RareName27                      // Grinderg
	RareName28                      // Crackg
	RareName29                      // Malletg
	RareName30                      // Knellg
	RareName31                      // Lanceg
	RareName32                      // Spikeg
	RareName33                      // Impalerg
	RareName34                      // Skewerg
	RareName35                      // Prodg
	RareName36                      // Scourgeg
	RareName37                      // Wandg
	RareName38                      // Wrackg
	RareName39                      // Barbg
	RareName40                      // Needleg
	RareName41                      // Dartg
	RareName42                      // Boltg
	RareName43                      // Quarrelg
	RareName44                      // Fletchg
	RareName45                      // Flightg
	RareName46                      // Nockg
	RareName47                      // Horng
	RareName48                      // Stingerg
	RareName49                      // Quillg
	RareName50                      // Goadg
	RareName51                      // Branchg
	RareName52                      // Spireg
	RareName53                      // Songg
	RareName54                      // Callg
	RareName55                      // Cryg
	RareName56                      // Spellg
	RareName57                      // Chantg
	RareName58                      // Weaverg
	RareName59                      // Gnarlg
	RareName60                      // Visageg
	RareName61                      // Crestg
	RareName62                      // Circletg
	RareName63                      // Veilg
	RareName64                      // Hoodg
	RareName65                      // Maskg
	RareName66                      // Browg
	RareName67                      // Casqueg
	RareName68                      // Visorg
	RareName69                      // Cowlg
	RareName70                      // Hideg
	RareName71                      // Peltg
	RareName72                      // Carapaceg
	RareName73                      // Coatg
	RareName74                      // Wrapg
	RareName75                      // Suitg
	RareName76                      // Cloakg
	RareName77                      // Shroudg
	RareName78                      // Jackg
	RareName79                      // Mantleg
	RareName80                      // Guardg
	RareName81                      // Badgeg
	RareName82                      // Rockg
	RareName83                      // Aegisg
	RareName84                      // Wardg
	RareName85                      // Towerg
	RareName86                      // Shieldg
	RareName87                      // Wingg
	RareName88                      // Markg
	RareName89                      // Emblemg
	RareName90                      // Handg
	RareName91                      // Fistg
	RareName92                      // Clawg
	RareName93                      // Clutchesg
	RareName94                      // Gripg
	RareName95                      // Graspg
	RareName96                      // Holdg
	RareName97                      // Torchg
	RareName98                      // Fingerg
	RareName99                      // Knuckleg
	RareName100                     // Shankg
	RareName101                     // Spurg
	RareName102                     // Treadg
	RareName103                     // Stalkerg
	RareName104                     // Greaveg
	RareName105                     // Blazerg
	RareName106                     // Nailsg
	RareName107                     // Trampleg
	RareName108                     // Broguesg
	RareName109                     // Trackg
	RareName110                     // Slippersg
	RareName111                     // Claspg
	RareName112                     // Buckleg
	RareName113                     // Harnessg
	RareName114                     // Lockg
	RareName115                     // Fringeg
	RareName116                     // Windingg
	RareName117                     // Chaing
	RareName118                     // Strapg
	RareName119                     // Lashg
	RareName120                     // Cordg
	RareName121                     // Knotg
	RareName122                     // Circleg
	RareName123                     // Loopg
	RareName124                     // Eyeg
	RareName125                     // Turng
	RareName126                     // Spiralg
	RareName127                     // Coilg
	RareName128                     // Gyreg
	RareName129                     // Bandg
	RareName130                     // Whorlg
	RareName131                     // Talismang
	RareName132                     // Heartg
	RareName133                     // Nooseg
	RareName134                     // Necklaceg
	RareName135                     // Collarg
	RareName136                     // Beadsg
	RareName137                     // Torcg
	RareName138                     // Gorgetg
	RareName139                     // Scarabg
	RareName140                     // Woodg
	RareName141                     // Brandg
	RareName142                     // Bludgeong
	RareName143                     // Cudgelg
	RareName144                     // Loomg
	RareName145                     // Harpg
	RareName146                     // Masterg
	RareName147                     // Barlg
	RareName148                     // Hewg
	RareName149                     // Crookg
	RareName150                     // Marg
	RareName151                     // Shellg
	RareName152                     // Stakeg
	RareName153                     // Picketg
	RareName154                     // Paleg
	RareName155                     // Flangeg
	RareName156                     // Beastg
	RareName157                     // Eagleg
	RareName158                     // Raveng
	RareName159                     // Viperg
	RareName160                     // Ghoulg
	RareName161                     // Skullg
	RareName162                     // Bloodg
	RareName163                     // Dreadg
	RareName164                     // Doomg
	RareName165                     // Grimg
	RareName166                     // Boneg
	RareName167                     // Deathg
	RareName168                     // Shadowg
	RareName169                     // Stormg
	RareName170                     // Runeg
	RareName171                     // Plagueg
	RareName172                     // Stoneg
	RareName173                     // Wraithg
	RareName174                     // Spiritg
	RareName175                     // Stormg
	RareName176                     // Demong
	RareName177                     // Cruelg
	RareName178                     // Empyriong
	RareName179                     // Brambleg
	RareName180                     // Paing
	RareName181                     // Loathg
	RareName182                     // Glyphg
	RareName183                     // Impg
	RareName184                     // Fiendrag
	RareName185                     // Hailstoneg
	RareName186                     // Galeg
	RareName187                     // Direg
	RareName188                     // Soulg
	RareName189                     // Brimstoneg
	RareName190                     // Corpseg
	RareName191                     // Carriong
	RareName192                     // Armageddong
	RareName193                     // Havocg
	RareName194                     // Bitterg
	RareName195                     // Entropyg
	RareName196                     // Chaosg
	RareName197                     // Orderg
	RareName198                     // Ruleg
	RareName199                     // Warpg
	RareName200                     // Riftg
	RareName201                     // Corruptiong
)
