// Code generated by "stringer -linecomment -type RunewordID -output runeword_string.go"; DO NOT EDIT.

package itemdata

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Runeword27-27]
	_ = x[Runeword30-28]
	_ = x[Runeword32-29]
	_ = x[Runeword34-30]
	_ = x[Runeword35-31]
	_ = x[Runeword36-32]
	_ = x[Runeword37-33]
	_ = x[Runeword39-34]
	_ = x[Runeword40-35]
	_ = x[Runeword42-36]
	_ = x[Runeword43-37]
	_ = x[Runeword46-38]
	_ = x[Runeword51-39]
	_ = x[Runeword52-40]
	_ = x[Runeword53-41]
	_ = x[Runeword55-42]
	_ = x[Runeword56-43]
	_ = x[Runeword57-44]
	_ = x[Runeword59-45]
	_ = x[Runeword60-46]
	_ = x[Runeword62-47]
	_ = x[Runeword63-48]
	_ = x[Runeword64-49]
	_ = x[Runeword65-50]
	_ = x[Runeword67-51]
	_ = x[Runeword70-52]
	_ = x[Runeword71-53]
	_ = x[Runeword73-54]
	_ = x[Runeword74-55]
	_ = x[Runeword75-56]
	_ = x[Runeword77-57]
	_ = x[Runeword80-58]
	_ = x[Runeword81-59]
	_ = x[Runeword85-60]
	_ = x[Runeword86-61]
	_ = x[Runeword88-62]
	_ = x[Runeword91-63]
	_ = x[Runeword92-64]
	_ = x[Runeword95-65]
	_ = x[Runeword97-66]
	_ = x[Runeword98-67]
	_ = x[Runeword100-68]
	_ = x[Runeword101-69]
	_ = x[Runeword106-70]
	_ = x[Runeword107-71]
	_ = x[Runeword108-72]
	_ = x[Runeword112-73]
	_ = x[Runeword113-74]
	_ = x[Runeword116-75]
	_ = x[Runeword117-76]
	_ = x[Runeword120-77]
	_ = x[Runeword123-78]
	_ = x[Runeword124-79]
	_ = x[Runeword128-80]
	_ = x[Runeword131-81]
	_ = x[Runeword134-82]
	_ = x[Runeword135-83]
	_ = x[Runeword137-84]
	_ = x[Runeword141-85]
	_ = x[Runeword142-86]
	_ = x[Runeword145-87]
	_ = x[Runeword146-88]
	_ = x[Runeword147-89]
	_ = x[Runeword151-90]
	_ = x[Runeword153-91]
	_ = x[Runeword155-92]
	_ = x[Runeword156-93]
	_ = x[Runeword158-94]
	_ = x[Runeword159-95]
	_ = x[Runeword162-96]
	_ = x[Runeword164-97]
	_ = x[Runeword173-98]
	_ = x[Runeword179-99]
	_ = x[Runeword185-100]
	_ = x[Runeword187-101]
	_ = x[Runeword188-102]
	_ = x[Runeword193-103]
	_ = x[Runeword195-104]
	_ = x[Runeword2718-105]
}

const _RunewordID_name = "Ancient's PledgeBeastBlackBoneBrambleBrandBreath of the DyingCall to ArmsChains of HonorChaosCrescent MoonDeathDestructionDoomDragonDreamDuressEdgeEnigmaEnlightenmentEternityExileFaithFamineFortitudeFuryGloomGriefHand of JusticeHarmoryHeart of the OakHoly ThunderHonorIceInfinityInsightKing's GraceKingslayerLast WishLawbringerLeafLionheartLoreMaliceMelodyMemoryMythNadirOathObediencePassionPeaceWinterPhoenixPlaguePridePrinciplePrudenceRadianceRainRhymeRiftSanctuarySilenceSmokeSpiritSplendorStealthSteelStoneStrengthTreacheryVenomWealthWhiteWindWrathZephyrDelirium"

var _RunewordID_index = [...]uint16{0, 16, 21, 26, 30, 37, 42, 61, 73, 88, 93, 106, 111, 122, 126, 132, 137, 143, 147, 153, 166, 174, 179, 184, 190, 199, 203, 208, 213, 228, 235, 251, 263, 268, 271, 279, 286, 298, 308, 317, 327, 331, 340, 344, 350, 356, 362, 366, 371, 375, 384, 391, 396, 402, 409, 415, 420, 429, 437, 445, 449, 454, 458, 467, 474, 479, 485, 493, 500, 505, 510, 518, 527, 532, 538, 543, 547, 552, 558, 566}

func (i RunewordID) String() string {
	i -= 27
	if i >= RunewordID(len(_RunewordID_index)-1) {
		return "RunewordID(" + strconv.FormatInt(int64(i+27), 10) + ")"
	}
	return _RunewordID_name[_RunewordID_index[i]:_RunewordID_index[i+1]]
}
