// Code generated by "stringer -linecomment -type RunewordID -output runeword_string.go"; DO NOT EDIT.

package itemdata

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Runeword27-27]
	_ = x[Runeword30-30]
	_ = x[Runeword32-32]
	_ = x[Runeword34-34]
	_ = x[Runeword35-35]
	_ = x[Runeword36-36]
	_ = x[Runeword37-37]
	_ = x[Runeword39-39]
	_ = x[Runeword40-40]
	_ = x[Runeword42-42]
	_ = x[Runeword43-43]
	_ = x[Runeword46-46]
	_ = x[Runeword51-50]
	_ = x[Runeword52-51]
	_ = x[Runeword53-52]
	_ = x[Runeword55-54]
	_ = x[Runeword56-55]
	_ = x[Runeword57-56]
	_ = x[Runeword59-58]
	_ = x[Runeword60-59]
	_ = x[Runeword62-61]
	_ = x[Runeword63-62]
	_ = x[Runeword64-63]
	_ = x[Runeword65-64]
	_ = x[Runeword67-66]
	_ = x[Runeword70-69]
	_ = x[Runeword71-70]
	_ = x[Runeword73-72]
	_ = x[Runeword74-73]
	_ = x[Runeword75-74]
	_ = x[Runeword77-76]
	_ = x[Runeword80-79]
	_ = x[Runeword81-80]
	_ = x[Runeword85-84]
	_ = x[Runeword86-85]
	_ = x[Runeword88-87]
	_ = x[Runeword91-90]
	_ = x[Runeword92-91]
	_ = x[Runeword95-94]
	_ = x[Runeword97-96]
	_ = x[Runeword98-97]
	_ = x[Runeword100-99]
	_ = x[Runeword101-100]
	_ = x[Runeword106-105]
	_ = x[Runeword107-106]
	_ = x[Runeword108-107]
	_ = x[Runeword112-111]
	_ = x[Runeword113-112]
	_ = x[Runeword116-115]
	_ = x[Runeword117-116]
	_ = x[Runeword120-119]
	_ = x[Runeword123-122]
	_ = x[Runeword124-123]
	_ = x[Runeword128-127]
	_ = x[Runeword131-130]
	_ = x[Runeword134-133]
	_ = x[Runeword135-134]
	_ = x[Runeword137-136]
	_ = x[Runeword141-140]
	_ = x[Runeword142-141]
	_ = x[Runeword145-144]
	_ = x[Runeword146-145]
	_ = x[Runeword147-146]
	_ = x[Runeword151-150]
	_ = x[Runeword153-152]
	_ = x[Runeword155-154]
	_ = x[Runeword156-155]
	_ = x[Runeword158-157]
	_ = x[Runeword159-158]
	_ = x[Runeword162-161]
	_ = x[Runeword164-163]
	_ = x[Runeword173-172]
	_ = x[Runeword179-178]
	_ = x[Runeword185-184]
	_ = x[Runeword187-186]
	_ = x[Runeword188-187]
	_ = x[Runeword193-192]
	_ = x[Runeword195-194]
	_ = x[Runeword2718-2718]
}

const _RunewordID_name = "Ancient's PledgeBeastBlackBoneBrambleBrandBreath of the DyingCall to ArmsChains of HonorChaosCrescent MoonDeathDestructionDoomDragonDreamDuressEdgeEnigmaEnlightenmentEternityExileFaithFamineFortitudeFuryGloomGriefHand of JusticeHarmoryHeart of the OakHoly ThunderHonorIceInfinityInsightKing's GraceKingslayerLast WishLawbringerLeafLionheartLoreMaliceMelodyMemoryMythNadirOathObediencePassionPeaceWinterPhoenixPlaguePridePrinciplePrudenceRadianceRainRhymeRiftSanctuarySilenceSmokeSpiritSplendorStealthSteelStoneStrengthTreacheryVenomWealthWhiteWindWrathZephyrDelirium"

var _RunewordID_map = map[RunewordID]string{
	27:   _RunewordID_name[0:16],
	30:   _RunewordID_name[16:21],
	32:   _RunewordID_name[21:26],
	34:   _RunewordID_name[26:30],
	35:   _RunewordID_name[30:37],
	36:   _RunewordID_name[37:42],
	37:   _RunewordID_name[42:61],
	39:   _RunewordID_name[61:73],
	40:   _RunewordID_name[73:88],
	42:   _RunewordID_name[88:93],
	43:   _RunewordID_name[93:106],
	46:   _RunewordID_name[106:111],
	50:   _RunewordID_name[111:122],
	51:   _RunewordID_name[122:126],
	52:   _RunewordID_name[126:132],
	54:   _RunewordID_name[132:137],
	55:   _RunewordID_name[137:143],
	56:   _RunewordID_name[143:147],
	58:   _RunewordID_name[147:153],
	59:   _RunewordID_name[153:166],
	61:   _RunewordID_name[166:174],
	62:   _RunewordID_name[174:179],
	63:   _RunewordID_name[179:184],
	64:   _RunewordID_name[184:190],
	66:   _RunewordID_name[190:199],
	69:   _RunewordID_name[199:203],
	70:   _RunewordID_name[203:208],
	72:   _RunewordID_name[208:213],
	73:   _RunewordID_name[213:228],
	74:   _RunewordID_name[228:235],
	76:   _RunewordID_name[235:251],
	79:   _RunewordID_name[251:263],
	80:   _RunewordID_name[263:268],
	84:   _RunewordID_name[268:271],
	85:   _RunewordID_name[271:279],
	87:   _RunewordID_name[279:286],
	90:   _RunewordID_name[286:298],
	91:   _RunewordID_name[298:308],
	94:   _RunewordID_name[308:317],
	96:   _RunewordID_name[317:327],
	97:   _RunewordID_name[327:331],
	99:   _RunewordID_name[331:340],
	100:  _RunewordID_name[340:344],
	105:  _RunewordID_name[344:350],
	106:  _RunewordID_name[350:356],
	107:  _RunewordID_name[356:362],
	111:  _RunewordID_name[362:366],
	112:  _RunewordID_name[366:371],
	115:  _RunewordID_name[371:375],
	116:  _RunewordID_name[375:384],
	119:  _RunewordID_name[384:391],
	122:  _RunewordID_name[391:396],
	123:  _RunewordID_name[396:402],
	127:  _RunewordID_name[402:409],
	130:  _RunewordID_name[409:415],
	133:  _RunewordID_name[415:420],
	134:  _RunewordID_name[420:429],
	136:  _RunewordID_name[429:437],
	140:  _RunewordID_name[437:445],
	141:  _RunewordID_name[445:449],
	144:  _RunewordID_name[449:454],
	145:  _RunewordID_name[454:458],
	146:  _RunewordID_name[458:467],
	150:  _RunewordID_name[467:474],
	152:  _RunewordID_name[474:479],
	154:  _RunewordID_name[479:485],
	155:  _RunewordID_name[485:493],
	157:  _RunewordID_name[493:500],
	158:  _RunewordID_name[500:505],
	161:  _RunewordID_name[505:510],
	163:  _RunewordID_name[510:518],
	172:  _RunewordID_name[518:527],
	178:  _RunewordID_name[527:532],
	184:  _RunewordID_name[532:538],
	186:  _RunewordID_name[538:543],
	187:  _RunewordID_name[543:547],
	192:  _RunewordID_name[547:552],
	194:  _RunewordID_name[552:558],
	2718: _RunewordID_name[558:566],
}

func (i RunewordID) String() string {
	if str, ok := _RunewordID_map[i]; ok {
		return str
	}
	return "RunewordID(" + strconv.FormatInt(int64(i), 10) + ")"
}
