// Code generated by "stringer -type CharacterClass -trimprefix Character -linecomment -output class_string.go"; DO NOT EDIT.

package d2senums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CharacterAmazon-0]
	_ = x[CharacterSorceress-1]
	_ = x[CharacterNecromancer-2]
	_ = x[CharacterPaladin-3]
	_ = x[CharacterBarbarian-4]
	_ = x[CharacterDruid-5]
	_ = x[CharacterAssassin-6]
}

const _CharacterClass_name = "AmazonSorceressNecromancerPaladinBarbarianDruidAssassin"

var _CharacterClass_index = [...]uint8{0, 6, 15, 26, 33, 42, 47, 55}

func (i CharacterClass) String() string {
	if i >= CharacterClass(len(_CharacterClass_index)-1) {
		return "CharacterClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CharacterClass_name[_CharacterClass_index[i]:_CharacterClass_index[i+1]]
}
