// Code generated by "stringer -linecomment -type ItemEquippedPlace -output equipped_place_string.go"; DO NOT EDIT.

package d2senums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EquippedAnywhere-0]
	_ = x[EquippedHead-1]
	_ = x[EquippedNeck-2]
	_ = x[EquippedTorse-3]
	_ = x[EquippedRightHand-4]
	_ = x[EquippedLeftHand-5]
	_ = x[EquippedRightFinger-6]
	_ = x[EquippedLeftFinger-7]
	_ = x[EquippedWaist-8]
	_ = x[EquippedFeet-9]
	_ = x[EquippedHands-10]
	_ = x[EquippedARightHand-11]
	_ = x[EquippedALeftHand-12]
}

const _ItemEquippedPlace_name = "headnecktorseright handleft handright fingerleft wingerwaistfeethandsalternative right handalternative left hand"

var _ItemEquippedPlace_index = [...]uint8{0, 0, 4, 8, 13, 23, 32, 44, 55, 60, 64, 69, 91, 112}

func (i ItemEquippedPlace) String() string {
	if i >= ItemEquippedPlace(len(_ItemEquippedPlace_index)-1) {
		return "ItemEquippedPlace(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ItemEquippedPlace_name[_ItemEquippedPlace_index[i]:_ItemEquippedPlace_index[i+1]]
}
