// Code generated by "stringer -type StatID"; DO NOT EDIT.

package d2sstats

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Strength-0]
	_ = x[Energy-1]
	_ = x[Dexterity-2]
	_ = x[Vitality-3]
	_ = x[UnusedStats-4]
	_ = x[UnusedSkills-5]
	_ = x[CurrentHP-6]
	_ = x[MaxHP-7]
	_ = x[CurrentMana-8]
	_ = x[MaxMana-9]
	_ = x[CurrentStamina-10]
	_ = x[MaxStamina-11]
	_ = x[Level-12]
	_ = x[Experience-13]
	_ = x[Gold-14]
	_ = x[StashedGold-15]
}

const _StatID_name = "StrengthEnergyDexterityVitalityUnusedStatsUnusedSkillsCurrentHPMaxHPCurrentManaMaxManaCurrentStaminaMaxStaminaLevelExperienceGoldStashedGold"

var _StatID_index = [...]uint8{0, 8, 14, 23, 31, 42, 54, 63, 68, 79, 86, 100, 110, 115, 125, 129, 140}

func (i StatID) String() string {
	if i >= StatID(len(_StatID_index)-1) {
		return "StatID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatID_name[_StatID_index[i]:_StatID_index[i+1]]
}
