// Code generated by "stringer -linecomment -type ItemEquippedPlace -output equipped_place_string.go"; DO NOT EDIT.

package d2senums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ItemEquippedAnywhere-0]
	_ = x[ItemEquippedHead-1]
	_ = x[ItemEquippedNeck-2]
	_ = x[ItemEquippedTorse-3]
	_ = x[ItemEquippedRightHand-4]
	_ = x[ItemEquippedLeftHand-5]
	_ = x[ItemEquippedRightFinger-6]
	_ = x[ItemEquippedLeftFinger-7]
	_ = x[ItemEquippedWaist-8]
	_ = x[ItemEquippedFeet-9]
	_ = x[ItemEquippedHands-10]
	_ = x[ItemEquippedARightHand-11]
	_ = x[ItemEquippedALeftHand-12]
}

const _ItemEquippedPlace_name = "headnecktorseright handleft handright fingerleft wingerwaistfeethandsalternative right handalternative left hand"

var _ItemEquippedPlace_index = [...]uint8{0, 0, 4, 8, 13, 23, 32, 44, 55, 60, 64, 69, 91, 112}

func (i ItemEquippedPlace) String() string {
	if i >= ItemEquippedPlace(len(_ItemEquippedPlace_index)-1) {
		return "ItemEquippedPlace(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ItemEquippedPlace_name[_ItemEquippedPlace_index[i]:_ItemEquippedPlace_index[i+1]]
}
