// Code generated by "stringer -linecomment -type ItemLocationType -output location_type_string.go"; DO NOT EDIT.

package d2senums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LocationStored-0]
	_ = x[LocationEquipped-1]
	_ = x[LocationBelt-2]
	_ = x[LocationMoved-4]
	_ = x[LocationInSocket-6]
}

const (
	_ItemLocationType_name_0 = "StoredEquippedin belt"
	_ItemLocationType_name_1 = "moving"
	_ItemLocationType_name_2 = "in socket"
)

var (
	_ItemLocationType_index_0 = [...]uint8{0, 6, 14, 21}
)

func (i ItemLocationType) String() string {
	switch {
	case i <= 2:
		return _ItemLocationType_name_0[_ItemLocationType_index_0[i]:_ItemLocationType_index_0[i+1]]
	case i == 4:
		return _ItemLocationType_name_1
	case i == 6:
		return _ItemLocationType_name_2
	default:
		return "ItemLocationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
