// Code generated by "string2enum -samepkg -type SkillID -linecomment -output skill_id_string2enum.go"; DO NOT EDIT.

package d2senums

import "fmt"

// SkillIDFromString returns the SkillID enum corresponding to s.
func SkillIDFromString(s string) SkillID {
	if len(s) == 0 {
		return 0
	}
	for i := range _SkillID_index_0[:len(_SkillID_index_0)-1] {
		if s == _SkillID_name_0[_SkillID_index_0[i]:_SkillID_index_0[i+1]] {
			return SkillID(i + 0)
		}
	}
	for i := range _SkillID_index_1[:len(_SkillID_index_1)-1] {
		if s == _SkillID_name_1[_SkillID_index_1[i]:_SkillID_index_1[i+1]] {
			return SkillID(i + 369)
		}
	}
	panic(fmt.Errorf("unable to locate SkillID enum corresponding to %q", s))
}

func _(s string) {
	// Check for duplicate string values in type "SkillID".
	switch s {
	// 0
	case "attack":
	// 1
	case "kick":
	// 2
	case "throw":
	// 3
	case "unsummon":
	// 4
	case "left hand throw":
	// 5
	case "left hand swing":
	// 6
	case "magic arrow":
	// 7
	case "fire arrow":
	// 8
	case "inner sight":
	// 9
	case "critical strike":
	// 10
	case "jab":
	// 11
	case "cold arrow":
	// 12
	case "multiple shot":
	// 13
	case "dodge":
	// 14
	case "power strike":
	// 15
	case "poison javelin":
	// 16
	case "exploding arrow":
	// 17
	case "slow missile":
	// 18
	case "avoid":
	// 19
	case "impale":
	// 20
	case "lightning bolt":
	// 21
	case "ice arrow":
	// 22
	case "guided arrow":
	// 23
	case "penetrate":
	// 24
	case "charged strike":
	// 25
	case "plague javelin":
	// 26
	case "strafe":
	// 27
	case "immolation arrow":
	// 28
	case "dopplezon":
	// 29
	case "evade":
	// 30
	case "fend":
	// 31
	case "freezing arrow":
	// 32
	case "valkyrie":
	// 33
	case "pierce":
	// 34
	case "lightning strike":
	// 35
	case "lightning fury":
	// 36
	case "fire bolt":
	// 37
	case "warmth":
	// 38
	case "charged bolt":
	// 39
	case "ice bolt":
	// 40
	case "frozen armor":
	// 41
	case "inferno":
	// 42
	case "static field":
	// 43
	case "telekinesis":
	// 44
	case "frost nova":
	// 45
	case "ice blast":
	// 46
	case "blaze":
	// 47
	case "fire ball":
	// 48
	case "nova":
	// 49
	case "lightning":
	// 50
	case "shiver armor":
	// 51
	case "fire wall":
	// 52
	case "enchant":
	// 53
	case "chain lightning":
	// 54
	case "teleport":
	// 55
	case "glacial spike":
	// 56
	case "meteor":
	// 57
	case "thunder storm":
	// 58
	case "energy shield":
	// 59
	case "blizzard":
	// 60
	case "chilling armor":
	// 61
	case "fire mastery":
	// 62
	case "hydra":
	// 63
	case "lightning mastery":
	// 64
	case "frozen orb":
	// 65
	case "cold mastery":
	// 66
	case "amplify damage":
	// 67
	case "teeth":
	// 68
	case "bone armor":
	// 69
	case "skeleton mastery":
	// 70
	case "raise skeleton":
	// 71
	case "dim vision":
	// 72
	case "weaken":
	// 73
	case "poison dagger":
	// 74
	case "corpse explosion":
	// 75
	case "cly golem":
	// 76
	case "iron maiden":
	// 77
	case "terror":
	// 78
	case "bone wall":
	// 79
	case "golem mastery":
	// 80
	case "raise skeletal mag":
	// 81
	case "confuse":
	// 82
	case "life tap":
	// 83
	case "poison explosion":
	// 84
	case "bone spear":
	// 85
	case "blood golem":
	// 86
	case "attract":
	// 87
	case "decrepify":
	// 88
	case "bone prison":
	// 89
	case "summon resist":
	// 90
	case "iron golem":
	// 91
	case "lower lesist":
	// 92
	case "poison nova":
	// 93
	case "bone spirit":
	// 94
	case "fire golem":
	// 95
	case "revive":
	// 96
	case "sacrifice":
	// 97
	case "smite":
	// 98
	case "might":
	// 99
	case "prayer":
	// 100
	case "resist fire":
	// 101
	case "holy bolt":
	// 102
	case "holy fire":
	// 103
	case "thorne":
	// 104
	case "defiance":
	// 105
	case "resist cold":
	// 106
	case "zeal":
	// 107
	case "charge":
	// 108
	case "blassed aim":
	// 109
	case "concentration":
	// 110
	case "holy freeze":
	// 111
	case "vigor":
	// 112
	case "conversion":
	// 113
	case "holy shield":
	// 114
	case "holy shock":
	// 115
	case "sanctuary":
	// 116
	case "meditation":
	// 117
	case "fist of the Heavens":
	// 118
	case "fanaticism":
	// 119
	case "conviction":
	// 120
	case "redemption":
	// 121
	case "salvation":
	// 122
	case "bash":
	// 123
	case "sword mastery":
	// 124
	case "axe mastery":
	// 125
	case "mace mastery":
	// 126
	case "howl":
	// 127
	case "find potion":
	// 128
	case "leap":
	// 129
	case "double swing":
	// 130
	case "pole arm mastery":
	// 131
	case "throwing mastery":
	// 132
	case "spear mastery":
	// 133
	case "taunt":
	// 134
	case "shout":
	// 135
	case "stum":
	// 136
	case "double throw":
	// 137
	case "increased stamina":
	// 138
	case "find items":
	// 139
	case "leap attack":
	// 140
	case "concentrate":
	// 141
	case "iron skin":
	// 142
	case "battle cry":
	// 143
	case "frenzy":
	// 144
	case "increased speed":
	// 145
	case "battle orders":
	// 146
	case "grim ward":
	// 147
	case "whirlwind":
	// 148
	case "berserk":
	// 149
	case "natural resistance":
	// 150
	case "war cry":
	// 151
	case "battle commands":
	// 369
	case "scroll of identify":
	// 370
	case "tome of identify":
	// 371
	case "scroll of town portal":
	// 372
	case "tome of town portal":
	// 373
	case "raven":
	// 374
	case "plague poppy":
	// 375
	case "warwolf":
	// 376
	case "shape shifting":
	// 377
	case "firestorm":
	// 378
	case "oak sage":
	// 379
	case "summon sprite wolf":
	// 380
	case "wearbear":
	// 381
	case "molten boulder":
	// 382
	case "arctic blast":
	// 383
	case "cycle of life":
	// 384
	case "feral rage":
	// 385
	case "maul":
	// 386
	case "eruption":
	// 387
	case "cyclone armor":
	// 388
	case "heart of wolverine":
	// 389
	case "summon fenris":
	// 390
	case "rabies":
	// 391
	case "fire claws":
	// 392
	case "twister":
	// 393
	case "vines":
	// 394
	case "hunger":
	// 395
	case "shock wave":
	// 396
	case "volcano":
	// 397
	case "tornado":
	// 398
	case "spirit of barbs":
	// 399
	case "summon grizzly":
	// 400
	case "fury":
	// 401
	case "armageddon":
	// 402
	case "hurricane":
	// 403
	case "fire trauma":
	// 404
	case "claw mastery":
	// 405
	case "psychic hammer":
	// 406
	case "tiger strike":
	// 407
	case "dragon talon":
	// 408
	case "shock field":
	// 409
	case "blade sentinel":
	// 410
	case "quickness":
	// 411
	case "fists of fire":
	// 412
	case "dragon claw":
	// 413
	case "charged bolt sentry":
	// 414
	case "weak of fire sentry":
	// 415
	case "weapon block":
	// 416
	case "cloak of shadows":
	// 417
	case "cobra strike":
	// 418
	case "blade fury":
	// 419
	case "fade":
	// 420
	case "shadow warrior":
	// 421
	case "claws of thunder":
	// 422
	case "dragon tail":
	// 423
	case "lightning sentry":
	// 424
	case "inferno sentry":
	// 425
	case "mint blast":
	// 426
	case "blade of ice":
	// 427
	case "dragon fight":
	// 428
	case "death sentry":
	// 429
	case "blade shield":
	// 430
	case "venom":
	// 431
	case "shadow mastery":
	// 432
	case "royal strike":
	}
}
