// Code generated by "string2enum -type SkillID -linecomment -output skill_id_string2enum.go"; DO NOT EDIT.

package d2senums

import "fmt"
import "github.com/gucio321/d2d2s/d2senums"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the string2enum command to generate them again.
	var x [1]struct{}
	_ = x[d2senums.SkillAttack-0]
	_ = x[d2senums.SkillKick-1]
	_ = x[d2senums.SkillThrow-2]
	_ = x[d2senums.SkillUnsummon-3]
	_ = x[d2senums.SkillLHThrow-4]
	_ = x[d2senums.SkillLHSwing-5]
	_ = x[d2senums.SkillAmazonMagicArrow-6]
	_ = x[d2senums.SkillAmazonFireArrow-7]
	_ = x[d2senums.SkillAmazonInnerSight-8]
	_ = x[d2senums.SkillAmazonCriticalStrike-9]
	_ = x[d2senums.SkillAmazonJab-10]
	_ = x[d2senums.SkillAmazonColdArrow-11]
	_ = x[d2senums.SkillAmazonMultipleShot-12]
	_ = x[d2senums.SkillAmazonDodge-13]
	_ = x[d2senums.SkillAmazonPowerStrike-14]
	_ = x[d2senums.SkillAmazonPoisonJavelin-15]
	_ = x[d2senums.SkillAmazonExplodingArrow-16]
	_ = x[d2senums.SkillAmazonSlowMissile-17]
	_ = x[d2senums.SkillAmazonAvoid-18]
	_ = x[d2senums.SkillAmazonImpale-19]
	_ = x[d2senums.SkillAmazonLightningBolt-20]
	_ = x[d2senums.SkillAmazonIceArrow-21]
	_ = x[d2senums.SkillAmazonGuidedArrow-22]
	_ = x[d2senums.SkillAmazonPenetrate-23]
	_ = x[d2senums.SkillAmazonChargedStrike-24]
	_ = x[d2senums.SkillAmazonPlagueJavelin-25]
	_ = x[d2senums.SkillAmazonStrafe-26]
	_ = x[d2senums.SkillAmazonImmolationArrow-27]
	_ = x[d2senums.SkillAmazonDopplezon-28]
	_ = x[d2senums.SkillAmazonEvade-29]
	_ = x[d2senums.SkillAmazonFend-30]
	_ = x[d2senums.SkillAmazonFreezingArrow-31]
	_ = x[d2senums.SkillAmazonValkyrie-32]
	_ = x[d2senums.SkillAmazonPierce-33]
	_ = x[d2senums.SkillAmazonLightningStrike-34]
	_ = x[d2senums.SkillAmazonLightningFury-35]
	_ = x[d2senums.SkillSorceressFireBolt-36]
	_ = x[d2senums.SkillSorceressWarmth-37]
	_ = x[d2senums.SkillSorceressChargedBolt-38]
	_ = x[d2senums.SkillSorceressIceBolt-39]
	_ = x[d2senums.SkillSorceressFrozenArmor-40]
	_ = x[d2senums.SkillSorceressInferno-41]
	_ = x[d2senums.SkillSorceressStaticField-42]
	_ = x[d2senums.SkillSorceressTelekinesis-43]
	_ = x[d2senums.SkillSorceressFrostNova-44]
	_ = x[d2senums.SkillSorceressIceBlast-45]
	_ = x[d2senums.SkillSorceressBlaze-46]
	_ = x[d2senums.SkillSorceressFireBall-47]
	_ = x[d2senums.SkillSorceressNova-48]
	_ = x[d2senums.SkillSorceressLightning-49]
	_ = x[d2senums.SkillSorceressShiverArmor-50]
	_ = x[d2senums.SkillSorceressFireWall-51]
	_ = x[d2senums.SkillSorceressEnchant-52]
	_ = x[d2senums.SkillSorceressChainLightning-53]
	_ = x[d2senums.SkillSorceressTeleport-54]
	_ = x[d2senums.SkillSorceressGlacialSpike-55]
	_ = x[d2senums.SkillSorceressMeteor-56]
	_ = x[d2senums.SkillSorceressThunderStorm-57]
	_ = x[d2senums.SkillSorceressEnergyShield-58]
	_ = x[d2senums.SkillSorceressBlizzard-59]
	_ = x[d2senums.SkillSorceressChillingArmor-60]
	_ = x[d2senums.SkillSorceressFireMastery-61]
	_ = x[d2senums.SkillSorceressHydra-62]
	_ = x[d2senums.SkillSorceressLightningMastery-63]
	_ = x[d2senums.SkillSorceressFrozenOrb-64]
	_ = x[d2senums.SkillSorceressColdMastery-65]
	_ = x[d2senums.SkillNecromancerAmplifyDamage-66]
	_ = x[d2senums.SkillNecromancerTeeth-67]
	_ = x[d2senums.SkillNecromancerBoneArmor-68]
	_ = x[d2senums.SkillNecromancerSkeletonMastery-69]
	_ = x[d2senums.SkillNecromancerRaiseSkeleton-70]
	_ = x[d2senums.SkillNecromancerDimVision-71]
	_ = x[d2senums.SkillNecromancerWeaken-72]
	_ = x[d2senums.SkillNecromancerPoisonDagger-73]
	_ = x[d2senums.SkillNecromancerCorpseExplosion-74]
	_ = x[d2senums.SkillNecromancerClyGolem-75]
	_ = x[d2senums.SkillNecromancerIronMaiden-76]
	_ = x[d2senums.SkillNecromancerTerror-77]
	_ = x[d2senums.SkillNecromancerBoneWall-78]
	_ = x[d2senums.SkillNecromancerGolemMastery-79]
	_ = x[d2senums.SkillNecromancerRaiseSkeletalMag-80]
	_ = x[d2senums.SkillNecromancerConfuse-81]
	_ = x[d2senums.SkillNecromancerLifeTap-82]
	_ = x[d2senums.SkillNecromancerPoisonExplosion-83]
	_ = x[d2senums.SkillNecromancerBoneSpear-84]
	_ = x[d2senums.SkillNecromancerBloodGolem-85]
	_ = x[d2senums.SkillNecromancerAttract-86]
	_ = x[d2senums.SkillNecromancerDecrepify-87]
	_ = x[d2senums.SkillNecromancerBonePrison-88]
	_ = x[d2senums.SkillNecromancerSummonResist-89]
	_ = x[d2senums.SkillNecromancerIronGolem-90]
	_ = x[d2senums.SkillNecromancerLowerResist-91]
	_ = x[d2senums.SkillNecromancerPoisonNova-92]
	_ = x[d2senums.SkillNecromancerBoneSpirit-93]
	_ = x[d2senums.SkillNecromancerFireGolem-94]
	_ = x[d2senums.SkillNecromancerRevive-95]
	_ = x[d2senums.SkillPaladinSacrifice-96]
	_ = x[d2senums.SkillPaladinSmite-97]
	_ = x[d2senums.SkillPaladinMight-98]
	_ = x[d2senums.SkillPaladinPrayer-99]
	_ = x[d2senums.SkillPaladinResistFire-100]
	_ = x[d2senums.SkillPaladinHolyBolt-101]
	_ = x[d2senums.SkillPaladinHolyFire-102]
	_ = x[d2senums.SkillPaladinThorne-103]
	_ = x[d2senums.SkillPaladinDefiance-104]
	_ = x[d2senums.SkillPaladinResistCold-105]
	_ = x[d2senums.SkillPaladinZeal-106]
	_ = x[d2senums.SkillPaladinCharge-107]
	_ = x[d2senums.SkillPaladinBlassedAim-108]
	_ = x[d2senums.SkillPaladinConcentration-109]
	_ = x[d2senums.SkillPaladinHolyFreeze-110]
	_ = x[d2senums.SkillPaladinVigor-111]
	_ = x[d2senums.SkillPaladinConversion-112]
	_ = x[d2senums.SkillPaladinHolyShield-113]
	_ = x[d2senums.SkillPaladinHolyShock-114]
	_ = x[d2senums.SkillPaladinSanctuary-115]
	_ = x[d2senums.SkillPaladinMeditation-116]
	_ = x[d2senums.SkillPaladinFOH-117]
	_ = x[d2senums.SkillPaladinFanaticism-118]
	_ = x[d2senums.SkillPaladinConviction-119]
	_ = x[d2senums.SkillPaladinRedemption-120]
	_ = x[d2senums.SkillPaladinSalvation-121]
	_ = x[d2senums.SkillBarbarianBash-122]
	_ = x[d2senums.SkillBarbarianSwordMastery-123]
	_ = x[d2senums.SkillBarbarianAxeMastery-124]
	_ = x[d2senums.SkillBarbarianMaceMastery-125]
	_ = x[d2senums.SkillBarbarianHowl-126]
	_ = x[d2senums.SkillBarbarianFindPotion-127]
	_ = x[d2senums.SkillBarbarianLeap-128]
	_ = x[d2senums.SkillBarbarianDoubleSwing-129]
	_ = x[d2senums.SkillBarbarianPoleArmMastery-130]
	_ = x[d2senums.SkillBarbarianThrowingMastery-131]
	_ = x[d2senums.SkillBarbarianSpearMastery-132]
	_ = x[d2senums.SkillBarbarianTaunt-133]
	_ = x[d2senums.SkillBarbarianShout-134]
	_ = x[d2senums.SkillBarbarianStum-135]
	_ = x[d2senums.SkillBarbarianDoubleThrow-136]
	_ = x[d2senums.SkillBarbarianIncreasedStamina-137]
	_ = x[d2senums.SkillBarbarianFintItems-138]
	_ = x[d2senums.SkillBarbarianLeapAttack-139]
	_ = x[d2senums.SkillBarbarianConcentrate-140]
	_ = x[d2senums.SkillBarbarianIronSkin-141]
	_ = x[d2senums.SkillBarbarianBattleCry-142]
	_ = x[d2senums.SkillBarbarianFrenzy-143]
	_ = x[d2senums.SkillBarbarianIncreasedSpeed-144]
	_ = x[d2senums.SkillBarbarianBattleOrders-145]
	_ = x[d2senums.SkillBarbarianGrimWard-146]
	_ = x[d2senums.SkillBarbarianWhirlwind-147]
	_ = x[d2senums.SkillBarbarianBerserk-148]
	_ = x[d2senums.SkillBarbarianNaturalResistance-149]
	_ = x[d2senums.SkillBarbarianWarCry-150]
	_ = x[d2senums.SkillBarbarianBattleCommands-151]
}

const _SkillID_name = "attackkickthrowunsummonleft hand throwleft hand swingmagic arrowfire arrowinner sightcritical strikejabcold arrowmultiple shotdodgepower strikepoison javelinexploding arrowslow missileavoidimpalelightning boltice arrowguided arrowpenetratecharged strikeplague javelinstrafeimmolation arrowdopplezonevadefendfreezing arrowvalkyriepiercelightning strikelightning furyfire boltwarmthcharged boltice boltfrozen armorinfernostatic fieldtelekinesisfrost novaice blastblazefire ballnovalightningshiver armorfire wallenchantchain lightningteleportglacial spikemeteorthunder stormenergy shieldblizzardchilling armorfire masteryhydralightning masteryfrozen orbcold masteryamplify damageteethbone armorskeleton masteryraise skeletondim visionweakenpoison daggercorpse explosioncly golemiron maidenterrorbone wallgolem masteryraise skeletal magconfuselife tappoison explosionbone spearblood golemattractdecrepifybone prisonsummon resistiron golemlower lesistpoison novabone spiritfire golemrevivesacrificesmitemightprayerresist fireholy boltholy firethornedefianceresist coldzealchargeblassed aimconcentrationholy freezevigorconversionholy shieldholy shocksanctuarymeditationfist of the Heavensfanaticismconvictionredemptionsalvationbashsword masteryaxe masterymace masteryhowlfind potionleapdouble swingpole arm masterythrowing masteryspear masterytauntshoutstumdouble throwincreased staminafind itemsleap attackconcentrateiron skinbattle cryfrenzyincreased speedbattle ordersgrim wardwhirlwindberserknatural resistancewar crybattle commands"

var _SkillID_index = [...]uint16{0, 6, 10, 15, 23, 38, 53, 64, 74, 85, 100, 103, 113, 126, 131, 143, 157, 172, 184, 189, 195, 209, 218, 230, 239, 253, 267, 273, 289, 298, 303, 307, 321, 329, 335, 351, 365, 374, 380, 392, 400, 412, 419, 431, 442, 452, 461, 466, 475, 479, 488, 500, 509, 516, 531, 539, 552, 558, 571, 584, 592, 606, 618, 623, 640, 650, 662, 676, 681, 691, 707, 721, 731, 737, 750, 766, 775, 786, 792, 801, 814, 832, 839, 847, 863, 873, 884, 891, 900, 911, 924, 934, 946, 957, 968, 978, 984, 993, 998, 1003, 1009, 1020, 1029, 1038, 1044, 1052, 1063, 1067, 1073, 1084, 1097, 1108, 1113, 1123, 1134, 1144, 1153, 1163, 1182, 1192, 1202, 1212, 1221, 1225, 1238, 1249, 1261, 1265, 1276, 1280, 1292, 1308, 1324, 1337, 1342, 1347, 1351, 1363, 1380, 1390, 1401, 1412, 1421, 1431, 1437, 1452, 1465, 1474, 1483, 1490, 1508, 1515, 1530}

// SkillIDFromString returns the SkillID enum corresponding to s.
func SkillIDFromString(s string) d2senums.SkillID {
	if len(s) == 0 {
		return 0
	}
	for i := range _SkillID_index[:len(_SkillID_index)-1] {
		if s == _SkillID_name[_SkillID_index[i]:_SkillID_index[i+1]] {
			return d2senums.SkillID(i)
		}
	}
	panic(fmt.Errorf("unable to locate SkillID enum corresponding to %q", s))
}

func _(s string) {
	// Check for duplicate string values in type "SkillID".
	switch s {
	// 0
	case "attack":
	// 1
	case "kick":
	// 2
	case "throw":
	// 3
	case "unsummon":
	// 4
	case "left hand throw":
	// 5
	case "left hand swing":
	// 6
	case "magic arrow":
	// 7
	case "fire arrow":
	// 8
	case "inner sight":
	// 9
	case "critical strike":
	// 10
	case "jab":
	// 11
	case "cold arrow":
	// 12
	case "multiple shot":
	// 13
	case "dodge":
	// 14
	case "power strike":
	// 15
	case "poison javelin":
	// 16
	case "exploding arrow":
	// 17
	case "slow missile":
	// 18
	case "avoid":
	// 19
	case "impale":
	// 20
	case "lightning bolt":
	// 21
	case "ice arrow":
	// 22
	case "guided arrow":
	// 23
	case "penetrate":
	// 24
	case "charged strike":
	// 25
	case "plague javelin":
	// 26
	case "strafe":
	// 27
	case "immolation arrow":
	// 28
	case "dopplezon":
	// 29
	case "evade":
	// 30
	case "fend":
	// 31
	case "freezing arrow":
	// 32
	case "valkyrie":
	// 33
	case "pierce":
	// 34
	case "lightning strike":
	// 35
	case "lightning fury":
	// 36
	case "fire bolt":
	// 37
	case "warmth":
	// 38
	case "charged bolt":
	// 39
	case "ice bolt":
	// 40
	case "frozen armor":
	// 41
	case "inferno":
	// 42
	case "static field":
	// 43
	case "telekinesis":
	// 44
	case "frost nova":
	// 45
	case "ice blast":
	// 46
	case "blaze":
	// 47
	case "fire ball":
	// 48
	case "nova":
	// 49
	case "lightning":
	// 50
	case "shiver armor":
	// 51
	case "fire wall":
	// 52
	case "enchant":
	// 53
	case "chain lightning":
	// 54
	case "teleport":
	// 55
	case "glacial spike":
	// 56
	case "meteor":
	// 57
	case "thunder storm":
	// 58
	case "energy shield":
	// 59
	case "blizzard":
	// 60
	case "chilling armor":
	// 61
	case "fire mastery":
	// 62
	case "hydra":
	// 63
	case "lightning mastery":
	// 64
	case "frozen orb":
	// 65
	case "cold mastery":
	// 66
	case "amplify damage":
	// 67
	case "teeth":
	// 68
	case "bone armor":
	// 69
	case "skeleton mastery":
	// 70
	case "raise skeleton":
	// 71
	case "dim vision":
	// 72
	case "weaken":
	// 73
	case "poison dagger":
	// 74
	case "corpse explosion":
	// 75
	case "cly golem":
	// 76
	case "iron maiden":
	// 77
	case "terror":
	// 78
	case "bone wall":
	// 79
	case "golem mastery":
	// 80
	case "raise skeletal mag":
	// 81
	case "confuse":
	// 82
	case "life tap":
	// 83
	case "poison explosion":
	// 84
	case "bone spear":
	// 85
	case "blood golem":
	// 86
	case "attract":
	// 87
	case "decrepify":
	// 88
	case "bone prison":
	// 89
	case "summon resist":
	// 90
	case "iron golem":
	// 91
	case "lower lesist":
	// 92
	case "poison nova":
	// 93
	case "bone spirit":
	// 94
	case "fire golem":
	// 95
	case "revive":
	// 96
	case "sacrifice":
	// 97
	case "smite":
	// 98
	case "might":
	// 99
	case "prayer":
	// 100
	case "resist fire":
	// 101
	case "holy bolt":
	// 102
	case "holy fire":
	// 103
	case "thorne":
	// 104
	case "defiance":
	// 105
	case "resist cold":
	// 106
	case "zeal":
	// 107
	case "charge":
	// 108
	case "blassed aim":
	// 109
	case "concentration":
	// 110
	case "holy freeze":
	// 111
	case "vigor":
	// 112
	case "conversion":
	// 113
	case "holy shield":
	// 114
	case "holy shock":
	// 115
	case "sanctuary":
	// 116
	case "meditation":
	// 117
	case "fist of the Heavens":
	// 118
	case "fanaticism":
	// 119
	case "conviction":
	// 120
	case "redemption":
	// 121
	case "salvation":
	// 122
	case "bash":
	// 123
	case "sword mastery":
	// 124
	case "axe mastery":
	// 125
	case "mace mastery":
	// 126
	case "howl":
	// 127
	case "find potion":
	// 128
	case "leap":
	// 129
	case "double swing":
	// 130
	case "pole arm mastery":
	// 131
	case "throwing mastery":
	// 132
	case "spear mastery":
	// 133
	case "taunt":
	// 134
	case "shout":
	// 135
	case "stum":
	// 136
	case "double throw":
	// 137
	case "increased stamina":
	// 138
	case "find items":
	// 139
	case "leap attack":
	// 140
	case "concentrate":
	// 141
	case "iron skin":
	// 142
	case "battle cry":
	// 143
	case "frenzy":
	// 144
	case "increased speed":
	// 145
	case "battle orders":
	// 146
	case "grim ward":
	// 147
	case "whirlwind":
	// 148
	case "berserk":
	// 149
	case "natural resistance":
	// 150
	case "war cry":
	// 151
	case "battle commands":
	}
}
