// Code generated by "stringer -linecomment -type MercClass -output mercenary_class_string.go"; DO NOT EDIT.

package d2smercenarytype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MercRogue-0]
	_ = x[MercDesert-1]
	_ = x[MercSorcerer-2]
	_ = x[MercBarbarian-3]
}

const _MercClass_name = "Rogue ScoutDesert MercenaryEastern SorcererBarbarian"

var _MercClass_index = [...]uint8{0, 11, 27, 43, 52}

func (i MercClass) String() string {
	if i >= MercClass(len(_MercClass_index)-1) {
		return "MercClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MercClass_name[_MercClass_index[i]:_MercClass_index[i+1]]
}
