// Code generated by "stringer -linecomment -type MercAttribute -output mercenary_attribute_string.go"; DO NOT EDIT.

package d2smercenarytype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MercAttributeFireArrow-0]
	_ = x[MercAttributeColdArrow-1]
	_ = x[MercAttributeCombat-2]
	_ = x[MercAttributeDefensive-3]
	_ = x[MercAttributeOffensive-4]
	_ = x[MercAttributeFire-5]
	_ = x[MercAttributeCold-6]
	_ = x[MercAttributeLightning-7]
	_ = x[MercAttributeBarb1-8]
	_ = x[MercAttributeBarb2-9]
}

const _MercAttribute_name = "Fire ArrowColdArrowCombatDevensiveOffensiveFire SpellsCold SpellsLightning Spells"

var _MercAttribute_index = [...]uint8{0, 10, 19, 25, 34, 43, 54, 65, 81, 81, 81}

func (i MercAttribute) String() string {
	if i >= MercAttribute(len(_MercAttribute_index)-1) {
		return "MercAttribute(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MercAttribute_name[_MercAttribute_index[i]:_MercAttribute_index[i+1]]
}
