package itemdata

//go:generate stringer -linecomment -type ItemCode -output item_code_string.go
//go:generate string2enum -samepkg -linecomment -type ItemCode -output item_code_string2enum.go

// ItemCode represents an items codes
type ItemCode uint16

// Item code value constant used as an internal reference or ID.
const (
	ItemCodeNotFound ItemCode = iota
	// Armor
	AlphaHelm         // dr6
	AncientArmor      // aar
	Antlers           // dr3
	ArchonPlate       // utp
	Armet             // ulm
	AssaultHelmet     // ba4
	AvengerGuard      // ba5
	BalrogSkin        // upl
	Basinet           // xhl
	BattleBelt        // ztb
	BattleBoots       // xtb
	BattleGauntlets   // xtg
	Belt              // mbl
	BloodSpirit       // drb
	BoneHelm          // bhm
	BoneVisage        // uh9
	Boneweave         // uhn
	BoneweaveBoots    // umb
	Bracers           // mgl
	BrambleMitts      // ulg
	BreastPlate       // brs
	Cap               // cap
	CarnageHelm       // bab
	Casque            // xlm
	ChainBoots        // mbt
	ChainMail         // chn
	ChaosArmor        // xul
	Circlet           // ci0
	ColossusGirdle    // uhc
	ConquerorCrown    // bae
	Corona            // urn
	Coronet           // ci1
	Crown             // crn
	CrusaderGauntlets // utg
	Cuirass           // xrs
	DeathMask         // xsk
	Demonhead         // usk
	DemonhideArmor    // xla
	DemonhideBoots    // xlb
	DemonhideGloves   // xlg
	DemonhideSash     // zlb
	DestroyerHelm     // bad
	Diadem            // ci3
	DiamondMail       // ung
	DreamSpirit       // drf
	DuskShroud        // uui
	EarthSpirit       // drd
	EmbossedPlate     // xth
	FalconMask        // dr4
	FangedHelm        // ba2
	FieldPlate        // fld
	FullHelm          // fhl
	PlateMail         // plt
	FullPlateMail     // ful
	FuryVisor         // bac
	Gauntlets         // hgl
	GhostArmor        // xui
	GiantConch        // uhl
	Girdle            // hbl
	Gloves            // lgl
	GothicPlate       // gth
	GrandCrown        // xrn
	GreatHauberk      // urs
	GreatHelm         // ghm
	GriffonHeadress   // dr7
	GrimHelm          // xh9
	GuardianCrown     // baf
	HardLeatherArmor  // hla
	HawkHelm          // dr2
	HeavyBelt         // tbl
	HeavyBoots        // vbt
	HeavyBracers      // xmg
	HeavyGloves       // vgl
	HellforgedPlate   // ult
	Helm              // hlm
	HornedHelm        // ba3
	HuntersGuise      // dr8
	Hydraskull        // ukp
	Hyperion          // urg
	JawboneCap        // ba1
	JawboneVisor      // ba6
	KrakenShell       // uld
	LacqueredPlate    // uth
	LeatherArmor      // lea
	LeatherBoots      // lbt
	LightBelt         // vbl
	LightGauntlets    // tgl
	LightPlate        // ltp
	LightPlatedBoots  // tbt
	LinkedMail        // xng
	LionHelm          // ba7
	LoricatedMail     // ucl
	MagePlate         // xtp
	Mask              // msk
	MeshArmor         // xhn
	MeshBelt          // zmb
	MeshBoots         // xmb
	MirroredBoots     // utb
	MithrilCoil       // umc
	MyrmidonGreaves   // uhb
	OgreGauntlets     // uhg
	OrnatePlate       // xar
	PlateBoots        // hbt
	QuiltedArmor      // qui
	RageMask          // ba8
	RingMail          // rng
	RussetArmor       // xpl
	SacredArmor       // uar
	SacredFeathers    // dr9
	Sallet            // xkp
	Sash              // lbl
	SavageHelmet      // ba9
	ScaleMail         // scl
	ScarabHusk        // ula
	ScarabshellBoots  // uvb
	SerpentskinArmor  // xea
	ShadowPlate       // uul
	Shako             // uap
	SharkskinBelt     // zvb
	SharkskinBoots    // xvb
	SharkskinGloves   // xvg
	SharktoothArmor   // xld
	SkullCap          // skp
	SkySpirit         // dre
	SlayerGuard       // baa
	SpiderwebSash     // ulc
	SpiredHelm        // uhm
	SpiritMask        // dr5
	SplintMail        // spl
	StuddedLeather    // stu
	SunSpirit         // drc
	TemplarCoat       // xlt
	Tiara             // ci2
	TigulatedMail     // xcl
	TotemicMask       // dra
	TrellisedArmor    // xtu
	TrollBelt         // utc
	Vambraces         // umg
	VampireboneGloves // uvg
	VampirefangBelt   // uvc
	WarBelt           // zhb
	WarBoots          // xhb
	WarGauntlets      // xhg
	WarHat            // xap
	WingedHelm        // xhm
	WireFleece        // utu
	WolfHead          // dr1
	Wyrmhide          // uea
	WyrmhideBoots     // ulb

	// Misc
	Amethyst                      // gsv
	AmnRune                       // r11
	Amulet                        // amu
	AntidotePotion                // yps
	Arrows                        // aqv
	BaalsEye                      // bey
	BarkScroll                    // bks
	BerRune                       // r30
	Bolts                         // cqv
	BookofSkill                   // ass
	BurningEssenceofTerror        // bet
	ChamRune                      // r32
	ChargedEssenceofHatred        // ceh
	GrandCharm                    // cm3
	LargeCharm                    // cm2
	SmallCharm                    // cm1
	ChippedAmethyst               // gcv
	ChippedDiamond                // gcw
	ChippedEmerald                // gcg
	ChippedRuby                   // gcr
	ChippedSapphire               // gcb
	ChippedSkull                  // skc
	ChippedTopaz                  // gcy
	DecipheredBarkScroll          // bkd
	DiablosHorn                   // dhn
	Diamond                       // gsw
	DolRune                       // r14
	ElRune                        // r01
	EldRune                       // r02
	Elixir                        // elx
	Emerald                       // gsg
	EthRune                       // r05
	FalRune                       // r19
	FesteringEssenceofDestruction // fed
	FlawedAmethyst                // gfv
	FlawedDiamond                 // gfw
	FlawedEmerald                 // gfg
	FlawedRuby                    // gfr
	FlawedSapphire                // gfb
	FlawedSkull                   // skf
	FlawedTopaz                   // gfy
	FlawlessAmethyst              // gzv
	FlawlessDiamond               // glw
	FlawlessEmerald               // glg
	FlawlessRuby                  // glr
	FlawlessSapphire              // glb
	FlawlessSkull                 // skl
	FlawlessTopaz                 // gly
	FullHealingPotion             // hpf
	FullManaPotion                // mpf
	FullRejuvenationPotion        // rvl
	Gold                          // gld
	GoldBird                      // g34
	GreaterHealingPotion          // hp5
	GreaterManaPotion             // mp5
	GulRune                       // r25
	HealingPotion                 // hp3
	HealingPotionMid              // hpo
	HelRune                       // r15
	Herb                          // hrb
	HoradricCube                  // box
	IdentifyBook                  // ibk
	IdentifyScroll                // isc
	IoRune                        // r16
	IstRune                       // r24
	IthRune                       // r06
	JadeFigurine                  // j34
	JahRune                       // r31
	Jewel                         // jew
	KeyofDestruction              // pk3
	KeyofHate                     // pk2
	KeyofTerror                   // pk1
	KhalimsBrain                  // qbr
	KhalimsEye                    // qey
	KhalimsHeart                  // qhr
	KoRune                        // r18
	LamEsensTome                  // bbb
	LargeBluePotion               // bpl
	LargeRedPotion                // rpl
	LemRune                       // r20
	LesserHealingPotion           // hp1
	LesserManaPotion              // mp1
	LightHealingPotion            // hp2
	LightManaPotion               // mp2
	LoRune                        // r28
	LumRune                       // r17
	Maguffin                      // ice
	MalRune                       // r23
	ManaPotion                    // mp3
	ManaPotionMid                 // mpo
	MephistosBrain                // mbr
	MephistoKey                   // luv
	MephistoSoulStone             // mss
	NefRune                       // r04
	OhmRune                       // r27
	OrtRune                       // r09
	PerfectAmethyst               // gpv
	PerfectDiamond                // gpw
	PerfectEmerald                // gpg
	PerfectRuby                   // gpr
	PerfectSapphire               // gpb
	PerfectSkull                  // skz
	PerfectTopaz                  // gpy
	PlayerEar                     // ear
	PulRune                       // r21
	RalRune                       // r08
	RejuvenationPotion            // rvs
	Ring                          // rin
	Ruby                          // gsr
	Sapphire                      // gsb
	Scroll                        // 0sc
	ScrollofHoradric              // tr1
	ScrollofMalah                 // tr2
	PotionofLife                  // xyz
	ShaelRune                     // r13
	SkeletonKey                   // key
	Skull                         // sku
	SmallBluePotion               // bps
	SmallRedPotion                // rps
	SolRune                       // r12
	StaminaPotion                 // vps
	StandardofHeroes              // std
	StrongHealingPotion           // hp4
	StrongManaPotion              // mp4
	SurRune                       // r29
	TalRune                       // r07
	ThawingPotion                 // wms
	ThulRune                      // r10
	TirRune                       // r03
	TokenofAbsolution             // toa
	Topaz                         // gsy
	Torch                         // tch
	TownPortalBook                // tbk
	TownPortalScroll              // tsc
	TwistedEssenceofSuffering     // tes
	UmRune                        // r22
	VexRune                       // r26
	ViperAmulet                   // vip
	ZodRune                       // r33

	// Shields
	Aegis            // uow
	AerinShield      // pa4
	AkaranRondache   // pa7
	AkaranTarge      // pa6
	KurastShield     // pad
	AncientShield    // xts
	BarbedShield     // xpk
	BladeBarrier     // upk
	BloodlordSkull   // nef
	BoneShield       // bsh
	Buckler          // buc
	CantorTrophy     // ne9
	CrownShield      // pa5
	Defender         // xuc
	DemonHead        // ne5
	DragonShield     // xit
	FetishTrophy     // ne7
	GargoyleHead     // ne4
	GothicShield     // gts
	GrimShield       // xsh
	GildedShield     // pa9
	HeirophantTrophy // nea
	Heater           // uuc
	HellspawnSkull   // neg
	HeraldicShield   // pa3
	KiteShield       // kit
	LargeShield      // lrg
	Luna             // uml
	MinionSkull      // neb
	Monarch          // uit
	MummifiedTrophy  // ne6
	OverseerSkull    // ned
	Pavise           // xow
	PreservedHead    // ne1
	ProtectorShield  // pa8
	Rondache         // pa2
	RoundShield      // xml
	RoyalShield      // paa
	SacredRondache   // pac
	SacredTarge      // pab
	Scutum           // xrg
	SextonTrophy     // ne8
	SmallShield      // sml
	SpikedShield     // spk
	SuccubusSkull    // nee
	Targe            // pa1
	TowerShield      // tow
	TrollNest        // ush
	UnravellerHead   // ne3
	VortexShield     // paf
	Ward             // uts
	ZakarumShield    // pae
	ZombieHead       // ne2

	// Weapons
	AncientAxe          // 9gi
	AncientSword        // 9wd
	Arbalest            // 8lx
	ArchonStaff         // 6ws
	AshwoodBow          // am6
	Ataghan             // 7sm
	Axe                 // axe
	BalancedAxe         // bal
	BalancedKnife       // bkf
	Balista             // 8hx
	BalrogBlade         // 7gs
	BalrogSpear         // 7s7
	BarbedClub          // 9sp
	Bardiche            // bar
	BastardSword        // bsw
	BattleAxe           // btx
	BattleCestus        // 7cs
	BattleDart          // 9tk
	BattleHammer        // 9wh
	BattleScythe        // 9s8
	BattleStaff         // bst
	BattleSword         // 9bs
	BeardedAxe          // 9ba
	BecDeCorbin         // 9h9
	BerserkerAxe        // 7wa
	Bill                // 9vo
	Blade               // bld
	BladeBow            // 6hb
	BladeTalons         // btl
	BoneKnife           // 7dg
	BoneWand            // bwn
	Brandistock         // brn
	BroadAxe            // bax
	BroadSword          // bsd
	BurntWand           // 9wn
	Caduceus            // 7ws
	CedarBow            // 8lb
	CedarStaff          // 8cs
	CeremonialBow       // am7
	CeremonialJavelin   // ama
	CeremonialPike      // am9
	CeremonialSpear     // am8
	Cestus              // ces
	ChampionAxe         // 7ga
	ChampionSword       // 7b7
	ChokingGasPotion    // gpm
	ChuKoNu             // 8rx
	Cinquedeas          // 9kr
	ClaspedOrb          // ob4
	Claws               // clw
	Claymore            // clm
	Cleaver             // 9ax
	CloudySphere        // ob8
	Club                // clb
	ColossalSword       // 7fb
	ColossalBlade       // 7gd
	ColossusCrossbow    // 6hx
	ColossusVoulge      // 7vo
	CompositeBow        // cbw
	ConquestSword       // 7bs
	Crossbow            // mxb
	Crowbill            // 9mp
	CrusaderBow         // 6l7
	CrypticAxe          // 7pa
	CrypticSword        // 7ls
	CrystalSword        // crs
	CrystallineGlobe    // ob7
	Cudgel              // 9cl
	Cutlass             // 9sm
	DacianFalx          // 9cm
	Dagger              // dgr
	Decapitator         // 7bt
	DecoyDagger         // d33
	DemonCrossbow       // 6rx
	DemonHeart          // obd
	DevilStar           // 7mt
	DiamondBow          // 6s7
	DimensionalBlade    // 9cr
	DimensionalShard    // obf
	Dirk                // dir
	DivineScepter       // 9ws
	DoubleAxe           // 2ax
	DoubleBow           // 8cb
	DragonStone         // ob5
	EableOrb            // ob1
	EdgeBow             // 8sb
	ElderStaff          // 6cs
	EldritchOrb         // obc
	ElegantBlade        // 7sb
	Espadon             // 92h
	EttinAxe            // 72a
	ExecutionerSword    // 9gd
	ExplodingPotion     // opm
	Falcata             // 7ss
	Falchion            // flc
	FangedKnife         // 7kr
	Fascia              // 9xf
	FeralAxe            // 7la
	FeralClaws          // 7lw
	Flail               // fla
	Flamberge           // flb
	FlangedMace         // 9ma
	FlyingAxe           // 7ta
	FlyingKnife         // 7tk
	Francisca           // 9ta
	FulmatingPotion     // opl
	Fuscina             // 9tr
	GhostGlaive         // 7gl
	GhostSpear          // 7st
	GhostWand           // 7yw
	GiantAxe            // gix
	GiantSword          // gis
	GiantThresher       // 7wc
	Gidbinn             // g33
	Gladius             // 9ss
	Glaive              // glv
	GloriousAxe         // 7gi
	GlowingOrb          // ob6
	GnarledStaff        // cst
	GorgonCrossbow      // 6mx
	GothicAxe           // 9ga
	GothicBow           // 8lw
	GothicStaff         // 8bs
	GothicSword         // 9b9
	GrandMatronBow      // amc
	GrandScepter        // gsc
	GraveWand           // 9gw
	GreatAxe            // gax
	GreatBow            // 6cb
	GreatMaul           // gma
	GreatPilum          // 9pi
	GreatPoleaxe        // 7h7
	GreatSword          // gsd
	GreaterClaws        // 9lw
	GreaterTalons       // 9tw
	GrimScythe          // 9wc
	GrimWand            // gwn
	Halberd             // hal
	HandAxe             // hax
	HandScythe          // 9cs
	Harpoon             // 9ts
	Hatchet             // 9ha
	HatchetHands        // axf
	HeavenlyStone       // obb
	HeavyCrossbow       // hxb
	HellforgeHammer     // hfh
	HighlandBlade       // 7cm
	HolyWaterSprinkler  // 9qs
	HoradricMalus       // hdm
	HoradricStaff       // hst
	HuntersBow          // hbw
	Hurlbat             // 9b8
	HydraBow            // 6lw
	HydraEdge           // 7fc
	HyperionJavelin     // 7ja
	HyperionSpear       // 7sr
	JaggedStar          // 9mt
	Javelin             // jav
	JoStaff             // 8ss
	Katar               // ktr
	KhalimFlail         // qf1
	Knout               // 9fl
	Kriss               // kri
	Lance               // 9p9
	LargeAxe            // lax
	LegendSpike         // 7bl
	LegendSword         // 72h
	LegendaryMallet     // 7wh
	LichWand            // 7bw
	LightCrossbow       // lxb
	LochaberAxe         // 9b7
	LongBattleBow       // lbb
	LongBow             // lbw
	LongSiegeBow        // 8l8
	LongStaff           // lst
	LongSword           // lsd
	LongWarBow          // lwb
	Mace                // mac
	MaidenJavelin       // am5
	MaidenPike          // am4
	MaidenSpear         // am3
	Mancatcher          // 7br
	MarteldeFer         // 9gm
	MatriarchalBow      // amb
	MatriarchalPike     // ame
	MatriarchalSpear    // amd
	MatriarchalJavelin  // amf
	Maul                // mau
	MightyScepter       // 7sc
	MilitaryAxe         // 9la
	MilitaryPick        // mpi
	MithralPoint        // 7di
	MorningStar         // mst
	MythicalSword       // 7wd
	Naga                // 9wa
	OgreAxe             // 7o7
	OgreMaul            // 7m7
	OilPotion           // ops
	Partizan            // 9pa
	PelletBow           // 6lx
	PetrifiedWand       // 9yw
	PhaseBlade          // 7cr
	Pike                // pik
	Pilum               // pil
	Poignard            // 9dg
	Poleaxe             // pax
	PolishedWand        // 7wn
	QuarterStaff        // 8ls
	Quhab               // 9ar
	RancidGasPotion     // gps
	RazorBow            // 8hb
	ReflexBow           // am2
	ReinforcedMace      // 7ma
	RepeatingCrossbow   // rxb
	Rondel              // 9di
	RuneBow             // 8sw
	RuneScepter         // 9sc
	RuneStaff           // 8ws
	RuneSword           // 9ls
	RunicTalons         // 7tw
	Sabre               // sbr
	SacredGlobe         // ob2
	Scepter             // scp
	Scimitar            // scm
	ScissorsKatar       // skr
	ScissorsQuhab       // 9qr
	ScissorsSuwayyah    // 7qr
	Scourge             // 7fl
	Scythe              // scy
	SeraphRod           // 7qs
	ShadowBow           // 6lb
	Shamshir            // 9sb
	Shillelah           // 6bs
	ShortBattleBow      // sbb
	ShortBow            // sbw
	ShortSiegeBow       // 8s8
	ShortSpear          // ssp
	ShortStaff          // sst
	ShortSword          // ssd
	ShortWarBow         // swb
	SiegeCrossbow       // 8mx
	SilverEdgedAxe      // 7ba
	Simbilan            // 9s9
	SmallCrescent       // 7ax
	SmokedSphere        // ob3
	SparklingBall       // ob9
	Spear               // spr
	Spetum              // spt
	Spiculum            // 9gl
	SpiderBow           // 6sb
	SpikedClub          // spc
	StaffOfTheKings     // msf
	StagBow             // am1
	Stalagmite          // 6ls
	Stilleto            // 9bl
	StranglingGasPotion // gpl
	StygianPike         // 7tr
	StygianPilum        // 7pi
	SuperKhalimFlail    // qf2
	Suwayyah            // 7ar
	SwirlingCrystal     // oba
	Tabar               // 9bt
	Thresher            // 7s8
	ThrowingAxe         // tax
	ThrowingKnife       // tkf
	ThrowingSpear       // tsp
	ThunderMaul         // 7gm
	Tomahawk            // 7ha
	TombWand            // 9bw
	Trident             // tri
	Truncheon           // 7cl
	Tulwar              // 9fc
	TuskSword           // 9gs
	TwinAxe             // 92a
	TwoHandedSword      // 2hs
	TyrantClub          // 7sp
	UnearthedWand       // 7gw
	VortexOrb           // obe
	Voulge              // vou
	WalkingStick        // 6ss
	Wand                // wnd
	WarAxe              // wax
	WarClub             // 9m9
	WarDart             // 9bk
	WarFist             // 7xf
	WarFork             // 9br
	WarHammer           // whm
	WarJavelin          // 9ja
	WarPike             // 7p7
	WarScepter          // wsp
	WarScythe           // wsc
	WarSpear            // 9sr
	WarSpike            // 7mp
	WarStaff            // wst
	WarSword            // wsd
	WardBow             // 6sw
	WingedAxe           // 7b8
	WingedHarpoon       // 7ts
	WingedKnife         // 7bk
	WirtsLeg            // leg
	WristBlade          // wrb
	WristSpike          // 9wb
	WristSword          // 7wb
	Yari                // 9st
	YewWand             // ywn
	Zweihander          // 9fb
)
