package itemdata

//go:generate stringer -linecomment -type RareName -output rare_string.go

// RareName represents a rare name
type RareName uint16

// rare names
const (
	RareBite       RareName = iota + 1 // Bite
	RareScratch                        // Scratch
	RareScalpel                        // Scalpel
	RareFang                           // Fang
	RareGutter                         // Gutter
	RareThirst                         // Thirst
	RareRazor                          // Razor
	RareScythe                         // Scythe
	RareEdge                           // Edge
	RareSaw                            // Saw
	RareSplitter                       // Splitter
	RareCleaver                        // Cleaver
	RareSever                          // Sever
	RareSunder                         // Sunder
	RareRend                           // Rend
	RareMangler                        // Mangler
	RareSlayer                         // Slayer
	RareReaver                         // Reaver
	RareSpawn                          // Spawn
	RareGnash                          // Gnash
	RareStar                           // Star
	RareBlow                           // Blow
	RareSmasher                        // Smasher
	RareBane                           // Bane
	RareCrusher                        // Crusher
	RareBreaker                        // Breaker
	RareGrinder                        // Grinder
	RareCrack                          // Crack
	RareMallet                         // Mallet
	RareKnell                          // Knell
	RareLance                          // Lance
	RareSpike                          // Spike
	RareImpaler                        // Impaler
	RareSkewer                         // Skewer
	RareProd                           // Prod
	RareScourge                        // Scourge
	RareWand                           // Wand
	RareWrack                          // Wrack
	RareBarb                           // Barb
	RareNeedle                         // Needle
	RareDart                           // Dart
	RareBolt                           // Bolt
	RareQuarrel                        // Quarrel
	RareFletch                         // Fletch
	RareFlight                         // Flight
	RareNock                           // Nock
	RareHorn                           // Horn
	RareStinger                        // Stinger
	RareQuill                          // Quill
	RareGoad                           // Goad
	RareBranch                         // Branch
	RareSpire                          // Spire
	RareSong                           // Song
	RareCall                           // Call
	RareCry                            // Cry
	RareSpall                          // Spell
	RareChant                          // Chant
	RareWeaver                         // Weaver
	RareGnarl                          // Gnarl
	RareVisage                         // Visage
	RareCrest                          // Crest
	RareCirclet                        // Circlet
	RareVeil                           // Veil
	RareHood                           // Hood
	RareMask                           // Mask
	RareBrow                           // Brow
	RareCasque                         // Casque
	RareVisor                          // Visor
	RareCowl                           // Cowl
	RareHide                           // Hide
	RarePelt                           // Pelt
	RareCarapace                       // Carapace
	RareCoat                           // Coat
	RareWrap                           // Wrap
	RareSuit                           // Suit
	RareCloak                          // Cloak
	RareShroud                         // Shroud
	RareJack                           // Jack
	RareMantle                         // Mantle
	RareGuard                          // Guard
	RareBadge                          // Badge
	RareRock                           // Rock
	RareAegis                          // Aegis
	RareWard                           // Ward
	RareTower                          // Tower
	RareShield                         // Shield
	RareWing                           // Wing
	RareMark                           // Mark
	RareEmblem                         // Emblem
	RareHand                           // Hand
	RareFist                           // Fist
	RareClaw                           // Claw
	RareClutches                       // Clutches
	RareGrip                           // Grip
	RareGrasp                          // Grasp
	RareGold                           // Hold
	RareTorch                          // Torch
	RareFinger                         // Finger
	RareKnuckle                        // Knuckle
	RareShank                          // Shank
	RareSpur                           // Spur
	RareTread                          // Tread
	RareStalker                        // Stalker
	RareGreave                         // Greave
	RareBlazer                         // Blazer
	RareNails                          // Nails
	RareTrample                        // Trample
	RareBrogues                        // Brogues
	RareTrack                          // Track
	RareSlippers                       // Slippers
	RareClasp                          // Clasp
	RareBuckle                         // Buckle
	RareGarness                        // Harness
	RareLock                           // Lock
	RareFringe                         // Fringe
	RareWinding                        // Winding
	RareChain                          // Chain
	RareStrap                          // Strap
	RareLash                           // Lash
	RareCord                           // Cord
	RareKnot                           // Knot
	RareCircle                         // Circle
	RareLoop                           // Loop
	RareEye                            // Eye
	RareTurn                           // Turn
	RareSpiral                         // Spiral
	RareCoil                           // Coil
	RareGyre                           // Gyre
	RareBand                           // Band
	RareWhorl                          // Whorl
	RareTalisman                       // Talisman
	RareHeart                          // Heart
	RareNoose                          // Noose
	RareNecklace                       // Necklace
	RareCollar                         // Collar
	RareBeads                          // Beads
	RareTorc                           // Torc
	RareGorget                         // Gorget
	RareScarab                         // Scarab
	RareWood                           // Wood
	RareBrand                          // Brand
	RareBludgeon                       // Bludgeon
	RareCudgel                         // Cudgel
	RareLoom                           // Loom
	RareHarp                           // Harp
	RareMaster                         // Master
	RareBarl                           // Barl
	RareHew                            // Hew
	RareCrook                          // Crook
	RareMar                            // Mar
	RareShell                          // Shell
	RareStake                          // Stake
	RarePicket                         // Picket
	RarePale                           // Pale
	RareFlange                         // Flange
	RareBeast                          // Beast
	RareEagle                          // Eagle
	RareRaven                          // Raven
	RareViper                          // Viper
	RareGhoul                          // Ghoul
	RareSkull                          // Skull
	RareBlood                          // Blood
	RareDread                          // Dread
	RareDoom                           // Doom
	RareGrim                           // Grim
	RareBone                           // Bone
	RareDeath                          // Death
	RareShadow                         // Shadow
	RareStorm1                         // Storm
	RareRune                           // Rune
	RarePlague                         // Plague
	RareStone                          // Stone
	RareWraith                         // Wraith
	RareSpirit                         // Spirit
	RareStorm2                         // Storm
	RareDemon                          // Demon
	RareCruel                          // Cruel
	RareEmpyrion                       // Empyrion
	RareBramble                        // Bramble
	RarePain                           // Pain
	RareLoath                          // Loath
	RareGlyph                          // Glyph
	RareImp                            // Imp
	RareFiendra                        // Fiendra
	RareHailstone                      // Hailstone
	RareGale                           // Gale
	RareDire                           // Dire
	RareSoul                           // Soul
	RareBrimstone                      // Brimstone
	RareCorpse                         // Corpse
	RareCarrion                        // Carrion
	RareArmageddon                     // Armageddon
	RareHavoc                          // Havoc
	RareBitter                         // Bitter
	RareEntropy                        // Entropy
	RareChaos                          // Chaos
	RareOrder                          // Order
	RareRule                           // Rule
	RareWarp                           // Warp
	RareRift                           // Rift
	RareCorruption                     // Corruption
)
