package itemdata

//go:generate stringer -linecomment -type RareName -output rare_string.go

// RareName represents a rare name
type RareName uint16

// rare names
const (
	RareNameBite       RareName = iota + 1 // Bite
	RareNameScratch                        // Scratch
	RareNameScalpel                        // Scalpel
	RareNameFang                           // Fang
	RareNameGutter                         // Gutter
	RareNameThirst                         // Thirst
	RareNameRazor                          // Razor
	RareNameScythe                         // Scythe
	RareNameEdge                           // Edge
	RareNameSaw                            // Saw
	RareNameSplitter                       // Splitter
	RareNameCleaver                        // Cleaver
	RareNameSever                          // Sever
	RareNameSunder                         // Sunder
	RareNameRend                           // Rend
	RareNameMangler                        // Mangler
	RareNameSlayer                         // Slayer
	RareNameReaver                         // Reaver
	RareNameSpawn                          // Spawn
	RareNameGnash                          // Gnash
	RareNameStar                           // Star
	RareNameBlow                           // Blow
	RareNameSmasher                        // Smasher
	RareNameBane                           // Bane
	RareNameCrusher                        // Crusher
	RareNameBreaker                        // Breaker
	RareNameGrinder                        // Grinder
	RareNameCrack                          // Crack
	RareNameMallet                         // Mallet
	RareNameKnell                          // Knell
	RareNameLance                          // Lance
	RareNameSpike                          // Spike
	RareNameImpaler                        // Impaler
	RareNameSkewer                         // Skewer
	RareNameProd                           // Prod
	RareNameScourge                        // Scourge
	RareNameWand                           // Wand
	RareNameWrack                          // Wrack
	RareNameBarb                           // Barb
	RareNameNeedle                         // Needle
	RareNameDart                           // Dart
	RareNameBolt                           // Bolt
	RareNameQuarrel                        // Quarrel
	RareNameFletch                         // Fletch
	RareNameFlight                         // Flight
	RareNameNock                           // Nock
	RareNameHorn                           // Horn
	RareNameStinger                        // Stinger
	RareNameQuill                          // Quill
	RareNameGoad                           // Goad
	RareNameBranch                         // Branch
	RareNameSpire                          // Spire
	RareNameSong                           // Song
	RareNameCall                           // Call
	RareNameCry                            // Cry
	RareNameSpall                          // Spell
	RareNameChant                          // Chant
	RareNameWeaver                         // Weaver
	RareNameGnarl                          // Gnarl
	RareNameVisage                         // Visage
	RareNameCrest                          // Crest
	RareNameCirclet                        // Circlet
	RareNameVeil                           // Veil
	RareNameHood                           // Hood
	RareNameMask                           // Mask
	RareNameBrow                           // Brow
	RareNameCasque                         // Casque
	RareNameVisor                          // Visor
	RareNameCowl                           // Cowl
	RareNameHide                           // Hide
	RareNamePelt                           // Pelt
	RareNameCarapace                       // Carapace
	RareNameCoat                           // Coat
	RareNameWrap                           // Wrap
	RareNameSuit                           // Suit
	RareNameCloak                          // Cloak
	RareNameShroud                         // Shroud
	RareNameJack                           // Jack
	RareNameMantle                         // Mantle
	RareNameGuard                          // Guard
	RareNameBadge                          // Badge
	RareNameRock                           // Rock
	RareNameAegis                          // Aegis
	RareNameWard                           // Ward
	RareNameTower                          // Tower
	RareNameShield                         // Shield
	RareNameWing                           // Wing
	RareNameMark                           // Mark
	RareNameEmblem                         // Emblem
	RareNameHand                           // Hand
	RareNameFist                           // Fist
	RareNameClaw                           // Claw
	RareNameClutches                       // Clutches
	RareNameGrip                           // Grip
	RareNameGrasp                          // Grasp
	RareNameGold                           // Hold
	RareNameTorch                          // Torch
	RareNameFinger                         // Finger
	RareNameKnuckle                        // Knuckle
	RareNameShank                          // Shank
	RareNameSpur                           // Spur
	RareNameTread                          // Tread
	RareNameStalker                        // Stalker
	RareNameGreave                         // Greave
	RareNameBlazer                         // Blazer
	RareNameNails                          // Nails
	RareNameTrample                        // Trample
	RareNameBrogues                        // Brogues
	RareNameTrack                          // Track
	RareNameSlippers                       // Slippers
	RareNameClasp                          // Clasp
	RareNameBuckle                         // Buckle
	RareNameGarness                        // Harness
	RareNameLock                           // Lock
	RareNameFringe                         // Fringe
	RareNameWinding                        // Winding
	RareNameChain                          // Chain
	RareNameStrap                          // Strap
	RareNameLash                           // Lash
	RareNameCord                           // Cord
	RareNameKnot                           // Knot
	RareNameCircle                         // Circle
	RareNameLoop                           // Loop
	RareNameEye                            // Eye
	RareNameTurn                           // Turn
	RareNameSpiral                         // Spiral
	RareNameCoil                           // Coil
	RareNameGyre                           // Gyre
	RareNameBand                           // Band
	RareNameWhorl                          // Whorl
	RareNameTalisman                       // Talisman
	RareNameHeart                          // Heart
	RareNameNoose                          // Noose
	RareNameNecklace                       // Necklace
	RareNameCollar                         // Collar
	RareNameBeads                          // Beads
	RareNameTorc                           // Torc
	RareNameGorget                         // Gorget
	RareNameScarab                         // Scarab
	RareNameWood                           // Wood
	RareNameBrand                          // Brand
	RareNameBludgeon                       // Bludgeon
	RareNameCudgel                         // Cudgel
	RareNameLoom                           // Loom
	RareNameHarp                           // Harp
	RareNameMaster                         // Master
	RareNameBarl                           // Barl
	RareNameHew                            // Hew
	RareNameCrook                          // Crook
	RareNameMar                            // Mar
	RareNameShell                          // Shell
	RareNameStake                          // Stake
	RareNamePicket                         // Picket
	RareNamePale                           // Pale
	RareNameFlange                         // Flange
	RareNameBeast                          // Beast
	RareNameEagle                          // Eagle
	RareNameRaven                          // Raven
	RareNameViper                          // Viper
	RareNameGhoul                          // Ghoul
	RareNameSkull                          // Skull
	RareNameBlood                          // Blood
	RareNameDread                          // Dread
	RareNameDoom                           // Doom
	RareNameGrim                           // Grim
	RareNameBone                           // Bone
	RareNameDeath                          // Death
	RareNameShadow                         // Shadow
	RareNameStorm1                         // Storm
	RareNameRune                           // Rune
	RareNamePlague                         // Plague
	RareNameStone                          // Stone
	RareNameWraith                         // Wraith
	RareNameSpirit                         // Spirit
	RareNameStorm2                         // Storm
	RareNameDemon                          // Demon
	RareNameCruel                          // Cruel
	RareNameEmpyrion                       // Empyrion
	RareNameBramble                        // Bramble
	RareNamePain                           // Pain
	RareNameLoath                          // Loath
	RareNameGlyph                          // Glyph
	RareNameImp                            // Imp
	RareNameFiendra                        // Fiendra
	RareNameHailstone                      // Hailstone
	RareNameGale                           // Gale
	RareNameDire                           // Dire
	RareNameSoul                           // Soul
	RareNameBrimstone                      // Brimstone
	RareNameCorpse                         // Corpse
	RareNameCarrion                        // Carrion
	RareNameArmageddon                     // Armageddon
	RareNameHavoc                          // Havoc
	RareNameBitter                         // Bitter
	RareNameEntropy                        // Entropy
	RareNameChaos                          // Chaos
	RareNameOrder                          // Order
	RareNameRule                           // Rule
	RareNameWarp                           // Warp
	RareNameRift                           // Rift
	RareNameCorruption                     // Corruption
)
