// Code generated by "stringer -linecomment -type RunewordID -output runeword_string.go"; DO NOT EDIT.

package itemdata

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RunewordAncientsPladge-27]
	_ = x[RunewordBeast-30]
	_ = x[RunewordBlack-32]
	_ = x[RunewordBone-34]
	_ = x[RunewordBramble-35]
	_ = x[RunewordBrand-36]
	_ = x[RunewordDyingBreath-37]
	_ = x[RunewordCTA-39]
	_ = x[RunewordChains-40]
	_ = x[RunewordChaos-42]
	_ = x[RunewordCrescentMoon-43]
	_ = x[RunewordDeath-46]
	_ = x[RunewordDestruction-50]
	_ = x[RunewordDoom-51]
	_ = x[RunewordDragon-52]
	_ = x[RunewordDream-54]
	_ = x[RunewordDuress-55]
	_ = x[RunewordEdge-56]
	_ = x[RunewordEnigma-58]
	_ = x[RunewordEnlightenment-59]
	_ = x[RunewordEternity-61]
	_ = x[RunewordExile-62]
	_ = x[RunewordFaith-63]
	_ = x[RunewordFamine-64]
	_ = x[RunewordFortitude-66]
	_ = x[RunewordFury-69]
	_ = x[RunewordGloom-70]
	_ = x[RunewordGrief-72]
	_ = x[RunewordJusticeHand-73]
	_ = x[RunewordHarmory-74]
	_ = x[RunewordHOTO-76]
	_ = x[RunewordHolyThunder-79]
	_ = x[RunewordHonor-80]
	_ = x[RunewordIce-84]
	_ = x[RunewordInfinity-85]
	_ = x[RunewordInsight-87]
	_ = x[RunewordKingsGrace-90]
	_ = x[RunewordKingslayer-91]
	_ = x[RunewordLastWish-94]
	_ = x[RunewordLawbringer-96]
	_ = x[RunewordLeaf-97]
	_ = x[RunewordLionheart-99]
	_ = x[RunewordLore-100]
	_ = x[RunewordMalice-105]
	_ = x[RunewordMelody-106]
	_ = x[RunewordMemory-107]
	_ = x[RunewordMyth-111]
	_ = x[RunewordNadir-112]
	_ = x[RunewordOath-115]
	_ = x[RunewordObedience-116]
	_ = x[RunewordPassion-119]
	_ = x[RunewordPeace-122]
	_ = x[RunewordWinter-123]
	_ = x[RunewordPhoenix-127]
	_ = x[RunewordPlague-130]
	_ = x[RunewordPride-133]
	_ = x[RunewordPrinciple-134]
	_ = x[RunewordPrudence-136]
	_ = x[RunewordRadiance-140]
	_ = x[RunewordRain-141]
	_ = x[RunewordRhyme-144]
	_ = x[RunewordRift-145]
	_ = x[RunewordSanctuary-146]
	_ = x[RunewordSilence-150]
	_ = x[RunewordSmoke-152]
	_ = x[RunewordSpirit-154]
	_ = x[RunewordSplendor-155]
	_ = x[RunewordStealth-157]
	_ = x[RunewordSteel-158]
	_ = x[RunewordStone-161]
	_ = x[RunewordStrength-163]
	_ = x[RunewordTreachery-172]
	_ = x[RunewordVenom-178]
	_ = x[RunewordWealth-184]
	_ = x[RunewordWhite-186]
	_ = x[RunewordWind-187]
	_ = x[RunewordWrath-192]
	_ = x[RunewordZephyr-194]
	_ = x[RunewordDelirium-2718]
}

const _RunewordID_name = "Ancient's PledgeBeastBlackBoneBrambleBrandBreath of the DyingCall to ArmsChains of HonorChaosCrescent MoonDeathDestructionDoomDragonDreamDuressEdgeEnigmaEnlightenmentEternityExileFaithFamineFortitudeFuryGloomGriefHand of JusticeHarmoryHeart of the OakHoly ThunderHonorIceInfinityInsightKing's GraceKingslayerLast WishLawbringerLeafLionheartLoreMaliceMelodyMemoryMythNadirOathObediencePassionPeaceWinterPhoenixPlaguePridePrinciplePrudenceRadianceRainRhymeRiftSanctuarySilenceSmokeSpiritSplendorStealthSteelStoneStrengthTreacheryVenomWealthWhiteWindWrathZephyrDelirium"

var _RunewordID_map = map[RunewordID]string{
	27:   _RunewordID_name[0:16],
	30:   _RunewordID_name[16:21],
	32:   _RunewordID_name[21:26],
	34:   _RunewordID_name[26:30],
	35:   _RunewordID_name[30:37],
	36:   _RunewordID_name[37:42],
	37:   _RunewordID_name[42:61],
	39:   _RunewordID_name[61:73],
	40:   _RunewordID_name[73:88],
	42:   _RunewordID_name[88:93],
	43:   _RunewordID_name[93:106],
	46:   _RunewordID_name[106:111],
	50:   _RunewordID_name[111:122],
	51:   _RunewordID_name[122:126],
	52:   _RunewordID_name[126:132],
	54:   _RunewordID_name[132:137],
	55:   _RunewordID_name[137:143],
	56:   _RunewordID_name[143:147],
	58:   _RunewordID_name[147:153],
	59:   _RunewordID_name[153:166],
	61:   _RunewordID_name[166:174],
	62:   _RunewordID_name[174:179],
	63:   _RunewordID_name[179:184],
	64:   _RunewordID_name[184:190],
	66:   _RunewordID_name[190:199],
	69:   _RunewordID_name[199:203],
	70:   _RunewordID_name[203:208],
	72:   _RunewordID_name[208:213],
	73:   _RunewordID_name[213:228],
	74:   _RunewordID_name[228:235],
	76:   _RunewordID_name[235:251],
	79:   _RunewordID_name[251:263],
	80:   _RunewordID_name[263:268],
	84:   _RunewordID_name[268:271],
	85:   _RunewordID_name[271:279],
	87:   _RunewordID_name[279:286],
	90:   _RunewordID_name[286:298],
	91:   _RunewordID_name[298:308],
	94:   _RunewordID_name[308:317],
	96:   _RunewordID_name[317:327],
	97:   _RunewordID_name[327:331],
	99:   _RunewordID_name[331:340],
	100:  _RunewordID_name[340:344],
	105:  _RunewordID_name[344:350],
	106:  _RunewordID_name[350:356],
	107:  _RunewordID_name[356:362],
	111:  _RunewordID_name[362:366],
	112:  _RunewordID_name[366:371],
	115:  _RunewordID_name[371:375],
	116:  _RunewordID_name[375:384],
	119:  _RunewordID_name[384:391],
	122:  _RunewordID_name[391:396],
	123:  _RunewordID_name[396:402],
	127:  _RunewordID_name[402:409],
	130:  _RunewordID_name[409:415],
	133:  _RunewordID_name[415:420],
	134:  _RunewordID_name[420:429],
	136:  _RunewordID_name[429:437],
	140:  _RunewordID_name[437:445],
	141:  _RunewordID_name[445:449],
	144:  _RunewordID_name[449:454],
	145:  _RunewordID_name[454:458],
	146:  _RunewordID_name[458:467],
	150:  _RunewordID_name[467:474],
	152:  _RunewordID_name[474:479],
	154:  _RunewordID_name[479:485],
	155:  _RunewordID_name[485:493],
	157:  _RunewordID_name[493:500],
	158:  _RunewordID_name[500:505],
	161:  _RunewordID_name[505:510],
	163:  _RunewordID_name[510:518],
	172:  _RunewordID_name[518:527],
	178:  _RunewordID_name[527:532],
	184:  _RunewordID_name[532:538],
	186:  _RunewordID_name[538:543],
	187:  _RunewordID_name[543:547],
	192:  _RunewordID_name[547:552],
	194:  _RunewordID_name[552:558],
	2718: _RunewordID_name[558:566],
}

func (i RunewordID) String() string {
	if str, ok := _RunewordID_map[i]; ok {
		return str
	}
	return "RunewordID(" + strconv.FormatInt(int64(i), 10) + ")"
}
